### ISSUE TITLE
Static Pipeline throws `IndexOutOfRangeException` with multiple column mappings

### ISSUE THREAD

**Issue by ixtreon** [dotnet/machinelearning#1180]
### System information

- **OS version/distro**: Windows 10 Pro v1803, build 17134.285
- **.NET Version (eg., dotnet --info)**: 2.1.402 @ commit 3599f217f4

### Issue

- **What did you do?** Translated an existing pipeline for text classification from the "legacy" pipeline builder to the new static API. Starting off with 2 text fields, we'd tokenize them and feed the results into a classifier. The classifier we are using is the FAFM which allows variable number of float vectors to be passed as the input.

- **What happened?** Code throws a `System.IndexOutOfRangeException` exception during training. Removing the second column from the tokenization **and** from the classifier fixes the issue.
- **What did you expect?** Applying the same operation twice and passing 2 `Vector<float>` inputs to the FAFM classifier should train a model using both of these, not crash.

### Source code / logs

```
System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'
   at Microsoft.ML.Runtime.Data.CompositeRowToRowMapper.GetDependencies(Func`2 predicate)
   at Microsoft.ML.Runtime.Data.CompositeRowToRowMapper.GetRow(IRow input, Func`2 active, Action& disposer)
   at Microsoft.ML.Runtime.Data.CompositeRowToRowMapper.GetRow(IRow input, Func`2 active, Action& disposer)
   at Microsoft.ML.Runtime.Data.CompositeRowToRowMapper.GetRow(IRow input, Func`2 active, Action& disposer)
   at Microsoft.ML.Runtime.Data.CompositeRowToRowMapper.GetRow(IRow input, Func`2 active, Action& disposer)
   at Microsoft.ML.Runtime.Data.CompositeRowToRowMapper.GetRow(IRow input, Func`2 active, Action& disposer)
   at Microsoft.ML.Runtime.Data.CompositeRowToRowMapper.GetRow(IRow input, Func`2 active, Action& disposer)
   at Microsoft.ML.Runtime.Api.PredictionEngine`2..ctor(IHostEnvironment env, Func`2 makeMapper, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.Runtime.Api.ComponentCreation.CreatePredictionEngine[TSrc,TDst](IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.Runtime.Data.PredictionFunction`2..ctor(IHostEnvironment env, ITransformer transformer)
   at Microsoft.ML.Runtime.Data.PredictionFunctionExtensions.MakePredictionFunction[TSrc,TDst](ITransformer transformer, IHostEnvironment env)
   at OpenRent.ML.Spam2.SpamTrainer.Foo(IList`1 source)
   at OpenRent.Utils.Scripts.Spam.SpamEvaluator.Run() in C:\OpenRent\OpenRent\OpenRent.Utils\Scripts\Spam\SpamEvaluator.cs:line 99
   at OpenRent.Utils.Program.runScript() in C:\OpenRent\OpenRent\OpenRent.Utils\Program.cs:line 66
   at OpenRent.Utils.Program.Main() in C:\OpenRent\OpenRent\OpenRent.Utils\Program.cs:line 39
```

### Proposed Fix
 - There is what looks like a typo on L39, in the `CompositeRowToRowMapper.cs` file, in the `Microsoft.ML.Data` project. 
 - The line reads: `for (int i = _innerMappers.Length - 1; i <= 0; --i)`
 - In order to loop through all `_innerMappers` the `<=` comparison should be changed to a `>=` . 
 - After changing the sign the code compiles, tests pass and training completes as expected.

**Comment by ixtreon** [comment]
Seems this was resolved with dddb5c13 and is working correctly in v0.7

Thanks!
