### ISSUE TITLE
Type mismatch in TransformSamples.SampleInfertDataWithFeatures

### ISSUE THREAD

**Issue by rantri** [dotnet/machinelearning#1550]
Type should be changed from int to float.

From:
```
class SampleInfertDataWithFeatures
{
    public VBuffer<int> Features { get; set; }
}
```

To:

```
class SampleInfertDataWithFeatures
{
    public VBuffer<float> Features { get; set; }
}
```

It caused exception:
System.InvalidOperationException
  HResult=0x80131509
  Message=Can't bind the IDataView column 'Features' of type 'Vec<R4, 3>' to field or property 'Features' of type 'Microsoft.ML.Runtime.Data.VBuffer`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
  Source=Microsoft.ML.Api
  StackTrace:
   at Microsoft.ML.Runtime.Api.TypedCursorable`1..ctor(IHostEnvironment env, IDataView data, Boolean ignoreMissingColumns, InternalSchemaDefinition schemaDefn) in C:\Users\rtrifon\Documents\GitHub\machinelearning\src\Microsoft.ML.Api\TypedCursor.cs:line 129
   at Microsoft.ML.Runtime.Api.TypedCursorable`1.Create(IHostEnvironment env, IDataView data, Boolean ignoreMissingColumns, SchemaDefinition schemaDefinition) in C:\Users\rtrifon\Documents\GitHub\machinelearning\src\Microsoft.ML.Api\TypedCursor.cs:line 249
   at Microsoft.ML.Runtime.Api.CursoringUtils.AsCursorable[TRow](IDataView data, IHostEnvironment env, Boolean ignoreMissingColumns, SchemaDefinition schemaDefinition) in C:\Users\rtrifon\Documents\GitHub\machinelearning\src\Microsoft.ML.Api\TypedCursor.cs:line 550
   at Microsoft.ML.Runtime.Api.PipeEngine`1..ctor(IHostEnvironment env, IDataView pipe, Boolean ignoreMissingColumns, SchemaDefinition schemaDefinition) in C:\Users\rtrifon\Documents\GitHub\machinelearning\src\Microsoft.ML.Api\PredictionEngine.cs:line 98
   at Microsoft.ML.Runtime.Api.CursoringUtils.AsEnumerable[TRow](IDataView data, IHostEnvironment env, Boolean reuseRowObject, Boolean ignoreMissingColumns, SchemaDefinition schemaDefinition) in C:\Users\rtrifon\Documents\GitHub\machinelearning\src\Microsoft.ML.Api\TypedCursor.cs:line 589
   at Microsoft.ML.Samples.Dynamic.TransformSamples.ConcatTransform() in C:\Users\rtrifon\Documents\GitHub\machinelearning\docs\samples\Microsoft.ML.Samples\Dynamic\ConcatTransform.cs:line 49
   at Microsoft.ML.Samples.Program.Main(String[] args) in C:\Users\rtrifon\Documents\GitHub\machinelearning\docs\samples\Microsoft.ML.Samples\Program.cs:line 13

**Comment by najeeb-kazmi** [comment]
Hi @rantri, where do you run into this exception? I could not reproduce this when building `Microsoft.ML.Samples`. I see that `SamplesUtils.DatasetUtils.GetInfertData()` is returning a dataset with ints. @sfilipi can you confirm that `int` is intentional here?

**Comment by rantri** [comment]
Hi @najeeb-kazmi, There is not code or test that running this sample directly.
To run in I change the Main method to this:

```
namespace Microsoft.ML.Samples
{
    internal static class Program
    {
        static void Main(string[] args)
        {
            TransformSamples.ConcatTransform();
        }
    }
}
```


The "SampleInfertData" are using float too.

```
        public class SampleInfertData
        {
            public int RowNum { get; set; }
            public string Education { get; set; }
            public float Age { get; set; }
            public float Parity { get; set; }
            public float Induced { get; set; }
            public float Case { get; set; }

            public float Spontaneous { get; set; }
            public float Stratum { get; set; }
            public float PooledStratum { get; set; }
        }

```
