### ISSUE TITLE
Training Model fails in Xamarin Notebooks

### ISSUE THREAD

**Issue by cosmincatalin** [dotnet/machinelearning#157]
### System information

- **OS version/distro**: macOS High Sierra (10.13.4)
- **.NET Version (eg., dotnet --info)**: 2.1.4

### Issue

- Tried training a model based on *FastTreeLearner*.
- The pipeline all the way to the model training succeeded, but the training part failed because of a .dll which was not found.
- Training with similar code in Visual Studio works just fine. I expect the Xamarin Notebooks to be compatible with this ML library.

#### The Xamarin Notebook

```
---
uti: com.xamarin.workbook
id: dfsdfsd-sdfsdfsd-sdfsdf-sdfsdfsdf
title: Sample
platforms:
- DotNetCore
packages:
- id: Microsoft.ML
  version: 0.1.0
---
```

```csharp
#r "Microsoft.ML.Api"
#r "Microsoft.ML.Core"
#r "Microsoft.ML.CpuMath"
#r "Microsoft.ML.Data"
#r "Microsoft.ML"
#r "Microsoft.ML.FastTree"
#r "Microsoft.ML.InternalStreams"
#r "Microsoft.ML.KMeansClustering"
#r "Microsoft.ML.Maml"
#r "Microsoft.ML.PCA"
#r "Microsoft.ML.PipelineInference"
#r "Microsoft.ML.ResultProcessor"
#r "Microsoft.ML.StandardLearners"
#r "Microsoft.ML.Sweeper"
#r "Microsoft.ML.Transforms"
#r "Microsoft.ML.UniversalModelFormat"
```

```csharp
using Microsoft.ML.Runtime.Api;
using Microsoft.ML.Models;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;
using System;
```

```csharp
const string DataPath = @"data.csv";
const string ModelPath = @"model.zip";
```

```csharp
#pragma warning disable 0649
public class InputData
{
    [Column("0")]
    public float Feature1;

    [Column("1")]
    public float Feature2;

    [Column("2")]
    public float DependentVariable;
}
```

```csharp
#pragma warning disable 0649
public class OutputPrediction
{
    [ColumnName("Score")]
    public float DependentVariable;
}
```

```csharp
var pipeline = new LearningPipeline();
pipeline.Add(new TextLoader<InputData>(DataPath, useHeader: true, separator: ","));
pipeline.Add(new ColumnCopier(("DependentVariable", "Label")));
pipeline.Add(new ColumnConcatenator("Features", "Feature1", "Feature2"));
pipeline.Add(new FastTreeRegressor() { DiskTranspose = true });
```

```csharp
 try
{
    pipeline.Train<InputData, OutputPrediction>();
}
catch (Exception ex)
{
    Console.Write(ex.ToString());
}
```

### Error at the last step

```
Not adding a normalizer.
Making per-feature arrays
Changing data from row-wise to column-wise on disk
Processed 1000 instances
Binning and forming Feature objects
Reserved memory for tree learner: 2340 bytes
Starting to train ...
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. (Unable to load DLL 'FastTreeNative': The specified module or one of its dependencies could not be found.
(Exception from HRESULT: 0x8007007E)) (Unable to load DLL 'FastTreeNative': The specified module or one of its dependencies could not be found.
(Exception from HRESULT: 0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'FastTreeNative': The specified module or one of its dependencies could not be found.
(Exception from HRESULT: 0x8007007E)
at Microsoft.ML.Runtime.FastTree.Internal.DenseIntArray.C_Sumup_double(Int32 numBits, Byte* pData, Int32* pIndices, Double* pSampleOutputs, Double* pSampleOutputWeights, Double* pSumTargetsByBin, Double* pSumTargets2ByBin, Int32* pCountByBin, Int32 totalCount, Double totalSampleOutputs, Double totalSampleOutputWeights)
at Microsoft.ML.Runtime.FastTree.Internal.DenseIntArray.SumupCPlusPlusDense(SumupInputData input, FeatureHistogram histogram, Byte* data, Int32 numBits)
at Microsoft.ML.Runtime.FastTree.Internal.Dense4BitIntArray.Sumup(SumupInputData input, FeatureHistogram histogram)
at Microsoft.ML.Runtime.FastTree.Internal.FeatureHistogram.SumupWeighted(Int32 numDocsInLeaf, Double sumTargets, Double sumWeights, Double[] outputs, Double[] weights, Int32[] docIndices)
at Microsoft.ML.Runtime.FastTree.Internal.LeastSquaresRegressionTreeLearner.Sumup(SufficientStatsBase stats, Int32 featureMin, LeafSplitCandidates candidates)
at Microsoft.ML.Runtime.FastTree.Internal.LeastSquaresRegressionTreeLearner.FindBestThresholdForFlockThreadWorker(Int32 flock)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of inner exception stack trace ---
at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
at Microsoft.ML.Runtime.FastTree.Internal.ThreadTaskManager.ThreadTask.RunTask()
at Microsoft.ML.Runtime.FastTree.Internal.LeastSquaresRegressionTreeLearner.FindBestSplitOfRoot(Double[] targets)
at Microsoft.ML.Runtime.FastTree.Internal.LeastSquaresRegressionTreeLearner.FitTargets(IChannel ch, Boolean[] activeFeatures, Double[] targets)
at Microsoft.ML.Runtime.FastTree.Internal.GradientDescent.TrainingIteration(IChannel ch, Boolean[] activeFeatures)
at Microsoft.ML.Runtime.FastTree.FastTreeTrainerBase`2.Train(IChannel ch)
at Microsoft.ML.Runtime.FastTree.FastTreeRegressionTrainer.Train(IChannel ch)
at Microsoft.ML.Runtime.FastTree.FastTreeTrainerBase`2.TrainCore(IChannel ch)
at Microsoft.ML.Runtime.FastTree.FastTreeRegressionTrainer.Train(RoleMappedData trainData)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at Microsoft.ML.Runtime.Data.TrainUtils.TrainCore(IHostEnvironment env, IChannel ch, RoleMappedData data, ITrainer trainer, String name, RoleMappedData validData, ICalibratorTrainer calibrator, Int32 maxCalibrationExamples, Nullable`1 cacheData, IPredictor inpPredictor)
at Microsoft.ML.Runtime.EntryPoints.LearnerEntryPointsUtils.Train[TArg,TOut](IHost host, TArg input, Func`1 createTrainer, Func`1 getLabel, Func`1 getWeight, Func`1 getGroup, Func`1 getName, Func`1 getCustom, ICalibratorTrainerFactory calibrator, Int32 maxCalibrationExamples)
at Microsoft.ML.Runtime.FastTree.FastTree.TrainRegression(IHostEnvironment env, Arguments input)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at Microsoft.ML.Runtime.EntryPoints.EntryPointNode.Run()
at Microsoft.ML.Runtime.EntryPoints.EntryPointGraph.RunNode(EntryPointNode node)
at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAllNonMacros()
at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAll()
at Microsoft.ML.LearningPipeline.Train[TInput,TOutput]()
```

**Comment by cosmincatalin** [comment]
Notebooks have established themselves as a key tool for data scientists, with Jupyter leading the way. Xamarin Workbooks is just a trivial REPL if it cannot integrate with the few machine learning libraries that are native to .NET. This is a key use case for both ML.NET and Xamarin Workbooks. Solving this will enable collaboration and faster iteration.
