### ISSUE TITLE
EntryPointSDCARegression test fails intermittenly in Mac Debug with: longIdx=449, invariants.Length=449 

### ISSUE THREAD

**Issue by sfilipi** [dotnet/machinelearning#1726]
Related to #1471

Failure is in [SdcaBinary.cs](https://github.com/dotnet/machinelearning/blob/284e02cadf5342aa0c36f31d62fc6fa15bc06885/src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs#L541)

 Contracts.Assert(0 <= longIdx & longIdx < invariants.Length, $"longIdx={longIdx}, invariants.Length={invariants.Length}");

Test Microsoft.ML.Runtime.RunTests.TestEntryPoints.EntryPointSDCARegression
fails intermittnely in the Mac builds, with failure message:

Assert failed: longIdx=449, invariants.Length=449
Expected: True
Actual: False

Stack trace: 

   at Microsoft.ML.Runtime.Internal.Internallearn.Test.GlobalBase.AssertHandler(String msg, IExceptionContext ectx) in /Users/vsts/agent/2.142.1/work/1/s/test/Microsoft.ML.TestFramework/GlobalBase.cs:line 70
   at Microsoft.ML.Runtime.Contracts.DbgFailCore(String msg, IExceptionContext ctx) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.Core/Utilities/Contracts.cs:line 754
   at Microsoft.ML.Runtime.Contracts.DbgFail(String msg) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.Core/Utilities/Contracts.cs:line 767
   at Microsoft.ML.Runtime.Contracts.Assert(Boolean f, String msg) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.Core/Utilities/Contracts.cs:line 825
   at Microsoft.ML.Trainers.SdcaTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data, LinearPredictor predictor, Int32 weightSetCount) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.StandardLearners/Standard/SdcaBinary.cs:line 541
   at Microsoft.ML.Runtime.Learners.StochasticTrainerBase`2.TrainModelCore(TrainContext context) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.StandardLearners/Standard/StochasticTrainerBase.cs:line 42
   at Microsoft.ML.Runtime.Training.TrainerEstimatorBase`2.Microsoft.ML.Runtime.ITrainer<TModel>.Train(TrainContext context) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs:line 94
   at Microsoft.ML.Runtime.Training.TrainerEstimatorBase`2.Microsoft.ML.Runtime.ITrainer.Train(TrainContext context) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs:line 161
   at Microsoft.ML.Runtime.Data.TrainUtils.TrainCore(IHostEnvironment env, IChannel ch, RoleMappedData data, ITrainer trainer, RoleMappedData validData, IComponentFactory`1 calibrator, Int32 maxCalibrationExamples, Nullable`1 cacheData, IPredictor inputPredictor, RoleMappedData testData) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.Data/Commands/TrainCommand.cs:line 278
   at Microsoft.ML.Runtime.Data.TrainUtils.Train(IHostEnvironment env, IChannel ch, RoleMappedData data, ITrainer trainer, IComponentFactory`1 calibrator, Int32 maxCalibrationExamples) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.Data/Commands/TrainCommand.cs:line 247
   at Microsoft.ML.Runtime.EntryPoints.LearnerEntryPointsUtils.Train[TArg,TOut](IHost host, TArg input, Func`1 createTrainer, Func`1 getLabel, Func`1 getWeight, Func`1 getGroup, Func`1 getName, Func`1 getCustom, ICalibratorTrainerFactory calibrator, Int32 maxCalibrationExamples) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.Data/EntryPoints/InputBase.cs:line 190
   at Microsoft.ML.Trainers.Sdca.TrainRegression(IHostEnvironment env, Arguments input) in /Users/vsts/agent/2.142.1/work/1/s/src/Microsoft.ML.StandardLearners/Standard/SdcaRegression.cs:line 189

**Comment by glebuk** [comment]
@sfilipi  - please verify that PR #1884 has addressed this and close.

**Comment by sfilipi** [comment]
Closing, since with PR #1884 I couldn't steadily repro the problem, and the EntryPointSDCARegression test is not one of the top failing tests (it is the 84th for the last 14 days.)
