### ISSUE TITLE
Feature type, input, and output validation should happen much earlier

### ISSUE THREAD

**Issue by shaunco** [dotnet/machinelearning#184]
Validation of feature vector types, inputs, and outputs seems to happen randomly throughout the learning pipeline - sometimes after a few minutes, sometimes after an hour.  It would really be great if this happened up front so that errors could be corrected faster.  It would also be great if some of these were documented.

For example:
```cs
public class InputData
{
    [Column("0")]
    public double input0;

    [Column("1")]
    public double input1;

    [Column("2", name: "Label")]
    public double output0;
}

public class OutputData
{
    [ColumnName("Score")]
    public double output0;
}

public class Program
{
    static void Main(string[] args)
    {
        var pipeline = new LearningPipeline();
        pipeline.Add(new TextLoader<InputData>("mydata.txt", separator: "comma"));
        pipeline.Add(new ColumnConcatenator("Features", "input0", "input1");
        pipeline.Add(new FastTreeRegressor());
        var model = pipeline.Train<InputData, OutputData>();
    }
}
```

Running this with a very large "mydata.txt" gives output of:
```
Not adding a normalizer.
Making per-feature arrays
Changing data from row-wise to column-wise
Warning: We seem to be processing a lot of data. Consider using the FastTree diskTranspose+ (or dt+) option, for slower but more memory efficient transposition.
Processed 1112251 instances
Binning and forming Feature objects
Reserved memory for tree learner: 10301148 bytes
Starting to train ...
Not training a calibrator because it is not needed.
```

And then about 15 minutes later, an exception occurs:
```
Incompatible features column type item type: 'R8' vs 'R4'

   at Microsoft.ML.Runtime.Data.SchemaBindablePredictorWrapperBase.Bind(IHostEnvironment env, RoleMappedSchema schema)
   at Microsoft.ML.Runtime.Data.GenericScorer.Bindings.Create(IHostEnvironment env, ISchemaBindableMapper bindable, ISchema input, IEnumerable`1 roles, String suffix, Boolean user)
   at Microsoft.ML.Runtime.Data.GenericScorer..ctor(IHost host, ModelLoadContext ctx, IDataView input)
   at Microsoft.ML.Runtime.Data.GenericScorer.<>c__DisplayClass15_0.<Create>b__0(IChannel ch)
   at Microsoft.ML.Runtime.HostExtensions.Apply[T](IHost host, String channelName, Func`2 func)
   at Microsoft.ML.Runtime.Data.GenericScorer.Create(IHostEnvironment env, ModelLoadContext ctx, IDataView input)
```

After lots of digging through code, it turns out only float types are supported - not doubles. Why didn't the docs say this and why wasn't I told almost immediately when I called Train()?

**Comment by glebuk** [comment]
Thanks for reporting the issue.  Indeed, we should document that input and output fields for the pipeline should be float.   IT would be also good to validate input/output types first.

The actual reason for the observed behavior is that we automatically convert doubles to floats for training, however, the scoring code does not.  Scoring only fires after training is complete, in your case after 15 minutes.

**Comment by anneomcl** [comment]
Just ran into this as well, adding my +1 for documenting and validating inputs.

**Comment by jwood803** [comment]
Also, this error message `Incompatible features column type item type: 'R8' vs 'R4'` seems a bit vague. Would it be worthwhile to try to also make a more understandable error message as part of this?
