### ISSUE TITLE
Could not find input column 'MovieID'

### ISSUE THREAD

**Issue by kinosang** [dotnet/machinelearning#1968]
### System information

- **OS version/distro**: Mac
- **.NET Version (eg., dotnet --info)**: 2.2.100, ML 0.8.0

### Issue

- **What did you do?**
I modified the official e2e MovieRecommender model training program to build a genres-based recommender.
- **What happened?**
In step 7 Try/test a single prediction by predicting a single movie rating for a specific user, it throw an `ArgumentOutOfRangeException:  Could not find input column 'MovieId'`

- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

Codes:
```
//STEP 2: Create a reader by defining the schema for reading the gallery recommendation datasets
var reader = ctx.Data.TextReader(new TextLoader.Arguments
{
    // Separator = "comma",
    // HasHeader = true,
    Column = new[]
    {
        new TextLoader.Column("UserId", DataKind.Text, 0),
        new TextLoader.Column("MovieID", DataKind.Text, 1),
        new TextLoader.Column("Title", DataKind.Text, 2),
        new TextLoader.Column("Genres", DataKind.Text, 3),
        new TextLoader.Column("Rating", DataKind.Bool, 4)
    }
});

......

//STEP 4: Transform your data by encoding the two features userId and movieId. 
//        These encoded features will be provided as input to FieldAwareFactorizationMachine learner
var pipeline = ctx.Transforms.Categorical.OneHotEncoding("UserId", "UserIdEncoded")
    .Append(ctx.Transforms.Categorical.OneHotEncoding("MovieID", "MovieIDEncoded")
        .Append(ctx.Transforms.Text.TokenizeWords("Genres", "GenresTokens", new[] {'|'})
            .Append(ctx.Transforms.Text.ExtractWordEmbeddings("GenresTokens", "GenresEmbeddings",
                    WordEmbeddingsExtractingTransformer.PretrainedModelKind.GloVeTwitter25D)
                .Append(ctx.Transforms.Concatenate("Features", "UserIdEncoded", "MovieIDEncoded",
                    "GenresEmbeddings"))
                .Append(ctx.BinaryClassification.Trainers.FieldAwareFactorizationMachine(
                    labelColumn: "Rating",
                    featureColumns: new[]
                    {
                        "Features"
                    })
                ))));

......

//STEP 7:  Try/test a single prediction by predicting a single movie rating for a specific user
var predictionengine = model.MakePredictionFunction<TrainingData, RatingPrediction>(ctx); // line 76
var movieratingprediction = predictionengine.Predict(
    new TrainingData
    {
        //Example rating prediction for userId = 6, movieId = 10 (GoldenEye)
        UserId = "6",
        MovieId = "17"
    }
);

......
public class TrainingData
{
    public string UserId;

    public string MovieId;

    public string Title;

    public string Genres;

    public float Rating;

    public string Timestamp;
}
```

Logs:
```
Unhandled Exception: System.ArgumentOutOfRangeException: Could not find input column 'MovieId'
Parameter name: inputSchema
   at Microsoft.ML.Runtime.Data.OneToOneTransformerBase.CheckInput(ISchema inputSchema, Int32 col, Int32& srcCol)
   at Microsoft.ML.Runtime.Data.OneToOneTransformerBase.OneToOneMapperBase..ctor(IHost host, OneToOneTransformerBase parent, Schema inputSchema)
   at Microsoft.ML.Transforms.Text.WordTokenizingTransformer.Mapper..ctor(WordTokenizingTransformer parent, Schema inputSchema)
   at Microsoft.ML.Transforms.Text.WordTokenizingTransformer.MakeRowMapper(Schema schema)
   at Microsoft.ML.Runtime.Data.RowToRowTransformerBase.GetRowToRowMapper(Schema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.GetRowToRowMapper(Schema inputSchema)
   at Microsoft.ML.Runtime.Api.PredictionEngineBase`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.Runtime.Api.ComponentCreation.CreatePredictionEngine[TSrc,TDst](IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.Runtime.Data.PredictionFunction`2..ctor(IHostEnvironment env, ITransformer transformer)
   at Microsoft.ML.Runtime.Data.PredictionFunctionExtensions.MakePredictionFunction[TSrc,TDst](ITransformer transformer, IHostEnvironment env)
   at model.Program.Main(String[] args) in Program.cs:line 76
```

I've set breakpoint on OneToOneTransformerBase line 77
https://github.com/dotnet/machinelearning/blob/51ea627fbc618120c7d63ab984b1b13c6d80b4a0/src/Microsoft.ML.Data/Transforms/OneToOneTransformerBase.cs#L77

and I got this
![](https://i.imgur.com/BED6j2R.jpg)

I also tried to change the order of the transforms in pipeline, for e.g. `TokenizeWords("Genres", balabala)` - `ExtractWordEmbeddings("GenresTokens", balabala)` - `OneHotEncoding("UserId", balabala)` - `OneHotEncoding("MovieID", balabala)`, it still raises the ArgumentOutOfRangeException but shows different message (in this order the message is ` Could not find input column 'Genres'`).

**Comment by Ivanidzo4ka** [comment]
`new TextLoader.Column("MovieID", DataKind.Text, 1),`
We are case sensitive regarding column names

**Comment by kinosang** [comment]
@Ivanidzo4ka oh, thx, I just did not catch your point, the column should be `MovieId` (the last char is lowercase).

sorry for the mistake 😂
