### ISSUE TITLE
KmeansOnnxConversionTest failing on NetCoreApp3.0

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#2087]
KmeansOnnxConversionTest is failing on NetCoreApp3.0
This happened after we changed the version of netcoreapp sdk to 3.0 preview1
Associated PR https://github.com/dotnet/machinelearning/pull/2082

This is not caused due to any change in cpumath library as it is even reproducable by using the software implementation of the functions.

```
2019-01-09T01:44:33.0500908Z [xUnit.net 00:01:21.86]     Microsoft.ML.Tests.OnnxConversionTest.KmeansOnnxConversionTest [FAIL]
2019-01-09T01:44:33.3587704Z Failed   Microsoft.ML.Tests.OnnxConversionTest.KmeansOnnxConversionTest
2019-01-09T01:44:33.3591191Z Error Message:
2019-01-09T01:44:33.3644424Z  Assert.Equal() Failure
2019-01-09T01:44:33.3644561Z Expected: 0 (rounded from 0)
2019-01-09T01:44:33.3648151Z Actual:   NaN (rounded from NaN)
2019-01-09T01:44:33.3648305Z Stack Trace:
2019-01-09T01:44:33.3648786Z    at Microsoft.ML.Tests.OnnxConversionTest.CompareSelectedR4VectorColumns(String leftColumnName, String rightColumnName, IDataView left, IDataView right, Int32 precision) in D:\a\1\s\test\Microsoft.ML.Tests\OnnxConversionTest.cs:line 500
2019-01-09T01:44:33.3648953Z    at Microsoft.ML.Tests.OnnxConversionTest.KmeansOnnxConversionTest() in D:\a\1\s\test\Microsoft.ML.Tests\OnnxConversionTest.cs:line 159
2019-01-09T01:44:33.3649371Z Standard Output Messages:
2019-01-09T01:44:33.3649668Z  Test KmeansOnnxConversionTest: aborted: passed
```

cc @eerhardt @danmosemsft @tannergooding

**Comment by eerhardt** [comment]
It would be helpful to list what is failing about the test. Are base lined numbers not comparing? Is an exception happening? etc.

**Comment by Anipik** [comment]
>  It would be helpful to list what is failing about the test

I intended to add the reason but i just forget while creathing the issue :P i updated the issue
there is no exception happening and its not a baseline comparision.

**Comment by wschin** [comment]
Does this problem still exist? I saw that ML.NET passes all CI tests.

**Comment by Anipik** [comment]
The test is disabled for .NET core 3 https://github.com/dotnet/machinelearning/blob/fabdabf867dc68481d519740a96b981bbeb63180/test/Microsoft.ML.Tests/OnnxConversionTest.cs#L127

**Comment by frank-dong-ms** [comment]
Test is passing after upgrade to dotnet core 3.1
