### ISSUE TITLE
Build system for Mac machines is broken on homebrew state.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2103]
```019-01-10T00:14:33.9225520Z Updating Homebrew...```
```019-01-10T00:15:19.2254360Z /usr/local/Homebrew/Library/Homebrew/config.rb:39:in 'initialize': no implicit conversion of nil into String (TypeError)
2019-01-10T00:15:19.2255080Z 	from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in 'new'
2019-01-10T00:15:19.2255680Z 	from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in '<top (required)>'
2019-01-10T00:15:19.2256260Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
2019-01-10T00:15:19.2256920Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
2019-01-10T00:15:19.2257470Z 	from /usr/local/Homebrew/Library/Homebrew/global.rb:25:in '<top (required)>'
2019-01-10T00:15:19.2258050Z 	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in 'require_relative'
2019-01-10T00:15:19.2258570Z 	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in '<main>'```

**Comment by Ivanidzo4ka** [comment]
related to https://github.com/dotnet/coreclr/issues/21910
