### ISSUE TITLE
Not able to load Whitening Module in Maml on full framework

### ISSUE THREAD

**Issue by Anipik** [dotnet/machinelearning#2104]
```
[xUnit.net 00:00:03.65]     Microsoft.ML.Tests.Transformers.NormalizerTests.TestWhiteningCommandLine [FAIL]
Failed   Microsoft.ML.Tests.Transformers.NormalizerTests.TestWhiteningCommandLine
Error Message:
 System.InvalidOperationException : Unknown loadable class: whitening
Stack Trace:
   at Microsoft.ML.Tools.Maml.MainCore(IHostEnvironment env, String args, Boolean alwaysPrintStacktrace) in C:\git\machinelearning\src\Microsoft.ML.Maml\MAML.cs:line 210
   at Microsoft.ML.Tools.Maml.MainWithProgress(String args) in C:\git\machinelearning\src\Microsoft.ML.Maml\MAML.cs:line 68
   at Microsoft.ML.Tools.Maml.MainAll(String args) in C:\git\machinelearning\src\Microsoft.ML.Maml\MAML.cs:line 45
   at Microsoft.ML.Tools.Maml.Main(String[] args) in C:\git\machinelearning\src\Microsoft.ML.Maml\MAML.cs:line 34
   at Microsoft.ML.Tests.Transformers.NormalizerTests.TestWhiteningCommandLine() in C:\git\machinelearning\test\Microsoft.ML.Tests\Transformers\NormalizerTests.cs:line 332
```

I am trying to run TestWhiteningCommandLine test on netfx. The test using Maml.Main and it is not able to load the whitening module.

Adding ``` Type t = typeof(VectorWhiteningTransformer);``` helps solve the issue but I think we may require more permanent solution

cc @danmosemsft @eerhardt @TomFinley

**Comment by Ivanidzo4ka** [comment]
Does SymSgd, Ols learner tests works fine? 
`Type t = typeof(VectorWhiteningTransformer)`
this looks like indication what we just don't link HalLearner project properly to our tests.

**Comment by Anipik** [comment]
> Does SymSgd, Ols learner tests works fine?

yes there is no similar failure.
