### ISSUE TITLE
LightGbmMulti System.ArgumentOutOfRangeException: Schema mismatch for label column '': expected Bool, got Key<U4>

### ISSUE THREAD

**Issue by Dmitry-A** [dotnet/machinelearning#2534]
running with 0.10 bits, started getting this error on certain datasets when benchmarking AutoML (not 100% positive but likely this started happening when we upgraded to 0.10):

Processing pipeline ColumnCopying{ col=Label:0} xf=ValueToKeyMapping{ col=Label:Label} tr=LightGbmMulti{}.
LightGbmMulti{} Crashed System.ArgumentOutOfRangeException: Schema mismatch for label column '': expected Bool, got Key<U4>
Parameter name: labelCol
   at Microsoft.ML.Training.TrainerEstimatorBase`2.CheckLabelCompatible(Column labelCol)
   at Microsoft.ML.Training.TrainerEstimatorBase`2.CheckInputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Training.TrainerEstimatorBase`2.GetOutputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Data.EstimatorChain`1.GetOutputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.Auto.SuggestedPipeline.Fit(IDataView trainData)
   at Microsoft.ML.Auto.AutoFitter`1.ProcessPipeline(SuggestedPipeline pipeline)

Note that we're adding ValueToKeyMapping to our pipelines to get around https://github.com/dotnet/machinelearning/issues/1969

**Comment by Ivanidzo4ka** [comment]
Should be fixed in https://github.com/dotnet/machinelearning/pull/2476

**Comment by Ivanidzo4ka** [comment]
Actually got fixed in https://github.com/dotnet/machinelearning/pull/2448
