### ISSUE TITLE
Ranker Evaluate doesn't allow you specify metric parameters.

### ISSUE THREAD

**Issue by Ivanidzo4ka** [dotnet/machinelearning#2728]
https://github.com/dotnet/machinelearning/blob/3b9d407d9dc4f8c46fa85ab80575ef16d74df6df/src/Microsoft.ML.Data/TrainCatalog.cs#L626
I can't specify how deep I want to calculate NDCG@i (i.e. i maximum), I can't specify custom gains.

**Comment by nicolehaugen** [comment]
This issue prevents for using the Ranking Evaluator when you have rank cardinality > 5.  By default, the underlying args (specified in the src/Microsoft.ML.FastTree/FastTreeRankingTrainer.cs file) specify the CustomGains to be a size of 5:

          public double[] CustomGains = new double[] { 0, 3, 7, 15, 31 };

As a result, when you attempt to use a the Ranking Evaluator to do ranking on values that are more than 5 (for example, if you rank values 1-10), you get the following exception:

System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Microsoft.ML.Data
  StackTrace:
   at Microsoft.ML.Data.RankingUtils.QueryMaxDcg(Double[] labelGains, Int32 truncationLevel, List`1 queryLabels, List`1 queryOutputs, Double[] groupMaxDcgCur) in E:\A\_work\449\s\src\Microsoft.ML.Data\Evaluators\RankingEvaluator.cs:line 991
   at Microsoft.ML.Data.RankingEvaluator.Aggregator.Counters.UpdateGroup(Single weight) in E:\A\_work\449\s\src\Microsoft.ML.Data\Evaluators\RankingEvaluator.cs:line 377
   at Microsoft.ML.Data.RankingEvaluator.Aggregator.ProcessGroup() in E:\A\_work\449\s\src\Microsoft.ML.Data\Evaluators\RankingEvaluator.cs:line 505
   at Microsoft.ML.Data.RankingEvaluator.Aggregator.ProcessRow() in E:\A\_work\449\s\src\Microsoft.ML.Data\Evaluators\RankingEvaluator.cs:line 471
   at Microsoft.ML.Data.EvaluatorBase`1.ProcessData(IDataView data, RoleMappedSchema schema, Func`2 activeColsIndices, TAgg aggregator, AggregatorDictionaryBase[] dictionaries) in E:\A\_work\449\s\src\Microsoft.ML.Data\Evaluators\EvaluatorBase.cs:line 166
   at Microsoft.ML.Data.EvaluatorBase`1.Microsoft.ML.Data.IEvaluator.Evaluate(RoleMappedData data) in E:\A\_work\449\s\src\Microsoft.ML.Data\Evaluators\EvaluatorBase.cs:line 38
   at Microsoft.ML.Data.RankingEvaluator.Evaluate(IDataView data, String label, String groupId, String score) in E:\A\_work\449\s\src\Microsoft.ML.Data\Evaluators\RankingEvaluator.cs:line 254
   at Microsoft.ML.RankingCatalog.Evaluate(IDataView data, String labelColumnName, String

**Comment by eerhardt** [comment]
@Ivanidzo4ka @codemzs @wschin @yaeldekel - It would seem to me that `RankingCatalog.Evaluate()` is pretty useless without fixing this. Any chance this can be fixed in the near term?

**Comment by harishsk** [comment]
RankingEvaluatorOptions have been added with the linked bug/pr.
