### ISSUE TITLE
LinearSupportVectorMachines trained Model not working

### ISSUE THREAD

**Issue by 1amirjalai** [dotnet/machinelearning#3145]
### System information

- **OS windows 10**:
- **.NET Version (Microsoft.NETCore.App 2.2.3)**: 

### Issue

- **What did you do?**
trained a model using LinearSupportVectorMachines
- **What happened?**
The model was created then i load the model and tried to predict on the model but it shows exception
```
Unhandled Exception: System.ArgumentOutOfRangeException: Could not find input column 'IdPreservationColumn'
Parameter name: inputSchema
   at Microsoft.ML.Data.ColumnConcatenatingTransformer.Mapper.MakeColumn(DataViewSchema inputSchema, Int32 iinfo)
   at Microsoft.ML.Data.ColumnConcatenatingTransformer.Mapper..ctor(ColumnConcatenatingTransformer parent, DataViewSchema inputSchema)
   at Microsoft.ML.Data.ColumnConcatenatingTransformer.MakeRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.RowToRowTransformerBase.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.PredictionEngineBase`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
```
- **What did you expect?**
I expected to predict based on loaded trained model
### Source code / logs

IdPreservationColumn i don't know what this is and i can't find any document about it

**Comment by sfilipi** [comment]
@1amirjalai Is there any column on your dataset with name "IdPreservationColumn" ?
Can you post your full pipeline, and one row of your data?

**Comment by ganik** [comment]
closing this as author has not replied for request for more info since March 2019
