### ISSUE TITLE
Exception on using LightGBM trainer with FeatureContributionCalculation and OneHotEncoding

### ISSUE THREAD

**Issue by vKuryshev** [dotnet/machinelearning#3272]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 4.7.1

### Issue

- **What did you do?**
I used FeatureContributionCalculation with LightGbm trainer. My data pipeline contains OneHotEncoding features.
- **What happened?**
When I try to get feature contribution calculation I get the following exception
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Splitter/consolidator worker encountered exception while consuming source data
  Source=Microsoft.ML.Data
  StackTrace:
   at Microsoft.ML.Data.DataViewUtils.Splitter.Batch.SetAll(OutPipe[] pipes)
   at Microsoft.ML.Data.DataViewUtils.Splitter.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Data.ColumnCursorExtensions.<GetColumnArrayDirect>d__3`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.BuildTrainEvaluateAndSaveModel(MLContext mlContext) in C:\Users\vladimir.kuryshev\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 150
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\vladimir.kuryshev\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 45

Inner Exception 1:
ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: slot

   at Microsoft.ML.Data.VBuffer`1.GetItemOrDefault(Int32 slot)
   at Microsoft.ML.Trainers.FastTree.InternalRegressionTree.AppendFeatureContributions(VBuffer`1& src, BufferBuilder`1 contributions)
   at Microsoft.ML.Trainers.FastTree.InternalTreeEnsemble.GetFeatureContributions(VBuffer`1& features, VBuffer`1& contribs, BufferBuilder`1& builder)
   at Microsoft.ML.Trainers.FastTree.TreeEnsembleModelParameters.<>c__DisplayClass30_0`2.<Microsoft.ML.Model.IFeatureContributionMapper.GetFeatureContributionMapper>b__0(VBuffer`1& src, VBuffer`1& dst)
   at Microsoft.ML.Data.DataViewUtils.Splitter.InPipe.Impl`1.Fill()
   at Microsoft.ML.Data.DataViewUtils.Splitter.<>c__DisplayClass5_1.<ConsolidateCore>b__2()
```
### Source code / logs
My code example
```
   IDataView trainingDataView = mlContext.Data.LoadFromTextFile<TaxiTrip>(TrainDataPath, hasHeader: true, separatorChar: ',');
   var dataProcessPipeline = mlContext.Transforms.CopyColumns(outputColumnName: DefaultColumnNames.Label, inputColumnName: nameof(TaxiTrip.FareAmount))
                            .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: VendorIdEncoded, inputColumnName: nameof(TaxiTrip.VendorId)))
                            .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: RateCodeEncoded, inputColumnName: nameof(TaxiTrip.RateCode)))
                            .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: PaymentTypeEncoded, inputColumnName: nameof(TaxiTrip.PaymentType)))
                            .Append(mlContext.Transforms.Normalize(outputColumnName: nameof(TaxiTrip.PassengerCount), mode: NormalizingEstimator.NormalizerMode.MeanVariance))
                            .Append(mlContext.Transforms.Normalize(outputColumnName: nameof(TaxiTrip.TripTime), mode: NormalizingEstimator.NormalizerMode.MeanVariance))
                            .Append(mlContext.Transforms.Normalize(outputColumnName: nameof(TaxiTrip.TripDistance), mode: NormalizingEstimator.NormalizerMode.MeanVariance))
                            .Append(mlContext.Transforms.Concatenate(DefaultColumnNames.Features, VendorIdEncoded, RateCodeEncoded, PaymentTypeEncoded, nameof(TaxiTrip.PassengerCount)
                            , nameof(TaxiTrip.TripTime), nameof(TaxiTrip.TripDistance)));

   var trainer = mlContext.Regression.Trainers.LightGbm(labelColumnName: DefaultColumnNames.Label, featureColumnName: DefaultColumnNames.Features);
   var trainingPipeline = dataProcessPipeline.Append(trainer);

   var trainedModel = trainingPipeline.Fit(trainingDataView);
   IDataView predictions = trainedModel.Transform(testDataView);

   var featureContributionCalculation = mlContext.Model.Explainability.FeatureContributionCalculation(trainedModel.LastTransformer.Model);
   var featureContributionData = featureContributionCalculation.Fit(predictions).Transform(predictions);
   var contributions = featureContributionData.GetColumn<float[]>(mlContext, DefaultColumnNames.FeatureContributions).ToList();
```
I used standard data from "taxi-fare-train.csv" file from ML.Net examples.

- **Note** Issue can't be reproduced If i remove OneHotEncoding from pipeline or change trainer to FastTree for example.

**Comment by rogancarr** [comment]
@vKuryshev Thanks for reporting this issue! Definitely not the expected results :)

@wschin This looks like a bug. Have you been able to reproduce it?

**Comment by antoniovs1029** [comment]
I was able to reproduce this issue. There have been some changes on the API since this Issue was opened, so just for the record I'll leave here a full repro using the latest API. I will look into this.

```C#
using System;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Data;

namespace Bugs
{
    public class TaxiTrip
    {
        [LoadColumn(0)]
        public string VendorId;

        [LoadColumn(1)]
        public float RateCode;

        [LoadColumn(2)]
        public float PassengerCount;

        [LoadColumn(3)]
        public float TripTime;

        [LoadColumn(4)]
        public float TripDistance;

        [LoadColumn(5)]
        public string PaymentType;

        [LoadColumn(6)]
        public float FareAmount;
    }

    static class DefaultColumnNames
    {
        public const string Features = "Features";
        public const string Label = "Label";
        public const string GroupId = "GroupId";
        public const string Name = "Name";
        public const string Weight = "Weight";
        public const string Score = "Score";
        public const string Probability = "Probability";
        public const string PredictedLabel = "PredictedLabel";
        public const string RecommendedItems = "Recommended";
        public const string User = "User";
        public const string Item = "Item";
        public const string Date = "Date";
        public const string FeatureContributions = "FeatureContributions";
    }

    class Program
    {
        static void Main(string[] args)
        {
            var TrainDataPath = @"C:\Users\anvelazq\Desktop\mymlnet\test\data\taxi-fare-train.csv";
            var TestDataPath = @"C:\Users\anvelazq\Desktop\mymlnet\test\data\taxi-fare-test.csv";

            var mlContext = new MLContext();
            IDataView trainingDataView = mlContext.Data.LoadFromTextFile<TaxiTrip>(TrainDataPath, hasHeader: true, separatorChar: ',');
            IDataView testDataView = mlContext.Data.LoadFromTextFile<TaxiTrip>(TestDataPath, hasHeader: true, separatorChar: ',');

            var VendorIdEncoded = "VendorIdEncoded";
            var RateCodeEncoded = "RateCodeEncoded";
            var PaymentTypeEncoded = "PaymentTypeEncoded";

            var dataProcessPipeline = mlContext.Transforms.CopyColumns(outputColumnName: DefaultColumnNames.Label, inputColumnName: nameof(TaxiTrip.FareAmount))
                                     .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: VendorIdEncoded, inputColumnName: nameof(TaxiTrip.VendorId)))
                                     .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: RateCodeEncoded, inputColumnName: nameof(TaxiTrip.RateCode)))
                                     .Append(mlContext.Transforms.Categorical.OneHotEncoding(outputColumnName: PaymentTypeEncoded, inputColumnName: nameof(TaxiTrip.PaymentType)))
                                     .Append(mlContext.Transforms.NormalizeMeanVariance(outputColumnName: nameof(TaxiTrip.PassengerCount)))
                                     .Append(mlContext.Transforms.NormalizeMeanVariance(outputColumnName: nameof(TaxiTrip.TripTime)))
                                     .Append(mlContext.Transforms.NormalizeMeanVariance(outputColumnName: nameof(TaxiTrip.TripDistance)))
                                     .Append(mlContext.Transforms.Concatenate(DefaultColumnNames.Features, VendorIdEncoded, RateCodeEncoded, PaymentTypeEncoded, nameof(TaxiTrip.PassengerCount)
                                     , nameof(TaxiTrip.TripTime), nameof(TaxiTrip.TripDistance))); 

            var trainer = mlContext.Regression.Trainers.LightGbm(labelColumnName: DefaultColumnNames.Label, featureColumnName: DefaultColumnNames.Features);
            var trainingPipeline = dataProcessPipeline.Append(trainer);

            var trainedModel = trainingPipeline.Fit(trainingDataView);
            IDataView predictions = trainedModel.Transform(testDataView);

            var featureContributionCalculation = mlContext.Transforms.CalculateFeatureContribution(trainedModel.LastTransformer, normalize: false);
            var featureContributionData = featureContributionCalculation.Fit(predictions).Transform(predictions);
            var contributions = featureContributionData.GetColumn<float[]>(DefaultColumnNames.FeatureContributions).ToList();
        }
    }
}
```

**Comment by antoniovs1029** [comment]
I've realized that this exception only appears if the training dataset of the LightGBM trainer has 50,001 rows or more. If I take only the first 50,000 or less rows to train, then the exception doesn't appear, and everything works as expected.

This happens because if the training set has over 50,000 rows, then this method will construct Categorical Feature Metadata.

https://github.com/dotnet/machinelearning/blob/1ea53362a692e551737341787d7b49541c28dfb8/src/Microsoft.ML.LightGbm/LightGbmTrainerBase.cs#L528-L558

I am still not sure why this affects the sample and causes the exception. But if I change the above method to never construct the categorical feature metadata, then the provided sample works without exception even when having over 50,000 rows.

**Comment by antoniovs1029** [comment]
The particular exception of this sample comes because any given `InternalRegressionTree` of the trained model has a `SplitFeatures` array with negative values (in one particular run it's `SplitFeatures = [-1, 8, 7]`, it seems there's always a -1) which is then used in the `AppendFeatureContributions` method to get a value from a VBuffer, so it throws when trying to access the negative index.

https://github.com/dotnet/machinelearning/blob/1ea53362a692e551737341787d7b49541c28dfb8/src/Microsoft.ML.FastTree/TreeEnsemble/InternalRegressionTree.cs#L1518-L1519

I am assuming that it's incorrect that the `SplitFeatures` array has negative numbers, so there must be something wrong when creating the array.

It seems that array is created, for every tree on the ensemble, in the `LightGBM.Booster.GetModel` method:
https://github.com/dotnet/machinelearning/blob/1ea53362a692e551737341787d7b49541c28dfb8/src/Microsoft.ML.LightGbm/WrappedLightGbmBooster.cs#L189

Particularly, it is the `splitFeature `array that is passed to the `InternalRegressionTree `constructor of every Tree.

Notice that the `categoricalFeatureBoudaries` parameter of the method affects the `splitFeature ` array. And notice that categoricalFeatureBoundaries is null if the LightGBM trainer had `catMetaData.CategoricalBoudaries = null` in the `GetCategoricalMetaData` method.

Still, something that is odd is that in the LightGBM.Booster.GetModel method explicitly assigns "-1" values to the `splitFeature` array. So I don't still know what's the purpose of doing that, and specially I don't know if that's a mistake or if it's intended, since that array is then used in `AppendFeatureContributions` to get the values from the VBuffer.
