### ISSUE TITLE
CreateTextLoader isn't respecting the KeyType attribute

### ISSUE THREAD

**Issue by nicolehaugen79** [dotnet/machinelearning#3811]
### System information

.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.503\

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

### Issue

I used LoadFromTextFile to load data where the loaded poco object has the KeyType attribute applied as follows:

   private class DataPoint
        {
            [LoadColumn(0), KeyType(5)]
            public uint Label { get; set; }
            [LoadColumn(1), KeyType(100)]
            public uint GroupId { get; set; }
            [LoadColumn(2,52), VectorType(50)]
            public float[] Features { get; set; }
        }

When I call Fit using the LightGbm algorithm, I see the following exception because the KeyType attribute isn't being respected when loading from a text file:

System.ArgumentOutOfRangeException  HResult=0x80131502
  Message=Schema mismatch for label column 'Label': expected Single or Key, got UInt32
Parameter name: labelCol
  Source=Microsoft.ML.LightGbm
  StackTrace:
   at Microsoft.ML.Trainers.LightGbm.LightGbmRankingTrainer.<>c__DisplayClass9_0.<CheckLabelCompatible>b__0() in E:\A\_work\449\s\src\Microsoft.ML.LightGbm\LightGbmRankingTrainer.cs:line 240
   at Microsoft.ML.Trainers.LightGbm.LightGbmRankingTrainer.CheckLabelCompatible(Column labelCol) in E:\A\_work\449\s\src\Microsoft.ML.LightGbm\LightGbmRankingTrainer.cs:line 246
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.CheckInputSchema(SchemaShape inputSchema)

Instead, the KeyType attribute should be respected when loading from a text file.

### Source code / logs
Run the attached code which uses the attached data.
[SampleKeyRepro.txt](https://github.com/dotnet/machinelearning/files/3249574/SampleKeyRepro.txt)

[MyTestData.txt](https://github.com/dotnet/machinelearning/files/3249578/MyTestData.txt)

**Comment by nicolehaugen79** [comment]
Closing since this is a duplicate of https://github.com/dotnet/machinelearning/issues/2642.
