### ISSUE TITLE
cannot use fasterrcnn onnx model in c# ap

### ISSUE THREAD

**Issue by i-newton** [dotnet/machinelearning#3932]
steps:
download https://github.com/onnx/models/tree/master/faster_rcnn
try to run model in .net
```
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.ML;
using AlexNet.DataStructures;
using Microsoft.ML.Transforms.Image;

namespace SomeNet
{
    public class ImageClassifier
    {
        private readonly string dataLocation;
        private readonly string labelsLocation;
        private readonly string imagesLocation;
        private readonly string modelLocation;
        private readonly MLContext mLContext;

        public ImageClassifier(string dataLocation, string imagesLocation, string labelsLocation, string modelLocation)
        {
            this.dataLocation = dataLocation;
            this.labelsLocation = labelsLocation;
            this.imagesLocation = imagesLocation;
            this.modelLocation = modelLocation;
            mLContext = new MLContext();
        }

        public struct ImageSettings
        {
            public const int imageHeight = 224;
            public const int imageWidth = 224;
        }

        public struct OnnxModelSettings
        {
            public const string ModelInput = "image";
        }

        public void Score()
        {
            var model = LoadModel(dataLocation, imagesLocation, modelLocation);

            var predictions = PredictData(dataLocation, imagesLocation, labelsLocation, model).ToArray(); 
        }

        private PredictionEngine<ImageData, ImagePrediction> LoadModel(string dataLocation, string imagesLocation, string modelLocation)
        {
            var data = mLContext.Data.LoadFromTextFile<ImageData>(dataLocation, hasHeader: false);

            var pipeline = mLContext.Transforms.LoadImages(outputColumnName: "loadedimage", imageFolder: imagesLocation, inputColumnName: nameof(ImageData.ImagePath))
                .Append(mLContext.Transforms.ResizeImages(outputColumnName: "resizedimage",inputColumnName:"loadedimage", imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight))
                .Append(mLContext.Transforms.ExtractPixels(outputColumnName: "image", inputColumnName:"resizedimage", orderOfExtraction: ImagePixelExtractingEstimator.ColorsOrder.ABGR))
                .Append(mLContext.Transforms.ApplyOnnxModel(modelFile: modelLocation, outputColumnNames: new[] { "6379", "6381", "6383" }, inputColumnNames: new[] { "image"}));
            var model = pipeline.Fit(data);

            var predictionEngine = mLContext.Model.CreatePredictionEngine<ImageData, ImagePrediction>(model, ignoreMissingColumns:false);

            return predictionEngine;
        }

        protected IEnumerable<ImageData> PredictData(string imageLocation, string imageFolder, string labelsLocation, PredictionEngine<ImageData, ImagePrediction> model)
        {
            var labels = labelsLocation;
            var p = model.Predict(new ImageData{
                ImagePath = "/home/snake/aspose/anton.perhunov/AlexNet/AlexNet/assets/Data/html.jpg"
            });
            var im =  new ImageData{
                ImagePath = imageFolder + "/e5725c32f8be4da8b6a27375fc7669ae_html.jpg"
            };
            yield return im;
        }
    }
}
```

when inference any image you will get
Unhandled Exception: System.ArgumentException: Length of memory (150528) must match product of dimensions (3).
at System.Numerics.Tensors.DenseTensor1..ctor(Memory1 memory, ReadOnlySpan1 dimensions, Boolean reverseStride) at Microsoft.ML.Transforms.Onnx.OnnxUtils.CreateNamedOnnxValue[T](String name, ReadOnlySpan1 data, List1 shape) at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.NamedOnnxValueGetterVec1.GetNamedOnnxValue()
at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.UpdateCacheIfNeeded(Int64 position, INamedOnnxValueGetter[] srcNamedOnnxValueGetters, String[] activeOutputColNames, OutputCache outputCache)
at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.<>c__DisplayClass13_01.<MakeGetter>b__0(VBuffer1& dst)
at Microsoft.ML.Data.TypedCursorable1.TypedRowBase.<>c__DisplayClass8_01.b__0(TRow row)
at Microsoft.ML.Data.TypedCursorable1.TypedRowBase.FillValues(TRow row) at Microsoft.ML.PredictionEngineBase2.Predict(TSrc example)

it seems that .net api does not support dynamic input sizes(-1 in dimension), it just treat them as 1, model supports inputs with (3, -1,-1), however onnx value size become (3,1,1).

**Comment by wschin** [comment]
There are two potential solutions. First, we could allow user to overwrite the shape loaded from the ONNX model. Second, we can also implicitly deduce that shape at runtime. Since the later is more user-friendly, I will try that first. Thanks a lot for your feedback!
