### ISSUE TITLE
Provided label column 'Status' was of type Single, but only type Boolean is allowed.

### ISSUE THREAD

**Issue by crperez5** [dotnet/machinelearning#4181]
Hi,

I'm using AutoML to auto-generate a model.

Input file looks like the following:
"V1","V2","V3","V4","Status"
-86,-66,-66,4,0
-84,-78,-61,65,0
...

Output:
For further learning check: https://aka.ms/mlnet-cli
|     Trainer                              Accuracy      AUC    AUPRC  F1-score  Duration #Iteration             |
[Source=AutoML, Kind=Trace] Channel started
Exception occured while exploring pipelines:
Provided label column 'Status' was of type Single, but only type Boolean is allowed.
System.ArgumentException: Provided label column 'Status' was of type Single, but only type Boolean is allowed.
   at Microsoft.ML.CLI.CodeGenerator.CodeGenerationHelper.GenerateCode()
   at Microsoft.ML.CLI.Program.<>c__DisplayClass1_0.<Main>b__0(NewCommandSettings options)
Please see the log file for more info.
Exiting ...

Is this a bug?

**Comment by crperez5** [comment]
Something was wrong with my input file.
