### ISSUE TITLE
InvalidOperationException: Invalid TValue in GetGetter: 'Microsoft.ML.Data.VBuffer`1[System.Single]'

### ISSUE THREAD

**Issue by gerjanvl** [dotnet/machinelearning#4201]
### System information

- Windows 10:
- netcoreapp 2.2
 
### Packages
Microsoft.ML 1.4.0-preview
Microsoft.ML.OnnxRuntime 0.5.0
Microsoft.ML.OnnxTransformer 1.4.0-preview

### Issue

- Used onnx model to create a prediction engine.
- I get an exception when creating the prediction engine: InvalidOperationException: Invalid TValue in GetGetter: 'Microsoft.ML.Data.VBuffer`1[System.Single]'
- I was expecting it to work everything looks right, the exception doesn't make it clear what's actually wrong. I could not debug the source code because it's inside a lambda function. 

### Source Code: 
https://github.com/GerjanVlot/BERT-ML.NET

### Callstack:
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.GenerateSetter(DataViewRow input, Int32 index, Column column, Delegate poke, Delegate peek)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase..ctor(TypedCursorable`1 parent, DataViewRow input, String channelMessage)
   at Microsoft.ML.Data.TypedCursorable`1.GetRow(DataViewRow input)
   at Microsoft.ML.PredictionEngineBase`2.PredictionEngineCore(IHostEnvironment env, InputRow`1 inputRow, IRowToRowMapper mapper, Boolean ignoreMissingColumns, SchemaDefinition outputSchemaDefinition, Action& disposer, IRowReadableAs`1& outputRow)
   at Microsoft.ML.PredictionEngineBase`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.PredictionEngineExtensions.CreatePredictionEngine[TSrc,TDst](ITransformer transformer, IHostEnvironment env, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at ML.BERT.TestApp.Onnx.OnnxModelConfigurator`1.GetMlNetPredictionEngine[T]() in ML.BERT.TestApp\Onnx\OnnxModelConfigurator.cs:line 34
   at ML.BERT.TestApp.Program.Main(String[] args) in ML.BERT.TestApp\Program.cs:line 22
```

**Comment by GerjanVlot** [comment]
I got it working, The order of the columns matters and the main problem was it couldn't handle a variable column so I removed the output.

If you want to know what I changed. 
https://github.com/GerjanVlot/BERT-ML.NET/commit/9ad4cde1e17fe3244c43f23923f230e469127d9a

**Comment by gerjanvl** [comment]
I got it working, The order of the columns matters and the main problem was it couldn't handle a variable column so I removed the output.

If you want to know what I changed. 
https://github.com/GerjanVlot/BERT-ML.NET/commit/9ad4cde1e17fe3244c43f23923f230e469127d9a

**Comment by gerjanvl** [comment]
I got it working, The order of the columns matters and the main problem was it couldn't handle a variable column so I removed the output.

If you want to know what I changed. 
https://github.com/GerjanVlot/BERT-ML.NET/commit/9ad4cde1e17fe3244c43f23923f230e469127d9a
