### ISSUE TITLE
Exception in AutoML regression experiment

### ISSUE THREAD

**Issue by bjoped** [dotnet/machinelearning#4241]
Windows 10 v. 1809

Upgraded From v.0.14 v. 0.15 and got ArgumentOutOfRangeException in CrossValSummaryRunner.suggestedPipelineRunDetail.
BestResultUtil.GetIndexOfBestScore returns -1. 

Code works as expected in v.0.14. tried to upgrade to v.0.15 and v0.16 preview and both fail with the Exception.

> System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.ML.AutoML.CrossValSummaryRunner`1.Run(SuggestedPipeline pipeline, DirectoryInfo modelDirectory, Int32 iterationNum) in C:\Data\Dev\machinelearning\src\Microsoft.ML.AutoML\Experiment\Runners\CrossValSummaryRunner.cs:line 74

**Comment by eerhardt** [comment]
@bjoped - can you provide the code you used to produce this exception?

**Comment by frank-dong-ms** [comment]
@bjoped could you please try out latest version of ML.NET see if still can reproduce the issue?
Close this issue as we haven't hear back for a long time, feel free to reopen if you can provide more info for us to investigate, thanks.

**Comment by AnQueth** [comment]
this is happening to me when using the model builder in either recommender or predictor.

this is the dataset
User,Make,Model,Year,Rating
1,"Ford",F150,2018,1.0
1,"Mazda",Something,2017,0.0
1,"Ford",F250,2016,1.0
1,"Nissan",Pickup,2018,1.0
1,"Toyota",Camry,2018,0.0
1,"Ford",F150,2019,1.0
