### ISSUE TITLE
[AutoML] Recommendation experiment got SMAC local search exception during training

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#4354]
Hey folks

I just try the Recommendation experiment API in the master branch. After I training for a period of time (like 300 sec), I got this error.

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: SMAC sweeper localSearch threw exception ---> System.MethodAccessException: Attempt by method 'Microsoft.ML.AutoML.SmacSweeper.ComputeForestStats(Double[][])' to access method 'Microsoft.ML.Trainers.FastTree.VectorUtils.GetMean(Double[])' failed.
   at Microsoft.ML.AutoML.SmacSweeper.ComputeForestStats(Double[][] leafValues)
   at Microsoft.ML.AutoML.SmacSweeper.LocalSearch(ParameterSet parent, FastForestRegressionModelParameters forest, Double bestVal, Double epsilon, Boolean isMetricMaximizing)
   --- End of inner exception stack trace ---
   at Microsoft.ML.AutoML.SmacSweeper.LocalSearch(ParameterSet parent, FastForestRegressionModelParameters forest, Double bestVal, Double epsilon, Boolean isMetricMaximizing)
   at Microsoft.ML.AutoML.SmacSweeper.GreedyPlusRandomSearch(ParameterSet[] parents, FastForestRegressionModelParameters forest, Int32 numOfCandidates, IEnumerable`1 previousRuns)
   at Microsoft.ML.AutoML.SmacSweeper.GenerateCandidateConfigurations(Int32 numOfCandidates, IEnumerable`1 previousRuns, FastForestRegressionModelParameters forest)
   at Microsoft.ML.AutoML.PipelineSuggester.SampleHyperparameters(MLContext context, SuggestedTrainer trainer, IEnumerable`1 history, Boolean isMaximizingMetric)
   at Microsoft.ML.AutoML.PipelineSuggester.GetNextInferredPipeline(MLContext context, IEnumerable`1 history, DatasetColumnInfo[] columns, TaskKind task, Boolean isMaximizingMetric, CacheBeforeTrainer cacheBeforeTrainer, IEnumerable`1 trainerWhitelist)
   at Microsoft.ML.AutoML.Experiment`2.Execute()
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(ColumnInformation columnInfo, DatasetColumnInfo[] columns, IEstimator`1 preFeaturizer, IProgress`1 progressHandler, IRunner`1 runner)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<>c__DisplayClass23_0`4.<InnerTrainModelAsync>b__4() in C:\Users\xiaoyuz\Source\Repos\machinelearning-tools\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 277
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<InnerTrainModelAsync>d__23`4.MoveNext() in C:\Users\xiaoyuz\Source\Repos\machinelearning-tools\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__9.MoveNext() in C:\Users\xiaoyuz\Source\Repos\machinelearning-tools\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 107
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\xiaoyuz\Source\Repos\machinelearning-tools\Microsoft.ML.ModelBuilder.AutoMLService\Program.cs:line 36
```

the dataset I use is this [one](https://raw.githubusercontent.com/dotnet/machinelearning-samples/master/samples/csharp/getting-started/MatrixFactorization_MovieRecommendation/Data/recommendation-ratings-train.csv)

I guess it's because of value error (like nan). But I'm not too sure about that, Please take a look, any suggestion will be helpful. Thanks

## A minimal reproducable example [here](https://github.com/LittleLittleCloud/ReproducableExampleForIssue4354)

**Comment by eerhardt** [comment]
@maryamariyan - can you take a look?

/cc @Dmitry-A @daholste @justinormont

**Comment by LittleLittleCloud** [comment]
Some clues:
the example works well, but when I call the API in model builder, the error raised

**Comment by eerhardt** [comment]
@maryamariyan - actually nevermind. I'm looking into it now.

**Comment by eerhardt** [comment]
The issue appears to be that the AutoML nuget package is getting the wrong version in its dependencies to LightGbm and FastTree:

```xml
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Microsoft.ML.LightGBM" version="0.16.0-preview3-28220-3" exclude="Build,Analyzers" />
```

The reason appears to be because the case is incorrect in the ProjectReference:

https://github.com/dotnet/machinelearning/blob/4ee7cbb2e31a90da9d641ba2a0ed720496fd0b4d/pkg/Microsoft.ML.AutoML/Microsoft.ML.AutoML.nupkgproj#L10

It should have `Gbm` instead of `GBM`.
