### ISSUE TITLE
ApplyOnnxModel Transform does not find method after upgrading to ONNXRuntime 1.0.0

### ISSUE THREAD

**Issue by edirgarcia** [dotnet/machinelearning#4461]
System information:
- .NET Version
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Issue:
ApplyOnnxModel Transform in 1.4.0 does not find a method after updating OnnxRuntime to 1.0.0

It throws:
Method not found: 'Microsoft.ML.OnnxRuntime.SessionOptions Microsoft.ML.OnnxRuntime.SessionOptions.MakeSessionOptionWithCudaProvider(Int32)'.

Looking at the library on iLSpy it seems that method is actually gone, but ML.NET still asumes is there. It does work when using OnnxRuntime 0.5.1

Stack Trace:
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes) 220
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary)
   at Microsoft.ML.OnnxCatalog.ApplyOnnxModel(TransformsCatalog catalog, String outputColumnName, String inputColumnName, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)
   at ***.***.***.TestModelTrainer.Load_Keras_Onnx_Mnist(String modelPath) in D:\Source\***\MyProjectPath\***\TestModelTrainer.cs:line 756
   at Microsoft.PS.Prediction.UnitTests.ML.NET.Tests.MLNetTests.Load_Test_Keras_Onnx_Mnist() in D:\Source\***\MyProjectPath\***\ML.NET.Tests.cs:line 165

**Comment by edirgarcia** [comment]
It seems that this is a non issue.
ML.NET 1.4.0 ships with OnnxRuntime 0.5.1, and is not expected to work with version 1.0.0.
