### ISSUE TITLE
I am able to dynamically train and create my regression model just fine from a string[] of column names. However, when I try to pass in a dynamic object with the same Parameter names as Dictionary Key Pair properties it throw the error:  System.ArgumentOutOfRangeException: 'Could not find input column '<MyColumn>'' Where <MyColumn> is the first parameter that the model is looking for.

### ISSUE THREAD

**Issue by jigarhshah17** [dotnet/machinelearning#4574]
### System information

- **OS version/distro**:
windows 7
- **.NET Version (eg., dotnet --info)**: 
4.6.1

### Issue

- **What did you do?**
I am able to dynamically train and create my regression model just fine from a string[] of column names. However, when I try to pass in a dynamic object with the same Parameter names as for create CreatePredictionEngine
- **What happened?**
It throw the error:

System.ArgumentOutOfRangeException: 'Could not find input column '<MyColumn>

System.ArgumentOutOfRangeException: Could not find input column 'Pressure'
Parameter name: inputSchema
   at Microsoft.ML.Data.OneToOneTransformerBase.CheckInput(DataViewSchema inputSchema, Int32 col, Int32& srcCol)
   at Microsoft.ML.Data.OneToOneTransformerBase.OneToOneMapperBase..ctor(IHost host, OneToOneTransformerBase parent, DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.ColumnCopyingTransformer.Mapper..ctor(ColumnCopyingTransformer parent, DataViewSchema inputSchema, ValueTuple`2[] columns)
   at Microsoft.ML.Transforms.ColumnCopyingTransformer.MakeRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.RowToRowTransformerBase.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.PredictionEngineBase`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.PredictionEngineExtensions.CreatePredictionEngine[TSrc,TDst](ITransformer transformer, IHostEnvironment env, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)

- **What did you expect?**
MLContextRef.Model.CreatePredictionEngine use dynamic created class or any other way i want to achive requirement.

### Source code / logs

predictionEngine = MLContextRef.Model.CreatePredictionEngine(dynamic created class obj, result)(loadedModel)
Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by yaeldekel** [comment]
Hi @jigarhshah17 ,
Could you elaborate about how you dynamically create the class for the model inputs? In order for the model to work, either the fields/properties of the class need to have the same names as the columns that the input data view had when `Fit()` was called, or they need to have the [`ColumnNameAttribute`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.Data/Data/SchemaDefinition.cs#L102).

**Comment by najeeb-kazmi** [comment]
@jigarhshah17 I believe this has been answered. If not, please feel free to reopen.
