### ISSUE TITLE
how to build DataViewSchema with Annotations?

### ISSUE THREAD

**Issue by jigarhshah17** [dotnet/machinelearning#4575]
### System information

- **OS version/distro**:
windows 7
- **.NET Version (eg., dotnet --info)**: 
4.6.1
### Issue
how to build DataViewSchema with Annotations?
- **What did you do?**
how to build DataViewSchema with Annotations?
- **What happened?**
- **What did you expect?**

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by yaeldekel** [comment]
Hi @jigarhshah17 ,
To build a `DataViewSchema` you can use the [`DataViewSchema.Builder`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.DataView/DataViewSchema.cs#L378) class. If you want to have annotations on the columns, you can use this method:
```
public void AddColumn(string name, DataViewType type, Annotations annotations = null)
```
The `Annotations` object has its own builder, [`DataViewSchema.Annotations.Builder`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.DataView/DataViewSchema.cs#L256)

**Comment by jigarhshah17** [comment]
I have made a DLL for prediction and DLL having function like 
Public Overridable Function PredictValue(Of TRow As Class, TDst As {Class, New})(inputdata As TRow, modelPathWithName As String,<Out> ByRef finalResult As TDst) As OperationError 

Dim loadedModel As ITransformer = Nothing
			Dim predictionEngine As PredictionEngine(Of TRow, TDst) = Nothing
			Dim dvSchemas As DataViewSchema = Nothing
			Try
				If ModelOperation.LoadModel(modelPathWithName, loadedModel, dvSchemas) <> OperationError.None Then
					Return OperationError.Fail
				End If

				If loadedModel Is Nothing Then
					Return OperationError.Fail
				End If
predictionEngine = MLContextRef.Model.CreatePredictionEngine(Of TRow, TDst)(loadedModel)
				finalResult = predictionEngine.Predict(inputdata)

				If finalResult Is Nothing Then
					Return OperationError.Fail
				End If

End Function

I have made two model for predict pressure and temperature.
Now I have made one client application for predict Pressure and temperature using above created model with help of above function

Now i created one pressure class and one temperature class
Like 
Dim pressureDataset As PressureData
pressureDataset = New PressureData With {.PressureOnPumpDischarge = 4.525,								.TankLevel = 6210,										.NoOfUnderLoadingTruck = 4}
same for temperature

now call above function

PredictValue(pressureDataset,Path.Combine(Environment.CurrentDirectory, "Model", _modelName & zip), out) 

It will give answer

Now I have made pressuredata class runtime and assign value and pass object like

PredictValue(objpressuredata,Path.Combine(Environment.CurrentDirectory, "Model", _modelName & zip), out) 

It will give error 

System.ArgumentOutOfRangeException: Could not find input column 'Pressure'
Parameter name: inputSchema
   at Microsoft.ML.Data.OneToOneTransformerBase.CheckInput(DataViewSchema inputSchema, Int32 col, Int32& srcCol)
   at Microsoft.ML.Data.OneToOneTransformerBase.OneToOneMapperBase..ctor(IHost host, OneToOneTransformerBase parent, DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.ColumnCopyingTransformer.Mapper..ctor(ColumnCopyingTransformer parent, DataViewSchema inputSchema, ValueTuple`2[] columns)
   at Microsoft.ML.Transforms.ColumnCopyingTransformer.MakeRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.RowToRowTransformerBase.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.PredictionEngineBase`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.PredictionEngineExtensions.CreatePredictionEngine[TSrc,TDst](ITransformer transformer, IHostEnvironment env, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at PredictValue[TRow,TDst](TRow inputdata, String modelPathWithName, TDst& finalResult) 1

so please help me

**Comment by jigarhshah17** [comment]
> Hi @jigarhshah17 ,
> To build a `DataViewSchema` you can use the [`DataViewSchema.Builder`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.DataView/DataViewSchema.cs#L378) class. If you want to have annotations on the columns, you can use this method:
> 
> ```
> public void AddColumn(string name, DataViewType type, Annotations annotations = null)
> ```
> 
> The `Annotations` object has its own builder, [`DataViewSchema.Annotations.Builder`](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.DataView/DataViewSchema.cs#L256)

I have made a DLL for prediction and DLL having function like 
Public Overridable Function PredictValue(Of TRow As Class, TDst As {Class, New})(inputdata As TRow, modelPathWithName As String,<Out> ByRef finalResult As TDst) As OperationError 

Dim loadedModel As ITransformer = Nothing
			Dim predictionEngine As PredictionEngine(Of TRow, TDst) = Nothing
			Dim dvSchemas As DataViewSchema = Nothing
			Try
				If ModelOperation.LoadModel(modelPathWithName, loadedModel, dvSchemas) <> OperationError.None Then
					Return OperationError.Fail
				End If

				If loadedModel Is Nothing Then
					Return OperationError.Fail
				End If
predictionEngine = MLContextRef.Model.CreatePredictionEngine(Of TRow, TDst)(loadedModel)
				finalResult = predictionEngine.Predict(inputdata)

				If finalResult Is Nothing Then
					Return OperationError.Fail
				End If

End Function

I have made two model for predict pressure and temperature.
Now I have made one client application for predict Pressure and temperature using above created model with help of above function

Now i created one pressure class and one temperature class
Like 
Dim pressureDataset As PressureData
pressureDataset = New PressureData With {.PressureOnPumpDischarge = 4.525,								.TankLevel = 6210,										.NoOfUnderLoadingTruck = 4}
same for temperature

now call above function

PredictValue(pressureDataset,Path.Combine(Environment.CurrentDirectory, "Model", _modelName & zip), out) 

It will give answer

Now I have made pressuredata class runtime and assign value and pass object like

PredictValue(objpressuredata,Path.Combine(Environment.CurrentDirectory, "Model", _modelName & zip), out) 

It will give error 

System.ArgumentOutOfRangeException: Could not find input column 'Pressure'
Parameter name: inputSchema
   at Microsoft.ML.Data.OneToOneTransformerBase.CheckInput(DataViewSchema inputSchema, Int32 col, Int32& srcCol)
   at Microsoft.ML.Data.OneToOneTransformerBase.OneToOneMapperBase..ctor(IHost host, OneToOneTransformerBase parent, DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.ColumnCopyingTransformer.Mapper..ctor(ColumnCopyingTransformer parent, DataViewSchema inputSchema, ValueTuple`2[] columns)
   at Microsoft.ML.Transforms.ColumnCopyingTransformer.MakeRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.RowToRowTransformerBase.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TransformerChain`1.Microsoft.ML.ITransformer.GetRowToRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.PredictionEngineBase`2..ctor(IHostEnvironment env, ITransformer transformer, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at Microsoft.ML.PredictionEngineExtensions.CreatePredictionEngine[TSrc,TDst](ITransformer transformer, IHostEnvironment env, Boolean ignoreMissingColumns, SchemaDefinition inputSchemaDefinition, SchemaDefinition outputSchemaDefinition)
   at PredictValue[TRow,TDst](TRow inputdata, String modelPathWithName, TDst& finalResult) 1

so please help me

**Comment by frank-dong-ms** [comment]
@jigarhshah17 Thanks for using ML.NET. Could you please provide complete repro project with the ArgumentOutOfRangeException issue? Also, what language are you using (looks like VB but I'm not sure yet)?

**Comment by frank-dong-ms** [comment]
Close this issue for now as not hearing back with required info to repro and investigate this issue. Feel free to reopen the issue if necessary, thanks.
