### ISSUE TITLE
LightGbm in Linux Container

### ISSUE THREAD

**Issue by mayoatte** [dotnet/machinelearning#4600]
### System information

- **Ubuntu*:
- **.NET Core 3.0**: 

### Issue

- **What did you do?**
Deployed a .Net Core 3.0 ML.NET app to Azure Container Instances (Linux Container). This same training app was working with other trainers but fails with the LightGbmRanking trainer.

- **What happened?**

Received the error below.

- **What did you expect?**

I expected training to complete.

### Source code / logs

`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'lib_lightgbm' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblib_lightgbm: cannot open shared object file: No such file or directory
   at Microsoft.ML.Trainers.LightGbm.WrappedLightGbmInterface.DatasetCreateFromSampledColumn(IntPtr sampleValuePerColumn, IntPtr sampleIndicesPerColumn, Int32 numCol, Int32[] sampleNonZeroCntPerColumn, Int32 numSampleRow, Int32 numTotalRow, String parameters, IntPtr& ret)
   at Microsoft.ML.Trainers.LightGbm.Dataset..ctor(Double[][] sampleValuePerColumn, Int32[][] sampleIndicesPerColumn, Int32 numCol, Int32[] sampleNonZeroCntPerColumn, Int32 numSampleRow, Int32 numTotalRow, String param, Single[] labels, Single[] weights, Int32[] groups)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.CreateDatasetFromSamplingData(IChannel ch, Factory factory, Int32 numRow, String param, Single[] labels, Single[] weights, Int32[] groups, CategoricalMetaData catMetaData, Dataset& dataset)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.LoadTrainingData(IChannel ch, RoleMappedData trainData, CategoricalMetaData& catMetaData)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)`

- **What have you tried?**

Installing libomp in the docker build as mentioned [here](https://github.com/dotnet/machinelearning/issues/1282)

**Comment by mayoatte** [comment]
I was able to get this work by installing some of the same packages that are required for building ML.NET itself on Linux.

`RUN apt-get install git clang-3.9 cmake libunwind8 curl -y
RUN apt-get install -y libomp-dev
RUN ldconfig`

The documentation could  be a lot better in this area.

**Comment by ArrowRaider** [comment]
How did you find these dependencies?

**Comment by mayoatte** [comment]
@ArrowRaider I believe it was from [this page](https://github.com/dotnet/machinelearning/blob/master/docs/building/unix-instructions.md)
