### ISSUE TITLE
Could not find label column 'Label'

### ISSUE THREAD

**Issue by h0s** [dotnet/machinelearning#4618]
### System information

- Microsoft.ML 1.4.0
- dotnet Core 2.1

### Issue

- **What did you do?**
I'am running  a test for the full data set
```
            var pipeline = context.Transforms.CustomMapping<FromLabel, ToLabel>(
    mapAction: (input, output) => { output.SentimentLabel = input.Sentiment == 0? "Bad Review 😡" : "Good Review  😍"; },
    contractName: "MyLambda")
     .Append(context.Transforms.Text.FeaturizeText(
        outputColumnName: "Features",
        inputColumnName: nameof(DataInputModel.SentimentText)))
    .Append(context.BinaryClassification.Trainers.SdcaLogisticRegression());

            Console.WriteLine("Performing cross validation...");
       var res=     data.Preview();
            var cvResults = context.BinaryClassification.CrossValidate(
                partitions.TrainSet,
               pipeline,5);
```

- **What happened?**
An exceptions is thrown "Could not find label column 'Label'"
- **What did you expect?**
get result of the test or a clean error message 
### Source code / logs
Data CSV Source example >
```
SentimentText	Sentiment
"first think another Disney movie, might good, it's kids movie. watch it, can't help enjoy it. ages love movie. first saw movie 10 8 years later still love it! Danny Glover superb could play part better. Christopher Lloyd hilarious perfect part. Tony Danza believable Mel Clark. can't help, enjoy movie! give 10/10!"	 1
"Put aside Dr. House repeat missed, Desperate Housewives (new) watch one. don't know exactly plagued movie. never thought I'd say this, want 15 minutes fame back.<br /><br />Script, Direction, can't say. recognized stable actors (the usual suspects), thought Herbert Marshall class addition sat good cheesy flick. Boy, wrong. Dullsville.<br /><br />My favorite parts: ""office girl"" makes 029 keypunch puts cards 087 sorter. LOL @ ""the computer"". I'd like someone identify next device - 477 ? It's even dinosaur's time.<br /><br />And dinosaurs don't much time waste."	 0
"big fan Stephen King's work, film made even greater fan King. Pet Sematary Creed family. moved new house, seem happy. pet cemetery behind house. Creed's new neighbor Jud (played Fred Gwyne) explains burial ground behind pet cemetery. burial ground pure evil. Jud tells Louis Creed bury human (or kind pet) burial ground, would come back life. problem, come back, person, they're evil. Soon Jud explains everything Pet Sematary, everything starts go hell. wont explain anymore don't want give away main parts film. acting Pet Sematary pretty good, needed little bit work. story one main parts movie, mainly original gripping. film features lots make-up effects make movie way eerie, frightening. One basic reasons movie sent chills back, fact make-up effects. one character film truly freaky. character ""Zelda."" particular character pops film three times precise. Zelda Rachel Creed's sister passed away years before, Rachel still haunted her. first time Zelda appears movie isn't generally scary isn't talking anything, second time worst, honest, second time scares living **** me. absolutely nothing wrong movie, almost perfect. Pet Sematary delivers great scares, pretty good acting, first rate plot, mesmerizing make-up. truly one favorite horror films time. 10 10."	 1
"watched horrid thing TV. Needless say one movies watch see much worse get. Frankly, don't know much lower bar go. <br /><br />The characters composed one lame stereo-type another, obvious attempt creating another ""Bad News Bears"" embarrassing say least.<br /><br />I seen prized turkeys time, reason list since ""Numero Uno"".<br /><br />Let put way, watched Vanilla Ice movie, bad funny. This...this...is even good."	 0
```
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Could not find label column 'Label'
Arg_ParamName_Name
  Source=Microsoft.ML.Data
  StackTrace:
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.CheckInputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.GetOutputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Data.EstimatorChain`1.GetOutputSchema(SchemaShape inputSchema)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.TrainCatalogBase.CrossValidateTrain(IDataView data, IEstimator`1 estimator, Int32 numFolds, String samplingKeyColumn, Nullable`1 seed)
   at Microsoft.ML.BinaryClassificationCatalog.CrossValidate(IDataView data, IEstimator`1 estimator, Int32 numberOfFolds, String labelColumnName, String samplingKeyColumnName, Nullable`1 seed)
   at SentimentAnalyzer.Program.Main(String[] args) in \Program.cs:line 34
```

**Comment by yaeldekel** [comment]
Hi @h0s , thank you for your question.
From your code it looks like the name of the label column in your pipeline is `SentimentLabel`. There are two options to let the SDCA trainer know which column is the label column:
- Rename the `SentimentLabel` field in the `ToLabel` class `Label`. This is the default label column name that trainers try to find if they are not explicitly given a label column name.
- Add the `labelColumnName` parameter when you construct the SDCA trainer: `context.BinaryClassification.Trainers.SdcaLogisticRegression(labelColumnName: "SentimentLabel")`.

There is also a third option, which is to pass a `SchemaDefinition` object when constructing the `CustomMappingEstimator`. This object contains a mapping from the field names in the output class to column names in the output data view. The first two options I mentioned are simpler to use so I am not going into detail about this option, but let me know if you do need to use it and I can help with constructing the `SchemaDefinition` object.

**Comment by h0s** [comment]
@yaeldekel thank you a lot ! i close it , it's not a bug but it will be better if we have a clear exception description.,
thanks
