### ISSUE TITLE
EntryPointChainedCrossValMacros test fails in CI occasionally

### ISSUE THREAD

**Issue by eerhardt** [dotnet/machinelearning#49]
### System information

- **OS version/distro**:  Linux Debug
- **.NET Version (eg., dotnet --info)**:   .NET Core

### Issue

- **What did you do?**
Submitted a PR that only changed a markdown file:  https://github.com/dotnet/machinelearning/pull/48
- **What happened?**
The Linux Debug leg failed.  See https://ci2.dot.net/job/dotnet_machinelearning/job/master/job/linux_debug_prtest/1/

- **What did you expect?**
I expected all the tests to pass on all legs since I didn't change any code.

### Source code / logs

```
MESSAGE:
                                        Assert failed: longIdx=328, invariants.Length=328
Expected: True
Actual:   False
                                        +++++++++++++++++++
                                        STACK TRACE:
                                           at Microsoft.ML.Runtime.Internal.Internallearn.Test.GlobalBase.AssertHandler(String msg, IExceptionContext ectx) in /mnt/resource/j/w/dotnet_machinelearning/master/linux_debug_prtest/test/Microsoft.ML.TestFramework/GlobalBase.cs:line 47
   at Microsoft.ML.Runtime.Contracts.DbgFailCore(String msg, IExceptionContext ctx) in /mnt/resource/j/w/dotnet_machinelearning/master/linux_debug_prtest/src/Microsoft.ML.Core/Utilities/Contracts.cs:line 751
   at Microsoft.ML.Runtime.Contracts.DbgFail(String msg) in /mnt/resource/j/w/dotnet_machinelearning/master/linux_debug_prtest/src/Microsoft.ML.Core/Utilities/Contracts.cs:line 764
   at Microsoft.ML.Runtime.Contracts.Assert(Boolean f, String msg) in /mnt/resource/j/w/dotnet_machinelearning/master/linux_debug_prtest/src/Microsoft.ML.Core/Utilities/Contracts.cs:line 822
   at Microsoft.ML.Runtime.Learners.SdcaTrainerBase`1.TrainCore(IChannel ch, RoleMappedData data, LinearPredictor predictor) in /mnt/resource/j/w/dotnet_machinelearning/master/linux_debug_prtest/src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs:line 520
   at Microsoft.ML.Runtime.Learners.LinearTrainerBase`1.TrainEx(RoleMappedData data, LinearPredictor predictor) in /mnt/resource/j/w/dotnet_machinelearning/master/linux_debug_prtest/src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs:line 76
   at Microsoft.ML.Runtime.Learners.LinearTrainerBase`1.Train(RoleMappedData examples) in /mnt/resource/j/w/dotnet_machinelearning/master/linux_debug_prtest/src/Microsoft.ML.StandardLearners/Standard/LinearClassificationTrainer.cs:line 84
   at Microsoft.ML.Runtime.Data.TrainUtils.TrainCore[TDataSet,TPredictor](IChannel ch, ITrainer trainer, Action`1 train, TDataSet data, TDataSet validData, TPredictor predictor) in /mnt/resource/j/w/dotnet_machinelearning/master/linux_debug_prtest/src/Microsoft.ML.Data/Commands/TrainCommand.cs:line 324
```

**Comment by abgoswam** [comment]
DRI RESPONSE: This is still partially still the case. SDCA do fail sometimes and we track it in https://github.com/dotnet/machinelearning/issues/1131, this one haven't happened for awhile.

**Comment by frank-dong-ms** [comment]
Also the race condition issue fixed in: https://github.com/dotnet/machinelearning/pull/4829
