### ISSUE TITLE
Training ImageClassification in parallel throws when trying to use the same WorkspacePath

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning#5112]
Using ImageClassification (ImageClassificationTrainer) on the machine as a job.
The job is implemented as a Azure Function, which is triggered by message in the storage queue. Every time the job receive a message the training process is calculated. The training runs for different data sets. That means, the function can observe multiple requests 

Unfortunately, when two training are running simultaneously on the same machine, we get following error:
```

2020-05-10T13:27:27  PID[11748] Information  ---> System.IO.IOException: Could not open file 'C:\DWASFiles\Sites\#1prodidentweb-training-webjob\LocalAppData\cache\bottleneck_train_cache.cac'. Error is: The process cannot access the file 'C:\DWASFiles\Sites\#1prodidentweb-training-webjob\LocalAppData\cache\bottleneck_train_cache.cac' because it is being used by another process.
2020-05-10T13:27:27  PID[11748] Information  ---> System.IO.IOException: The process cannot access the file '***\LocalAppData\cache\bottleneck_train_cache.cac' because it is being used by another process.
2020-05-10T13:27:27  PID[11748] Information    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
2020-05-10T13:27:27  PID[11748] Information    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
2020-05-10T13:27:27  PID[11748] Information    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
2020-05-10T13:27:27  PID[11748] Information    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
2020-05-10T13:27:27  PID[11748] Information    at Microsoft.ML.Internal.Utilities.StreamUtils.OpenInStream(String fileName)
2020-05-10T13:27:27  PID[11748] Information    at Microsoft.ML.Data.MultiFileSource.Open(Int32 index)
2020-05-10T13:27:27  PID[11748] Information    --- End of inner exception stack trace ---
```

By following the error shown above, it looks as trainer uses internal a local file(s), which should not be touched by multiple threads.
I guess, this can be solved by providing a different 'WorkspacePath' for every request? In any case, such internal details, should be transparent for developers. Moreover, ML algorithms, at least in the .NET ecosystem should not internal create any kind of singleton inside of process and also machine.
This is very untypical for .NET. 

In my opinion this is a not best design and it should should be fixed.

**Comment by antoniovs1029** [comment]
Hi, @ddobric . Thanks for reporting this.

So I wonder if you've tried this:

> I guess, this can be solved by providing a different 'WorkspacePath' for every request? 
Did this work? It looks to me this should be sufficient to solve your problem. Trying to leave `WorkspacePath` as null might also be another recommendation, since it looks to me it will actually create a new temporary directory every time a trainer is created:

https://github.com/dotnet/machinelearning/blob/6c3076348be4db5d714a9cb0fe2005d0f9343616/src/Microsoft.ML.Vision/ImageClassificationTrainer.cs#L536

About this:
> In any case, such internal details, should be transparent for developers. Moreover, ML algorithms, at least in the .NET ecosystem should not internal create any kind of singleton inside of process and also machine. This is very untypical for .NET. In my opinion this is a not best design and it should should be fixed.
I am afraid I am not following. Why should this be the case? If training an `ImageClassificationTrainer` requires creating a set of files on a given directory (which are specific of that specific trainer), then multiple trainers shouldn't share the same files, and each one of them should have their own directories. Since we already provide the API for the user to determine a different WorkspacePath for each trainer, then that should be enough to cover this use case.

So I am not sure if I am missing something in your suggestion, and I would appreciate your feedback on this regard if there's something I am not seeing. Thanks. 😄

**Comment by frank-dong-ms** [comment]
This is by design behavior and Antonio has already give suggestions on this issue, close for now.
@ddobric feel free to reopen this issue if necessary, thanks.
