### ISSUE TITLE
DateTimeTransformer cant find its own json data 

### ISSUE THREAD

**Issue by ganik** [dotnet/machinelearning#5220]
ML.NET 1.5.0
ML.Featurizers 0.17.0
Featurizers 0.4.1

Run NimbusML test_datetimesplitter.py method test_holidays. You get Exception:

RuntimeError: Error: *** System.Exception: ''Canada' is not a supported country name'
StackTrace:    at Microsoft.ML.Featurizers.DateTimeTransformer.TypedColumn.CreateTransformerFromEstimatorBase(HolidayList country)
at Microsoft.ML.Featurizers.DateTimeTransformer..ctor(IHostEnvironment host, String inputColumnName, String columnPrefix, HolidayList country, DataViewSchema schema)
at Microsoft.ML.Featurizers.DateTimeEstimator.Fit(IDataView input)
at Microsoft.ML.Featurizers.DateTimeTransformerEntrypoint.DateTimeSplit(IHostEnvironment env, Options input)

This is regression from ML.NET 1.5.0.preview2.

**Comment by michaelgsharp** [comment]
Not sure why this came in again, but I am creating a PR to fix it right now.
