### ISSUE TITLE
System.ArgumentException: Destination is too short. (Parameter 'destination')

### ISSUE THREAD

**Issue by Babadinier** [dotnet/machinelearning#5321]
### System information

.NET Core SDK (reflecting any global.json):
Version: 3.1.301
Commit: 7feb845744

 

Runtime Environment:

OS Name: Windows

OS Version: 10.0.14393

OS Platform: Windows

RID: win10-x86

Base Path: D:\Program Files (x86)\dotnet\sdk\3.1.301\

 

Host (useful for support):

Version: 3.1.5

Commit: 65cd789777

 

.NET Core SDKs installed:

1.1.14 [D:\Program Files (x86)\dotnet\sdk]

2.1.514 [D:\Program Files (x86)\dotnet\sdk]

2.1.515 [D:\Program Files (x86)\dotnet\sdk]

2.2.109 [D:\Program Files (x86)\dotnet\sdk]

3.1.202 [D:\Program Files (x86)\dotnet\sdk]

3.1.301 [D:\Program Files (x86)\dotnet\sdk]

 

.NET Core runtimes installed:

Microsoft.AspNetCore.All 2.1.17 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]

Microsoft.AspNetCore.All 2.1.19 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]

Microsoft.AspNetCore.All 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]

Microsoft.AspNetCore.App 2.1.17 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

Microsoft.AspNetCore.App 2.1.19 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

Microsoft.AspNetCore.App 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

Microsoft.AspNetCore.App 3.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

Microsoft.AspNetCore.App 3.1.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

Microsoft.AspNetCore.App 3.1.5 [D:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]

Microsoft.NETCore.App 1.0.16 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Microsoft.NETCore.App 1.1.13 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Microsoft.NETCore.App 2.0.9 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Microsoft.NETCore.App 2.1.19 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Microsoft.NETCore.App 2.2.8 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Microsoft.NETCore.App 3.0.3 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Microsoft.NETCore.App 3.1.5 [D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

### Issue

- We have implemented a service using ML.Net to analyze email messages.  In certain cases, when sending a request to analyze we get the following error, which results in a 400 status reply from our service.  When trying the same payload a couple of minutes later we get a correct 200 reply without error.
We would expect that ML always returns the same result when provided with the same payload?

System.ArgumentException: Destination is too short. (Parameter 'destination')
   at Microsoft.ML.Data.BufferBuilder`1.GetResult(VBuffer`1& buffer)
   at Microsoft.ML.Transforms.Text.NgramExtractingTransformer.Mapper.<>c__DisplayClass10_0.<MakeGetter>b__2(VBuffer`1& dst)
   at Microsoft.ML.Transforms.LpNormNormalizingTransformer.Mapper.<>c__DisplayClass8_0.<MakeGetter>b__5(VBuffer`1& dst)
   at Microsoft.ML.Data.ColumnConcatenatingTransformer.Mapper.BoundColumn.<>c__DisplayClass18_0`1.<MakeGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.ColumnConcatenatingTransformer.Mapper.BoundColumn.<>c__DisplayClass18_0`1.<MakeGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.SchemaBindablePredictorWrapperBase.<>c__DisplayClass18_0`2.<GetValueGetter>b__0(TDst& dst)
   at Microsoft.ML.Data.PredictedLabelScorerBase.EnsureCachedPosition[TScore](Int64& cachedPosition, TScore& score, DataViewRow boundRow, ValueGetter`1 scoreGetter)
   at Microsoft.ML.Data.MulticlassClassificationScorer.<>c__DisplayClass16_0.<GetPredictedLabelGetter>b__0(UInt32& dst)
   at Microsoft.ML.Transforms.KeyToValueMappingTransformer.Mapper.KeyToValueMap`2.<>c__DisplayClass8_0.<GetMappingGetter>b__0(TValue& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass9_0`2.<CreateConvertingActionSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
   at Microsoft.ML.PredictionEngine`2.Predict(TSrc example, TDst& prediction)
   at sar.svc.ml.alex.business.services.MailPredictionService.GetIntents(Mail mail) in D:\a\1\s\sar.svc.ml.alex.business\services\MailPredictionService.cs:line 26

```csharp      
public Dictionary<string, float> GetIntents(Mail mail)
        {
            if (mail == null)
            {
                throw new ArgumentNullException(nameof(mail));
            }

            var prediction = predictionEngine.Engine.Predict(mail);

            return BuildIntents(predictionEngine.Engine.OutputSchema, prediction.Score);
        }
```

**Comment by mstfbl** [comment]
Hi @Babadinier,

Thank you for sharing this issue. From the error stack trace you've shared, the problem seems to be caused in `Microsoft.ML.Data.BufferBuilder.GetResult` when it tries to copy the given `buffer` to `VBufferEditor editor` below:

https://github.com/dotnet/machinelearning/blob/8631afaaaa60daa1bda734dc79d92433591f7917/src/Microsoft.ML.Data/Data/BufferBuilder.cs#L435-L465

This seems like a memory overflow and/or a threading problem. Are you able to share your code and data, so that we can attempt to reproduce and analyze the error on our end?

**Comment by Babadinier** [comment]
Hi @mstfbl,

Thanks for your quick response.

I would be able to provide you with an example of the code we use, but the data we use to train the model is confidential - we use ML.net to analyze internal and external mail flow in our company. 

We basically train the model with 2000 examples and then just run Predict on this engine. 

Would you need all the training data too, and the input we provide to the predict function? My company has a full Microsoft support subscription. Is it possible to share with you within this subscription?

**Comment by mstfbl** [comment]
I see. Please provide an example of the code, and if possible, a randomized or fake data that is in the schema of your actual dataset, so that we can reproduce the issue on our end. Thanks.

**Comment by mstfbl** [comment]
Hi @Babadinier, without further data and/or code to go from, we are not able to further diagnose your issue. Please feel free to share any data, so that we may reopen this issue. Thanks.
