### ISSUE TITLE
NoColumn Attribute not recognized by TextLoaderSaverCatalog.LoadFromTextFile Method

### ISSUE THREAD

**Issue by scyentyfyc** [dotnet/machinelearning#5443]
### System information

- **OS version/distro**: Windows 10/ Home

- **.NET Version (eg., dotnet --info)**: 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

### Issue

- **What did you do?**
Tried to run the following code to load my training data out of a CSV file.  I've been using the AutoML CLI to this point to generate my models, and thought I'd take crack at doing it via my .NET code.  The `ModelInput` class has been working at runtime to load my metrics into, and pass to the model trained using the CLI, for predictions, even with the extra columns in the class.

```csharp
MLContext mlContext = new MLContext();
IDataView trainDataView = mlContext.Data.LoadFromTextFile<ModelInput>("data/data.csv", hasHeader: true);
```
- **What happened?**
Get error:
```
System.InvalidOperationException: Property 'Change_Tomorrow' is missing the LoadColumnAttribute attribute
   at Microsoft.ML.Data.TextLoader.CreateTextLoader[TInput](IHostEnvironment host, Options options, IMultiStreamSource dataSample)
   at Microsoft.ML.Data.TextLoader.CreateTextLoader[TInput](IHostEnvironment host, Boolean hasHeader, Char separator, Boolean allowQuoting, Boolean supportSparse, Boolean trimWhitespace, IMultiStreamSource dataSample)
   at Microsoft.ML.TextLoaderSaverCatalog.LoadFromTextFile[TInput](DataOperationsCatalog catalog, String path, Char separatorChar, Boolean hasHeader, Boolean allowQuoting, Boolean trimWhitespace, Boolean allowSparse)
```
- **What did you expect?**
Data to be loaded from my csv file into an IDataView

### Source code / logs
- **ModelInput Class**
This is a trimmed down version of my ModelInput class.  Note that the "Index(0)" attribute and the "Ignore" attribute come from the "CsvHelper" Nuget package, as I use this ModelInput class for both writing to Csv, and for input for model predictions.
```csharp
    public class ModelInput
    {
        [ColumnName("Country"), LoadColumn(0), Index(0)]
        public string Country { get; set; }
        [Ignore, NoColumn]
        public float Change_Tomorrow { get; set; }
        [Ignore, NoColumn]
        public DateTime DateTomorrow { get; set; }
    }
```

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by mstfbl** [comment]
Hi @scyentyfyc ,

Thank you for reporting this issue. Can you please attach the CSV file you're trying to load? I will attempt to replicate your issue and let you know of a fix. Thanks.

**Comment by mstfbl** [comment]
Hi @scyentyfyc ,

I attempted to repro your issue with a small fake CSV dataset according to `ModelInput`, and I was not able to obtain the `InvalidOperationException` you reported. Please feel free to share the CSV file with which you've reported this exception.
