### ISSUE TITLE
ResizeImages() raise System.ArgumentException when resizing image already at correct size

### ISSUE THREAD

**Issue by BobLd** [dotnet/machinelearning#5469]
### System information

- **OS version/distro**: Windows 10, 10.0.19041
- **.NET Version (eg., dotnet --info)**:  .NET Core 3.1.403

### Issue

- **What did you do?**
Doing inference on an image, with `ResizeImages()` part of the pipeline. The processed image is already at the correct size (1300x1300, i.e. no resizing needed). Also occurs with different pipeline/images when image already at `ResizeImages()` output size.

- **What happened?**
Program raised an exception: `System.ArgumentException: 'Parameter is not valid.'`
(No exception for other images, and for same image with a different size).

- **What did you expect?**
No exception.

### Source code / logs
```csharp
// Define scoring pipeline
var pipeline = mlContext.Transforms.ResizeImages(inputColumnName: "bitmap", outputColumnName: "image",
                                             imageWidth: 1300, imageHeight: 1300,
                                             resizing: ResizingKind.IsoPad)
                            .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "image", scaleImage: 1f / 255f))
                            .Append(mlContext.Transforms.ApplyOnnxModel(inputColumnNames: new[] { "image" },
                                                                        outputColumnNames: new[] { "boxes", "labels", "scores", "masks" },
                                                                        modelFile: modelLocation));
// Fit on empty list to obtain input data schema
var model = pipeline.Fit(mlContext.Data.LoadFromEnumerable(new List<InputBitmapData>()));

// Create prediction engine
var predictionEngine = mlContext.Model.CreatePredictionEngine<InputBitmapData, OutputPrediction>(model);

using (var bitmap = new Bitmap(Image.FromFile(imagePath)))
{
      var prediction = predictionEngine.Predict(new InputBitmapData() { Image = bitmap }); // <- error raised
}

```

```
System.ArgumentException
  HResult=0x80070057
  Message=Parameter is not valid.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.Image.get_Height()
   at Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper.<>c__DisplayClass3_0.<MakeGetter>b__1(Bitmap& dst)
   at Microsoft.ML.Transforms.Image.ImagePixelExtractingTransformer.Mapper.<>c__DisplayClass5_0`1.<GetGetterCore>b__1(VBuffer`1& dst)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.NamedOnnxValueGetterVec`1.GetNamedOnnxValue()
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.UpdateCacheIfNeeded(Int64 position, INamedOnnxValueGetter[] srcNamedOnnxValueGetters, String[] activeOutputColNames, OnnxRuntimeOutputCacher outputCache)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.<>c__DisplayClass12_0`1.<MakeTensorGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass8_0`1.<CreateDirectVBufferSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
   at Microsoft.ML.PredictionEngine`2.Predict(TSrc example, TDst& prediction)
   at Microsoft.ML.PredictionEngineBase`2.Predict(TSrc example)
```

Guess: the problem might come from here:
https://github.com/dotnet/machinelearning/blob/a9ab7fc530ba9a2a519aaca70862ee67f42bf712/src/Microsoft.ML.ImageAnalytics/ImageResizer.cs#L301-L305

**Comment by Lynx1820** [comment]
Hi @BobLd, I'm taking a look at it. If you can provide the repo, that would be great.

**Comment by BobLd** [comment]
@Lynx1820 , try running this repo: https://github.com/BobLd/YOLOv4MLNet

I've just added a new image that is problematic. If you run the code, it will runsmoothly for the first image (`kite.jpg`) but will throw an exception for the second one (`kite_416.jpg`).

Guessing again, when image are already at the correct size, this part is missed:
https://github.com/dotnet/machinelearning/blob/a9ab7fc530ba9a2a519aaca70862ee67f42bf712/src/Microsoft.ML.ImageAnalytics/ImageResizer.cs#L384-L401

I think a way to make this is also process, would be just to remove the following (or maybe to make it part of the if/else if chain):
```csharp
if (src.Height == info.ImageHeight && src.Width == info.ImageWidth)
{
    dst = src;
    return;
}
```

**Comment by BobLd** [comment]
HI @Lynx1820, I saw you did some work on this issue. Any update? If I can help, let me know

**Comment by rosebyte** [comment]
The `System.Drawing.Bitmap` implementation involved in this failure was removed in #6363 and replaced with `MLImage`. The reported code path no longer exists, so we are closing this issue.
