### ISSUE TITLE
Unable to split the file provided into multiple, consistent columns. (.tsv)

### ISSUE THREAD

**Issue by itwithlyam** [dotnet/machinelearning#5511]
### System information

- **OS version/distro**: Windows 10
- **.NET Version (eg., dotnet --info)**: 3.1.402

### Issue

- **What did you do?** I was trying to use ML.NET to create a support desk application.
- **What happened?** Once I pressed "start training" this error came:
`   Unable to split the file provided into multiple, consistent columns.
at Microsoft.ML.AutoML.ColumnInferenceApi.InferSplit(MLContext context, TextFileSample sample, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 112`
- **What did you expect?**

### Source code / logs
Logs:
at Microsoft.ML.AutoML.ColumnInferenceApi.InferSplit(MLContext context, TextFileSample sample, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse)
   at Microsoft.ML.AutoML.ColumnInferenceApi.InferColumns(MLContext context, String path, ColumnInformation columnInfo, Nullable`1 separatorChar, Nullable`1 allowQuotedStrings, Nullable`1 supportSparse, Boolean trimWhitespace, Boolean groupColumns, Boolean hasHeader)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.InferColumns(MLContext context, AutoMLServiceParamater config, ColumnInformation columnInformation)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 112
TSV file:
ID	Question Category
1	My printer isn't working.	Printer
1	Printer	Printer
2	I can't turn on my computer.	Computer
3	I would like to book a chromebook.	Chromebooks
1	My printer won't print.	Printer
1	My printer isn't working.	Printer
1	I can't print	Printer
2	My computer isn't working	Computer
2	My computer isn't turning on	Computer
2	Computer	Computer
2	My computer is malfunctioning.	Computer
3	Chromebooks	Chromebooks
3	I would like a chromebook.	Chromebooks
3	How can I book a chromebook?	Chromebooks
3	My chromebook isn't charging.

(before you ask, the tabs are formatted correctly in VS)

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

**Comment by itwithlyam** [comment]
Ah. Sorry. It was a mistake on my end in the tsv file.
Forgot to add "Chromebooks" to the category tab.
