### ISSUE TITLE
DataFrame can't handle separators in data

### ISSUE THREAD

**Issue by terrajobst** [dotnet/machinelearning#5647]
Related to dotnet/corefxlab#2968 

Looks like `DataFrame` can't handle CSV where the separator appears in the column data.

### Repro

```C#
var frame = DataFrame.LoadCsv(fileName);

foreach (var row in frame.Rows)
{
    Console.WriteLine(row[0]);
    Console.WriteLine(row[1]);
    Console.WriteLine(row[2]);
    Console.WriteLine();
}
```

CSV contents:

```text
Name,Age,Description
Paul,34,"Paul lives in Vermont, VA."
Victor,29,"Victor: Funny guy"
Maria,31,
```

### Expected behavior

Prints the contents of the CSV

### Actual behavior

Exception:

```text
Unhandled exception. System.FormatException: Line 2 has less columns than expected
   at Microsoft.Data.Analysis.DataFrame.GuessKind(Int32 col, List`1 read)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(Stream csvStream, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int64 numberOfRowsToRead, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(String filename, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int32 numRows, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at ConsoleApp49.Program.Main(String[] args)
```

**Comment by luisquintanilla** [comment]
Unable to repro as of verwion 0.20.0-preview.22313.1

**Comment by dakersnar** [comment]
As Luis mentioned, this issue appears to have been solved at some point. Regardless, I'm adding unit tests that confirm this behavior here: https://github.com/dotnet/machinelearning/pull/6301.
