### ISSUE TITLE
DataFrame can't handle line breaks

### ISSUE THREAD

**Issue by terrajobst** [dotnet/machinelearning#5648]
Looks like `DataFrame` can't handle CSV files where line breaks occur.

### Repro

```C#
var frame = DataFrame.LoadCsv(fileName);

foreach (var row in frame.Rows)
{
    Console.WriteLine(row[0]);
    Console.WriteLine(row[1]);
    Console.WriteLine(row[2]);
    Console.WriteLine();
}
```

CSV contents:

```text
Name,Age,Description
Paul,34,"Paul lives in Vermont VA."
Victor,29,"Victor:
Funny guy"
Maria,31,
```

### Expected behavior

Prints the contents of the CSV

### Actual behavior

Exception:

```text
Unhandled exception. System.FormatException: Line 3 has less columns than expected
   at Microsoft.Data.Analysis.DataFrame.GuessKind(Int32 col, List`1 read)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(Stream csvStream, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int64 numberOfRowsToRead, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(String filename, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int32 numRows, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at ConsoleApp49.Program.Main(String[] args)
```

**Comment by luisquintanilla** [comment]
Unable to repro in version 0.20.0-preview.22313.1. Closing this issue for now.
