### ISSUE TITLE
[DataFrame] Allow quoting when loading CSV

### ISSUE THREAD

**Issue by lqdev** [dotnet/machinelearning#5674]
Given the following code:

```fsharp
let df = DataFrame.LoadCsv("Data/test.csv")
```

And data that looks like the snippet below:

```text
Project Name,Neighborhood,Zip Code,TtlProjUnits,RentUnits,OwnUnits,TtlMarket,MarketRent,MarketOwn,Total Income- Restricted,Income- Restricted Rental,Income- Restricted Ownership,Tenure,Public/ Private,Includes Elderly Units?,Section_8
AB&W Cooperative Building,Roxbury,02121,24,24,0,0,0,0,24,24,0,Rental,Private,,
```

If a row contains the separator character, although surrounded in quotes:

```text
"Berkeley Investments, Inc.",South Boston,02127,97,0,97,89,0,89,8,0,8,Ownership,Private,,
```

The following error is thrown:

```text
Unhandled exception. System.ArgumentException: Expected value to be of type System.Single (Parameter 'val')
   at Microsoft.Data.Analysis.DataFrame.AppendRow(List`1 columns, Int64 rowIndex, String[] values)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(Stream csvStream, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int64 numberOfRowsToRead, Int32 guessRows, Boolean addIndexColumn)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(String filename, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int32 numRows, Int32 guessRows, Boolean addIndexColumn)
   at Program.main(String[] argv) in C:\Users\lqdev\Development\dotnet\FsDataFrameSample\FsDataFrameSample\Program.fs:line 9   
```

This is the source dataset for reference: https://data.boston.gov/dataset/income-restricted-housing

**Comment by luisquintanilla** [comment]
Unable to repro in version 0.20.0-preview.22313.1. Closing for now.
