### ISSUE TITLE
ERROR : Schema mismatch for input column

### ISSUE THREAD

**Issue by iluveu28** [dotnet/machinelearning#5714]
### System information

- **OS version/distro**: Linux
- **.NET Version (eg., dotnet --info)**: 5

### Issue

When I got to the training step - https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train

It failed with below error. Why and how to fix it?

### Source code / logs

Schema mismatch for input column 'TIU_SOC_tf_CharExtractor': expected Expected known-size vector of Single, got Vector<Single>
Parameter name: inputSchema

   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__26.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 150

**Comment by michaelgsharp** [comment]
Did you do anything different than what is in that tutorial?

@JakeRadMSFT any ideas?
