### ISSUE TITLE
Resource/Meta files unavailable for Image Classification

### ISSUE THREAD

**Issue by HashGrammer** [dotnet/machinelearning#5745]
### System information

- **OS version/distro**: Windows 10 1909
- **.NET Version (eg., dotnet --info)**:  2.1.519

### Issue

- **What did you do?**
Installed the MLNET Marketplace package for fresh install of visual studio 2017, opened the Model Builder, attempted to train a model.
- **What happened?**

As noted, but not responded to, in the most recent comments of issue #5052, the site no longer exists and and .meta is not available. Have these resources been moved, or is this just an outage type of failure with the server? Where can we acquire them manually in the meantime? Why hasn't the URL been updated in the NuGet package?

```
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] Downloading resnet_v2_50_299.meta from https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta to C:\Users\user\AppData\Local\Temp\MLNET\resnet_v2_50_299.meta
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Error] resnet_v2_50_299.meta: Could not download. WebClient returned the following error: The remote name could not be resolved: 'mlnetresources.blob.core.windows.net'
```
- **What did you expect?**
Model to train

### Source code / logs

```
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] Downloading resnet_v2_50_299.meta from https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta to C:\Users\user\AppData\Local\Temp\MLNET\resnet_v2_50_299.meta
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Error] resnet_v2_50_299.meta: Could not download. WebClient returned the following error: The remote name could not be resolved: 'mlnetresources.blob.core.windows.net'
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:00:50.2436251.
[Source=AutoML, Kind=Error] Pipeline crashed: xf=ValueToKeyMapping{ col=Label:Label} xf=RawByteImageLoading{ col=ImageSource_featurized:ImageSource imageFolder=} xf=ColumnCopying{ col=Features:ImageSource_featurized} tr=ImageClassification{} xf=KeyToValueMapping{ col=PredictedLabel:PredictedLabel} cache=- . Exception: System.InvalidOperationException: Error downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': The remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\n
Meta file could not be downloaded! Please copy the model file 'resnet_v2_50_299.meta' from 'meta\resnet_v2_50_299.meta' to 'C:\Users\user\AppData\Local\Temp\MLNET'.
   at Microsoft.ML.TensorFlow.TensorFlowUtils.DownloadIfNeeded(IHostEnvironment env, String url, String dir, String fileName, Int32 timeout)
   at Microsoft.ML.Vision.ImageClassificationTrainer.LoadTensorFlowSessionFromMetaGraph(IHostEnvironment env, Architecture arch)
   at Microsoft.ML.Vision.ImageClassificationTrainer.InitializeTrainingGraph(IDataView input)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String groupId, String labelColumn, IMetricsAgent`1 metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger)
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel disposed
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
Error downloading resource from 'https://aka.ms/mlnet-resources/meta/resnet_v2_50_299.meta': The remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\nThe remote name could not be resolved: 'mlnetresources.blob.core.windows.net'\n
Meta file could not be downloaded! Please copy the model file 'resnet_v2_50_299.meta' from 'meta\resnet_v2_50_299.meta' to 'C:\Users\user\AppData\Local\Temp\MLNET'.
```

**Comment by HashGrammer** [comment]
Resolved
