### ISSUE TITLE
Splitter/consolidator worker encountered exception while consuming source data

### ISSUE THREAD

**Issue by Tweekaz2018** [dotnet/machinelearning#5762]
### System information

Window Server R2 2012 x64
- ** .net 5

### Issue

- Image classification for 4 classes. 16000(4000 per cat) images
- Exception 
- Trained model

When i had 2500 images per class it was ok. At 3500 per class 1/10 ended successful.  

### Source code / logs
Splitter/consolidator worker encountered exception while consuming source data
at Microsoft.ML.Data.DataViewUtils.Splitter.Batch.SetAll(OutPipe[] pipes)
   at Microsoft.ML.Data.DataViewUtils.Splitter.Cursor.MoveNextCore()
   at Microsoft.ML.Data.RootCursorBase.MoveNext()
   at Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()
   at Microsoft.ML.Trainers.LbfgsTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data)
   at Microsoft.ML.Trainers.LbfgsTrainerBase`3.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at MarkerModel.MarkModel.TrainModel() in C:\Users\m\source\repos\Twitter\MarkerModel\Class1.cs:line 66
   at ModelTrainer.Trainer.TrainDefaultModel(ModelType type) in C:\Users\m\source\repos\Twitter\ModelTrainer\Trainer.cs:line 42

**Comment by Tweekaz2018** [comment]
Any info?

**Comment by danmoseley** [comment]
Could you share the exception info? Is it possible to share a repro case?

**Comment by Tweekaz2018** [comment]
> Splitter/consolidator worker encountered exception while consuming source data
> at Microsoft.ML.Data.DataViewUtils.Splitter.Batch.SetAll(OutPipe[] pipes)
> at Microsoft.ML.Data.DataViewUtils.Splitter.Cursor.MoveNextCore()
> at Microsoft.ML.Data.RootCursorBase.MoveNext()
> at Microsoft.ML.Trainers.TrainingCursorBase.MoveNext()
> at Microsoft.ML.Trainers.LbfgsTrainerBase`3.TrainCore(IChannel ch, RoleMappedData data) at Microsoft.ML.Trainers.LbfgsTrainerBase`3.TrainModelCore(TrainContext context)
> at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor) at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
> at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
> at MarkerModel.MarkModel.TrainModel() in C:\Users\m\source\repos\Twitter\MarkerModel\Class1.cs:line 66
> at ModelTrainer.Trainer.TrainDefaultModel(ModelType type) in C:\Users\m\source\repos\Twitter\ModelTrainer\Trainer.cs:line 42

It's exeption. 
I can share data because its 18000 of photo. 

I just can share my test method: 
```
public void TrainModel()
        {
            IEstimator<ITransformer> pipeline = mlContext.Transforms.LoadImages(outputColumnName: "input", imageFolder: "", inputColumnName: nameof(ImageData.ImagePath))
                           .Append(mlContext.Transforms.ResizeImages(outputColumnName: "input", imageWidth: InceptionSettings.ImageWidth, imageHeight: InceptionSettings.ImageHeight, inputColumnName: "input"))
                           .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "input", interleavePixelColors: InceptionSettings.ChannelsLast, offsetImage: InceptionSettings.Mean))
                           .Append(mlContext.Model.LoadTensorFlowModel(_inceptionTensorFlowModel).
                               ScoreTensorFlowModel(outputColumnNames: new[] { "softmax2_pre_activation" }, inputColumnNames: new[] { "input" }, addBatchDimensionInput: true))
                           .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName: "LabelKey", inputColumnName: "Label"))
                           .Append(mlContext.MulticlassClassification.Trainers.LbfgsMaximumEntropy(labelColumnName: "LabelKey", featureColumnName: "softmax2_pre_activation"))
                           .Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabelValue", "PredictedLabel"))
                           .AppendCacheCheckpoint(mlContext);

            int trainCount = _trainSet.Count / 100 * 90;
            var loadImages = _trainSet.Take(trainCount);
            IDataView trainingData = mlContext.Data.LoadFromEnumerable<ImageData>(loadImages);
            **model = pipeline.Fit(trainingData);**
            IDataView testData = mlContext.Data.LoadFromEnumerable<ImageData>(_trainSet.Skip(trainCount));
            IDataView predictions = model.Transform(testData);
            List<ImagePrediction> imagePredictionData = mlContext.Data.CreateEnumerable<ImagePrediction>(predictions, true).ToList();
            MulticlassClassificationMetrics metrics =
                mlContext.MulticlassClassification.Evaluate(predictions,
                  labelColumnName: "LabelKey",
                  predictedLabelColumnName: "PredictedLabel");
            schema = trainingData.Schema;
            var tested = Test(_trainSet.Skip(trainCount));
            LogLoss = metrics.LogLoss;
            SimpleTest = tested;
            Console.WriteLine($"LogLoss is {metrics.LogLoss}; Simple test - {tested}");
        }

        public double GetSimpleTestMetrics(string path = "")
        {
            double val = 0.0;
            var filePath = Path.Combine(path, Path.GetFileNameWithoutExtension(modelName) + ".txt");
            if (File.Exists(filePath))
                val = double.Parse(File.ReadAllText(filePath));
            return val;
        }
```
