### ISSUE TITLE
AutoML Recommender fails with error (Provided label column 'rating' was of type String, but only type Single is allowed.)

### ISSUE THREAD

**Issue by cyberkoolman** [dotnet/machinelearning#5865]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: ML.NET v1.5
 - .NET Version: NET 5.0

**Describe the bug**
Both VS Model Builder and mlnet CLI fails in executing model building on recommender.

**To Reproduce**
1. Grab the machinelearning-samples/samples/csharp/end-to-end-apps/Recommendation-MovieRecommender/MovieRecommender_Model/Data/ratings_train.csv
2. mlnet recommendation --dataset .\ratings_train.csv --item-col movieId --rating-col rating --user-col userId --has-header true --train-time 30
3. Error: One or more errors occurred. (Provided label column 'rating' was of type String, but only type Single is allowed.)
Tried to identify if the rating column indeed contains any string value, but it doesn't seem so.  Besides, manual implementation of Recommender works well.

**Expected behavior**
Should be able to complete to generate the model and the code.  

**Screenshots, Code, Sample Projects**
One or more errors occurred. (Provided label column 'rating' was of type String, but only type Single is allowed.)
System.AggregateException: One or more errors occurred. (Provided label column 'rating' was of type String, but only type Single is allowed.)
 ---> System.ArgumentException: Provided label column 'rating' was of type String, but only type Single is allowed.
   at Microsoft.ML.AutoML.UserInputValidationUtil.ValidateTrainDataColumn(IDataView trainData, String columnName, String columnPurpose, IEnumerable`1 allowedTypes)
   at Microsoft.ML.AutoML.UserInputValidationUtil.ValidateColumnInformation(IDataView trainData, ColumnInformation columnInformation, TaskKind task)
   at Microsoft.ML.AutoML.UserInputValidationUtil.ValidateExperimentExecuteArgs(IDataView trainData, ColumnInformation columnInformation, IDataView validationData, TaskKind task)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteCrossValSummary(IDataView[] trainDatasets, ColumnInformation columnInfo, IDataView[] validationDatasets, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, IDataView validationData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<>c__DisplayClass21_0.<ExecuteAsync>b__5() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 80
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.ExecuteAsync(IDataView trainData, IDataView validateData, ColumnInformation columnInformation, Nullable`1 userCancellationToken, Nullable`1 timeout) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AutoMLExperiment.cs:line 82
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(AutoMLServiceParameter config, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 134
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.ML.CLI.Runners.AutoMLRunner.Execute() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 71
   at Microsoft.ML.CLI.Program.Main(String[] args) in /_/src/mlnet/Program.cs:line 140

**Additional context**
Testing on classification and regression (with another set of data) of mlnet CLI works well.

**Comment by cyberkoolman** [comment]
Using Excel, I re-formatted the rating column to single.  Note that the rating column only contained the number and AutoML's Regression task doesn't make it as the similar issue on number column. Since the workaround is there, I will close this issue.
