### ISSUE TITLE
Executing experiment with SamplingKeyColumnName throws  'Validation data has 0 rows Arg_ParamName_Name'

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning#5911]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: 1.6.0
 - .NET Version: .NET 5.0

**Describe the bug**
I have a dataset with a sampling key column with about 10 text values derived from week numbers. First, I infer column types 
`ColumnInferenceResults columnInference = mlContext.Auto().InferColumns(TrainDataPath, LabelColumnName, groupColumns: false); `

Then, I set SamplingKeyColumnName, and run the experiment. Label and SamplingKeyColumnName are unrelated.

```
columnInformation.SamplingKeyColumnName = SamplingColumnName;
var experimentResult = experiment.Execute(TrainDataView, columnInformation, null, progressHandler);
```

After execution start I receive the exception 'Validation data has 0 rows Arg_ParamName_Name'

```
Unhandled exception. System.ArgumentException: Validation data has 0 rows (Parameter 'validationData')
   at Microsoft.ML.AutoML.UserInputValidationUtil.ValidateValidationData(IDataView trainData, IDataView validationData)
   at Microsoft.ML.AutoML.UserInputValidationUtil.ValidateExperimentExecuteArgs(IDataView trainData, ColumnInformation columnInformation, IDataView validationData, TaskKind task)
   at Microsoft.ML.AutoML.ExperimentBase`2.ExecuteTrainValidate(IDataView trainData, ColumnInformation columnInfo, IDataView validationData, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Microsoft.ML.AutoML.ExperimentBase`2.Execute(IDataView trainData, IDataView validationData, ColumnInformation columnInformation, IEstimator`1 preFeaturizer, IProgress`1 progressHandler)
   at Kwork.AI.AutoML.Program.RunAutoMLExperiment(MLContext mlContext, ColumnInferenceResults columnInference) in Q:\git\Kwork.AI.AutoML\Kwork.AI.AutoML\Program.cs:line 242
   at Kwork.AI.AutoML.Program.Main(String[] args) in Q:\git\Kwork.AI.AutoML\Kwork.AI.AutoML\Program.cs:line 80
```

If I don't set the sampling key, I am able to run the experiments.

I also receive the same error when trying to split manually:
```
var splitData = mlContext.Data.TrainTestSplit(TrainDataView, samplingKeyColumnName: SamplingColumnName);
experimentResult = experiment.Execute(splitData.TrainSet, splitData.TestSet, columnInformation, null, progressHandler);
```

**Comment by michaelgsharp** [comment]
Would it be possible for you to share a sample of the data you are using?

**Comment by torronen** [comment]
I just noticed: I am setting Sampling Key in `columnInformation` AND also in `TrainTestSplit`() arguments. So maybe it is now trying to sample from the already split test data? I am not able to test it right now, just FYI.
