### ISSUE TITLE
MLContext.BinaryClassification.CrossValidate - System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by Gloppy** [dotnet/machinelearning#5955]
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.7.3.2143002
 - Visual Studio Version:  Community 2019 version 16.11.1

**Describe the bug**
- On which step of the process did you run into an issue: CrossValidate
- Clear description of the problem: Unable to cross validate, throws an IndexOutOfRangeException

**To Reproduce**
1. Create a solution with the included project
2. Run PositionClassification2DModelBuilder.TrainModel(string outputModelPath, string filePath) using the included CSV file for data
3. See crash in CrossValidate

**Expected behavior**
CrossValidate should complete and not crash

**Additional context**
Cannot figure out why an IndexOutOfRangeException exception would happen in CrossValidate, but not in the pipeline training. It is entirely possible I am doing something wrong, but I get past the training phase.

[bug_report.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/7270682/bug_report.zip)

Stack Trace:
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Microsoft.ML.FastTree
  StackTrace:
   at Microsoft.ML.Trainers.FastTree.LeastSquaresRegressionTreeLearner.FindAndSetBestFeatureForLeaf(LeafSplitCandidates leafSplitCandidates)
   at Microsoft.ML.Trainers.FastTree.LeastSquaresRegressionTreeLearner.FindBestSplitOfRoot(Double[] targets)
   at Microsoft.ML.Trainers.FastTree.LeastSquaresRegressionTreeLearner.FitTargets(IChannel ch, Boolean[] activeFeatures, Double[] targets)
   at Microsoft.ML.Trainers.FastTree.GradientDescent.TrainingIteration(IChannel ch, Boolean[] activeFeatures)
   at Microsoft.ML.Trainers.FastTree.FastTreeTrainerBase`3.Train(IChannel ch)
   at Microsoft.ML.Trainers.FastTree.FastTreeTrainerBase`3.TrainCore(IChannel ch)
   at Microsoft.ML.Trainers.FastTree.FastTreeBinaryTrainer.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.TrainCatalogBase.CrossValidateTrain(IDataView data, IEstimator`1 estimator, Int32 numFolds, String samplingKeyColumn, Nullable`1 seed)
   at Microsoft.ML.BinaryClassificationCatalog.CrossValidate(IDataView data, IEstimator`1 estimator, Int32 numberOfFolds, String labelColumnName, String samplingKeyColumnName, Nullable`1 seed)
   at Gloppy.ML.Classification.Position2D.Model.PositionClassification2DModelBuilder.Evaluate(MLContext mlContext, IDataView trainingDataView, IEstimator`1 trainingPipeline) in Models\PositionClassification2D\PositionClassification2DModelBuilder.cs:line 168
   at Gloppy.ML.Classification.Position2D.Model.PositionClassification2DModelBuilder.CreateModel(IDataView trainingDataView) in Models\PositionClassification2D\PositionClassification2DModelBuilder.cs:line 73
   at Gloppy.ML.Classification.Position2D.Model.PositionClassification2DModelBuilder.TrainModel(String outputModelPath, IEnumerable`1 dataSource) in Models\PositionClassification2D\PositionClassification2DModelBuilder.cs:line 55
   at Gloppy.ML.Training.Trainer.Train2DPositionClassification(Object trainingParams) in Training\Trainer.cs:line 34
   at Testing.Program.Train(String rankLevel) in Testing\Program.cs:line 110
   at Testing.Program.<>c.<Main>b__4_0(Object o) in Testing\Program.cs:line 32
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by michaelgsharp** [comment]
@Gloppy it looks like the project you uploaded is missing a few files. Can you upload it again?

It can't resolve things like `ClassificationOutput`, `PositionClassificationInput`, `PositionInput2D`, and various others for example.

**Comment by Gloppy** [comment]
@michaelgsharp I apologize for that. It was part of a larger solution so I tried to cut it down into as small a piece as possible. In trying to create a working/better package for you I naturally cannot reproduce the issue anymore. I'm honestly not sure that I even really changed anything. I'll close the issue for now until I can reproduce it again.

**Comment by michaelgsharp** [comment]
@Gloppy no worries. If it repros again let me know so that we can take another look. Glad its working for you now!
