### ISSUE TITLE
DataFrame.LoadCsv fails when hasHeader=true

### ISSUE THREAD

**Issue by LittleLittleCloud** [dotnet/machinelearning#5979]
**System Information (please complete the following information):**
 - OS & Version: Win11
 - ML.NET Version: ML.Net 1.6.0

**Describe the bug**
dataset: 
[spam.csv](https://github.com/dotnet/machinelearning/files/7368451/spam.csv)

code:
```
DataFrame.LoadCsv(/path/to/csv, hasHeader: true)
```

**Comment by ericstj** [comment]
Did you mean `DataFrame.LoadCsv("spam.csv", header: true)`?

There is no parameter named `hasHeader`.

When I do this is see
```
Unhandled exception. System.ArgumentException: DataFrame already contains a column called  (Parameter 'column')
   at Microsoft.Data.Analysis.DataFrameColumnCollection.InsertItem(Int32 columnIndex, DataFrameColumn column)
   at Microsoft.Data.Analysis.DataFrameColumnCollection..ctor(IEnumerable`1 columns, Action columnsChanged)
   at Microsoft.Data.Analysis.DataFrame..ctor(IEnumerable`1 columns)
   at Microsoft.Data.Analysis.DataFrame.ReadCsvLinesIntoDataFrame(WrappedStreamReaderOrStringReader wrappedReader, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int64 numberOfRowsToRead, Int32 guessRows, Boolean addIndexColumn)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(Stream csvStream, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int64 numberOfRowsToRead, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at Microsoft.Data.Analysis.DataFrame.LoadCsv(String filename, Char separator, Boolean header, String[] columnNames, Type[] dataTypes, Int32 numRows, Int32 guessRows, Boolean addIndexColumn, Encoding encoding)
   at Program.<Main>$(String[] args) in C:\scratch\dataFrame\Program.cs:line 3
```

Which appears to be because your data has multiple unnamed columns:
```
v1,v2,,,
```

If I give the unnamed columns unique names then it succeeds:
```
v1,v2,c1,c2,c3
```

It looks like we are treating an empty string as a valid column name, which I don't think we should.  The fix should be here:
https://github.com/dotnet/machinelearning/blob/cc5e6395e0d15e4d3db702b9cb1129e12838b840/src/Microsoft.Data.Analysis/DataFrame.IO.cs#L113-L116

@LittleLittleCloud would you be interested in contributing a fix & test for this?

**Comment by LittleLittleCloud** [comment]
Yes, it's probably I'm not using the latest version of DataFrame API, but the error you got is the same with mine.

> It looks like we are treating an empty string as a valid column name, which I don't think we should. The fix should be here:

would love to

**Comment by ericstj** [comment]
FWIW I think `hasHeader` better represents the naming conventions we use in `.NET`.  I'm a bit surprised that the current state is not `hasHeader`.  @eerhardt do you recall if the current API went through API review?

There's also a workaround which is to pass the column header names if you are blocked.
```
var df = DataFrame.LoadCsv("spam.csv", header: true, columnNames: new [] { "v1", "v2", "c1", "c2", "c3"});
```

Thanks for taking this!

**Comment by eerhardt** [comment]
> FWIW I think hasHeader better represents the naming conventions we use in .NET. I'm a bit surprised that the current state is not hasHeader.

Agreed.

> @eerhardt do you recall if the current API went through API review?

It did, but it didn't go through that deep of a review of every parameter name. It was more "high level" API review. If you are interested, here are the notes of the API reviews it went through:

https://github.com/dotnet/apireviews/tree/main/2019/10-08-dataframe
https://github.com/dotnet/apireviews/tree/main/2019/11-05-dataframe
