### ISSUE TITLE
Disable Drawing tests on non-windows

### ISSUE THREAD

**Issue by ericstj** [dotnet/machinelearning#6162]
PR validation regularly fails with 
```
    Microsoft.ML.Tests.ImageTests.TestBackAndForthConversionWithoutAlphaNoInterleaveNoOffset [FAIL]
[31;1m[m[37m      System.ArgumentException : Parameter is not valid.
[m[30;1m      Stack Trace:
[m[37m           at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
[m[37m           at System.Drawing.Bitmap.UnlockBits(BitmapData bitmapdata)
[m[37m        /__w/1/s/src/Microsoft.ML.ImageAnalytics/VectorToImageTransform.cs(421,0): at Microsoft.ML.Transforms.Image.VectorToImageConvertingTransformer.Mapper.<>c__DisplayClass5_0`1.<GetterFromType>b__0(Bitmap& dst)
[m[37m        /__w/1/s/test/Microsoft.ML.Tests/ImagesTests.cs(804,0): at Microsoft.ML.Tests.ImageTests.TestBackAndForthConversionWithoutAlphaNoInterleaveNoOffset()
[m[30;1m      Output:
[m[37m        Test TestBackAndForthConversionWithoutAlphaNoInterleaveNoOffset: aborted: passed
```

This is bug https://github.com/dotnet/runtime/issues/30184, but it will never be fixed now that Unix is no longer supported.  Let's disable Image tests on non-windows until we can replace the usage of drawing with a different library.

**Comment by rosebyte** [comment]
Closing as superseded by the removal of `System.Drawing` in #6363.
