### ISSUE TITLE
ML.NET CLI failing but ML.NET Model Builder is working fine for same training dataset

### ISSUE THREAD

**Issue by dliedke** [dotnet/machinelearning#6196]
### System information

- **OS version/distro**: Windows 10 20H2
- **.NET Version (eg., dotnet --info)**:  6.0.300
- mlnet --version
16.13.5+936af07a091757189faee78de128429bf06a6845

ML.NET Model Builder version: 16.13.6.2226201

### Issue

- **What did you do?**

Train ML classification model.

- **What happened?**

Failing in ML.NET CLI but working fine in ML.NET Model Builder with the exact same dataset.

- **What did you expect?**

ML Model created.

### Source code / logs

Please paste or attach the code or logs or traces that would be helpful to diagnose the issue you are reporting.

C:\Temp>mlnet classification --dataset results_AI_Training_ChatViewer.csv --label-col TemplateName
Start Training
start nni training
Experiment output folder: C:\Temp\Windows\AutoML-NNI\Experiment-5MYR1S
[##                                                                                                              ]
Trial 0 encounter error with message: Must be at least 2. (Parameter 'numClasses')
System.ArgumentOutOfRangeException: Schema mismatch for score column 'Score': expected vector of two or more items of type Single, got Vector<Single, 1> (Parameter 'schema')
   at Microsoft.ML.Data.MulticlassClassificationEvaluator.CheckScoreAndLabelTypes(RoleMappedSchema schema)
   at Microsoft.ML.Data.EvaluatorBase`1.CheckColumnTypes(RoleMappedSchema schema)
   at Microsoft.ML.Data.EvaluatorBase`1.Microsoft.ML.Data.IEvaluator.Evaluate(RoleMappedData data)
   at Microsoft.ML.Data.MulticlassClassificationEvaluator.Evaluate(IDataView data, String label, String score, String predictedLabel)
   at Microsoft.ML.MulticlassClassificationCatalog.Evaluate(IDataView data, String labelColumnName, String scoreColumnName, String predictedLabelColumnName, Int32 topKPredictionCount)
   at Microsoft.ML.ModelBuilder.AutoMLService.MulticlassClassificationRunner.RunTrainTestSplit(TrialParameter parameter, TrainingConfiguration config, IDataView trainDatasetCache, IDataView testDatasetCache) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Runner/MulticlassClassificationRunner.cs:line 86
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.Run() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 172
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.<RunAsync>b__19_0() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 181
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.RunAsync() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 181
   at Microsoft.ML.ModelBuilder.AutoMLService.LocalDispatcher.AddTrialAsync(TrialParameter parameter) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Dispatcher/LocalDispatcher.cs:line 48
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.LocalAutoMLExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, ColumnInformation columnInformation, CancellationToken cancellationToken, CancellationToken timeout) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/LocalAutoMLExperiment.cs:line 168
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(TrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 160
   at Microsoft.ML.CLI.Runners.AutoMLRunner.ExecuteAsync() in /_/src/mlnet/Runners/AutoMLRunner.cs:line 88
   at Microsoft.ML.CLI.Program.TrainAsync(TrainingConfiguration trainingConfiguration, PathConfiguration pathConfig, AutoMLServiceLogLevel logLevel) in /_/src/mlnet/Program.cs:line 348
   at Microsoft.ML.CLI.Program.AutoMLCommandRunner(AutoMLCommand command, Boolean skipGenerateConsoleApp) in /_/src/mlnet/Program.cs:line 329
   at Microsoft.ML.CLI.Program.<>c.<<CreateRootCommandLineBuilder>b__4_0>d.MoveNext() in /_/src/mlnet/Program.cs:line 89
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.CommandHandler.GetExitCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.ML.CLI.Program.<>c__DisplayClass4_0.<<CreateRootCommandLineBuilder>b__9>d.MoveNext() in /_/src/mlnet/Program.cs:line 290
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
Check out log file for more information: C:\Temp\Windows\mlnet\log.txt
Exiting ...

I can't post dataset because of compliance issues, but it seems ML.NET algorithms are not the same in both tools. The dataset has around 9.9mb with 9 classes and 65k rows.

**Comment by LittleLittleCloud** [comment]
Did your dataset contains mostly 1 class type in the first 10k rows or so?

**Comment by dliedke** [comment]
yes, 18.8k training rows for first class, is this a problem? 
Thanks!

**Comment by LittleLittleCloud** [comment]
Yeah, you can learn details from this [issue](https://github.com/dotnet/machinelearning-modelbuilder/issues/2102) but in short, shuffling in ml.net sometimes doesn't result to a global shuffle. We fixed it in latest model builder, but not in cli yet.


One work-around is to make sure you have all labels appear in first 10k of your dataset

**Comment by dliedke** [comment]
Thanks for the update, I will try that approach and report back.

**Comment by LittleLittleCloud** [comment]
And you probably want to remove experiment output folder as well

> Experiment output folder: C:\Temp\Windows\AutoML-NNI\Experiment-5MYR1S

And just FYI we are also publishing a new ml.net cli, it might be available in nuget in a few minutes. So an update of cli might also work

**Comment by dliedke** [comment]
Yes, I am always removing the experiment output folder. Thanks for the tip.

> And just FYI we are also publishing a new ml.net cli which include that fix, it might be available in nuget in a few minutes. So an update of cli might also work
That is great!!

I added a manual shuffling for the training data using code below and it worked.

public void Shuffle<T>(IList<T> list)
        {
            int n = list.Count;
            while (n > 1)
            {
                n--;
                int k = rngShuffle.Next(n + 1);
                T value = list[k];
                list[k] = list[n];
                list[n] = value;
            }
        }

Thanks @LittleLittleCloud  for the amazing support!

Daniel Liedke

**Comment by dliedke** [comment]
Can you please let me know if new package is available? Should I just update the mlnet tool with command `dotnet tool update --global mlnet-win-x64` correct?

Thank you!

Daniel

**Comment by dliedke** [comment]
I got the new version here and I will try again:

dotnet tool install --global mlnet-win-x64
You can invoke the tool using the following command: mlnet
Tool 'mlnet-win-x64' (version '16.13.6') was successfully installed.

**Comment by dliedke** [comment]
Confirmed issue fixed for mlnet 16.13.6

Really appreciate the fast fix for this issue!

Daniel Liedke
