### ISSUE TITLE
Cannot run Transform on DataFrame with DateTime type

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning#6213]
**System Information (please complete the following information):**
 - OS & Version: [e.g. Windows 10] 
 - ML.NET Version: 1.7.1
 - .NET Version: [e.g. .NET 5.0]

**Describe the bug**
I'm adding the DateTime type to Model Builder, but unfortunately a few features are broken because of DataFrame support. DataFrame doesn't support the DateTime type directly. However I can add a PrimitiveDataFrameColumn of type DateTime. This displays correctly but breaks when I try to use the DataFrame for a prediction 

```
System.NotSupportedException: Specified method is not supported.
   at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.GetDataViewType()
   at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.AddDataViewColumn(Builder builder)
   at Microsoft.Data.Analysis.DataFrame.get_DataViewSchema()
   at Microsoft.Data.Analysis.DataFrame.Microsoft.ML.IDataView.get_Schema()
   at Microsoft.ML.Data.TransformerChain`1.Transform(IDataView input)
   at Submission#8.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**To Reproduce**
`var resultDataView = model.Transform(dataFrame /*DataFrame with DateTime*/);`

I have a notebook with the problem here [DateTimeDF.zip](https://github.com/dotnet/machinelearning/files/8828238/DateTimeDF.zip)

**Expected behavior**
Since IDataView supports the DateTime type, I expect DataFrame to support it as well.

**Comment by beccamc** [comment]
I assume this is the same root cause as this - https://github.com/dotnet/machinelearning/issues/5698

**Comment by michaelgsharp** [comment]
@beccamc I'll tag this for our "future" milestone and we can pull it in whenever we have the capacity to work on it.
