### ISSUE TITLE
Text Classification Target 2 is out of bounds

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6225]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version: 2.0.0-preview-22310.1, 0.20.0-preview-22310.1
 - .NET Version: .NET 6.0

**Describe the bug**

When training a model with [GitHub Issues dataset](https://raw.githubusercontent.com/dotnet/samples/main/machine-learning/tutorials/GitHubIssueClassification/Data/issues_train.tsv) with the following pipeline I get the error `Target 2 is out of bounds`

**Pipeline**:

```csharp
//Initialize MLContext
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.TorchSharp;

var mlContext = new MLContext();

// Load your data
var dataView = mlContext.Data.LoadFromTextFile<ModelInput>(@"C:\Datasets\issues_train.tsv", separatorChar: '\t', hasHeader: true);

//Define your training pipeline
var pipeline =
		mlContext.Transforms.Conversion.MapValueToKey("Label","Area")
			.Append(mlContext.MulticlassClassification.Trainers.TextClassification(sentence1ColumnName: "Title"))
			.Append(mlContext.Transforms.Conversion.MapKeyToValue("PredictedLabel"));

// Train the model

Console.WriteLine("Training model...");

var model = pipeline.Fit(dataView);

Console.WriteLine("Model trained...");

public class ModelInput
{
    [LoadColumn(0)]
    public int Id { get; set; }

    [LoadColumn(1)]
    public string Area { get; set; }

    [LoadColumn(2)]
    public string Title { get; set; }

    [LoadColumn(3)]
    public string Description { get; set; }
}

```

**Stacktrace**

```
System.Runtime.InteropServices.ExternalException
  HResult=0x80004005
  Message=Target 2 is out of bounds.
Exception raised from nll_loss_out_frame at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\LossNLL.cpp:230 (most recent call first):
00007FFFC6DDA4C200007FFFC6DDA460 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFFC6DB3ED500007FFFC6DB3E60 c10.dll!c10::IndexError::IndexError [<unknown file> @ <unknown line number>]
00007FFF898A1FB400007FFF8989CE60 torch_cpu.dll!at::native::multi_margin_loss_cpu_out [<unknown file> @ <unknown line number>]
00007FFF898A58F300007FFF8989CE60 torch_cpu.dll!at::native::multi_margin_loss_cpu_out [<unknown file> @ <unknown line number>]
00007FFF898A773400007FFF898A76D0 torch_cpu.dll!at::native::structured_nll_loss_forward_out_cpu::impl [<unknown file> @ <unknown line number>]
00007FFF8A0EC3DE00007FFF8A0DB710 torch_cpu.dll!at::cpu::zero_ [<unknown file> @ <unknown line number>]
00007FFF8A0B19AE00007FFF8A086730 torch_cpu.dll!at::cpu::bucketize_outf [<unknown file> @ <unknown line number>]
00007FFF89CEB89000007FFF89C974F0 torch_cpu.dll!at::_ops::zeros_out::redispatch [<unknown file> @ <unknown line number>]
00007FFF89E7308300007FFF89E72FE0 torch_cpu.dll!at::_ops::nll_loss_forward::redispatch [<unknown file> @ <unknown line number>]
00007FFF8AC0AFA300007FFF8AA8A050 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFF8ABD60F200007FFF8AA8A050 torch_cpu.dll!torch::autograd::GraphRoot::apply [<unknown file> @ <unknown line number>]
00007FFF89E2698C00007FFF89E26800 torch_cpu.dll!at::_ops::nll_loss_forward::call [<unknown file> @ <unknown line number>]
00007FFF898A7F0F00007FFF898A7E90 torch_cpu.dll!at::native::nll_loss [<unknown file> @ <unknown line number>]
00007FFF8A26B6B200007FFF8A267680 torch_cpu.dll!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFF8A24AA5D00007FFF8A21FD00 torch_cpu.dll!at::compositeimplicitautograd::broadcast_to [<unknown file> @ <unknown line number>]
00007FFF89EF0C6F00007FFF89EF0AE0 torch_cpu.dll!at::_ops::nll_loss::call [<unknown file> @ <unknown line number>]
00007FFF898A888F00007FFF898A7F80 torch_cpu.dll!at::native::nll_loss_nd [<unknown file> @ <unknown line number>]
00007FFF8A26B6E200007FFF8A267680 torch_cpu.dll!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFF8A24AACD00007FFF8A21FD00 torch_cpu.dll!at::compositeimplicitautograd::broadcast_to [<unknown file> @ <unknown line number>]
00007FFF89D3142F00007FFF89D312A0 torch_cpu.dll!at::_ops::nll_loss_nd::call [<unknown file> @ <unknown line number>]
00007FFF898A653F00007FFF898A6250 torch_cpu.dll!at::native::cross_entropy_loss [<unknown file> @ <unknown line number>]
00007FFF8A26968100007FFF8A267680 torch_cpu.dll!at::compositeimplicitautograd::where [<unknown file> @ <unknown line number>]
00007FFF8A24AB5200007FFF8A21FD00 torch_cpu.dll!at::compositeimplicitautograd::broadcast_to [<unknown file> @ <unknown line number>]
00007FFF89ED6B2300007FFF89ED6980 torch_cpu.dll!at::_ops::cross_entropy_loss::call [<unknown file> @ <unknown line number>]
00007FFF895CFC7100007FFF895CFC40 torch_cpu.dll!at::cross_entropy_loss [<unknown file> @ <unknown line number>]
00007FFF9C2C008500007FFF9C2BFEE0 LibTorchSharp.DLL!THSNN_cross_entropy [<unknown file> @ <unknown line number>]
00007FFF436CE068 <unknown symbol address> !<unknown symbol> [<unknown file> @ <unknown line number>]

  Source=TorchSharp
  StackTrace:
   at TorchSharp.torch.CheckForErrors()
   at TorchSharp.torch.nn.functional.<>c__DisplayClass100_0.<cross_entropy_loss>b__0(Tensor src, Tensor target)
   at Microsoft.ML.TorchSharp.NasBert.TextClassificationTrainer.Trainer.TrainStep(DataViewRowCursor cursor, ValueGetter`1 sentence1Getter, ValueGetter`1 sentence2Getter, ValueGetter`1 labelGetter, List`1& inputTensors, List`1& targets)
   at Microsoft.ML.TorchSharp.NasBert.TextClassificationTrainer.Trainer.Train(IDataView input)
   at Microsoft.ML.TorchSharp.NasBert.TextClassificationTrainer.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Program.<Main>$(String[] args) in C:\Users\luquinta.REDMOND\source\repos\TextClassificationAPI\TextClassificationAPI\Program.cs:line 22

```

**Comment by michaelgsharp** [comment]
As discussed this is due to the number of classes not being specified correctly. Initially we will just make it not have a default value. In the future we will have it auto figure this out.
