### ISSUE TITLE
Text Classification index out of range in self

### ISSUE THREAD

**Issue by luisquintanilla** [dotnet/machinelearning#6226]
**System Information (please complete the following information):**
 - OS & Version: Windows 11
 - ML.NET Version: ML.NET 2.0.0-preview.22310.1, ML.NET 0.20.0-preview.22310.1
 - .NET Version: .NET 6.0

**Describe the bug**

When running a training workload on the [wikipedia detox dataset](https://raw.githubusercontent.com/dotnet/machinelearning/main/test/data/wikipedia-detox-250-line-data.tsv) with the following pipeline, I get the error `index out of range in self`:

**Pipeline**

```csharp
//Initialize MLContext
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.TorchSharp;
using System.ComponentModel;

var mlContext = new MLContext();

// Load your data
var dataView = mlContext.Data.LoadFromTextFile<ModelInput>(@"C:\Datasets\wikipedia-detox-250-line-data.tsv", hasHeader: true);

//Define your training pipeline
var pipeline =
		mlContext.Transforms.Conversion.MapValueToKey("Label","Sentiment")
			.Append(mlContext.MulticlassClassification.Trainers.TextClassification(sentence1ColumnName: "SentimentText", outputColumnName: "outputColumn"))
			.Append(mlContext.Transforms.Conversion.MapKeyToValue("outputColumn"));

// Train the model

Console.WriteLine("Training model...");

var model = pipeline.Fit(dataView);

Console.WriteLine("Model trained...");

public class ModelInput
{
    [LoadColumn(0)]
    public float Sentiment { get; set; }

    [LoadColumn(1)]
    public string SentimentText { get; set; }
}
```

**Stacktrace**
```
System.Runtime.InteropServices.ExternalException
  HResult=0x80004005
  Message=index out of range in self
Exception raised from operator () at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorAdvancedIndexing.cpp:996 (most recent call first):
00007FFFA4C8A4C200007FFFA4C8A460 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFFA4C63ED500007FFFA4C63E60 c10.dll!c10::IndexError::IndexError [<unknown file> @ <unknown line number>]
00007FFF899A545200007FFF89992360 torch_cpu.dll!at::native::_bincount_cpu [<unknown file> @ <unknown line number>]
00007FFF899ADA5F00007FFF89992360 torch_cpu.dll!at::native::_bincount_cpu [<unknown file> @ <unknown line number>]
00007FFF8999567800007FFF89992360 torch_cpu.dll!at::native::_bincount_cpu [<unknown file> @ <unknown line number>]
00007FFF98A7D8ED00007FFF98A7D7C0 libiomp5md.dll!_kmp_invoke_microtask [<unknown file> @ <unknown line number>]
00007FFF98A2777C00007FFF98A26E30 libiomp5md.dll!_kmpc_threadprivate_register_vec [<unknown file> @ <unknown line number>]
00007FFF989DE72C00007FFF989D4B50 libiomp5md.dll!_kmp_acquire_nested_drdpa_lock [<unknown file> @ <unknown line number>]
00007FFF98A682B200007FFF98A68160 libiomp5md.dll!_kmp_launch_worker [<unknown file> @ <unknown line number>]
00007FF890F754E000007FF890F754D0 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FF89296485B00007FF892964830 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]

  Source=TorchSharp
  StackTrace:
   at TorchSharp.torch.CheckForErrors()
   at TorchSharp.Modules.Embedding.forward(Tensor input)
   at Microsoft.ML.TorchSharp.NasBert.Modules.LearnedPositionalEmbedding.forward(Tensor input, Dictionary`2 param)
   at Microsoft.ML.TorchSharp.NasBert.Models.TransformerEncoder.ForwardEmbedding(Tensor tokens, Tensor segmentLabels, Tensor positions)
   at Microsoft.ML.TorchSharp.NasBert.Models.TransformerEncoder.forward(Tensor tokens, Tensor segmentLabels, Tensor positions)
   at Microsoft.ML.TorchSharp.NasBert.Models.BaseModel.ExtractFeatures(Tensor srcTokens)
   at Microsoft.ML.TorchSharp.NasBert.Models.TextClassificationModel.forward(Tensor srcTokens, Tensor tokenMask)
   at Microsoft.ML.TorchSharp.NasBert.TextClassificationTrainer.Trainer.TrainStep(DataViewRowCursor cursor, ValueGetter`1 sentence1Getter, ValueGetter`1 sentence2Getter, ValueGetter`1 labelGetter, List`1& inputTensors, List`1& targets)
   at Microsoft.ML.TorchSharp.NasBert.TextClassificationTrainer.Trainer.Train(IDataView input)
   at Microsoft.ML.TorchSharp.NasBert.TextClassificationTrainer.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Program.<Main>$(String[] args) in C:\Users\luquinta.REDMOND\source\repos\TextClassificationAPI\TextClassificationAPI\Program.cs:line 22
```

**To Reproduce**

**Expected behavior**

**Screenshots, Code, Sample Projects**
If applicable, add screenshots, code snippets, or sample projects to help explain your problem.

**Additional context**

**Comment by michaelgsharp** [comment]
As discussed this is because the tensor length is too long. Our model limits us to 512 characters and this is past that. Will fix this for now by throwing a more descriptive error when this happens.

In the future we will want to add support to either fail with an error, auto truncate the row, or drop the whole row.
