### ISSUE TITLE
Exception When Doing Image Prediction On Ubuntu

### ISSUE THREAD

**Issue by QuinnDamerell** [dotnet/machinelearning#6244]
**System Information (please complete the following information):**
 - OS & Version: Ubuntu 20.04.4 LTS
 - ML.NET Version: ML 1.7.1
 - .NET Version: NET 6.0

**Describe the bug**

I'm running a quite standard version of Ubuntu, using the latest dotnet 6.0 and latest ML libs, but for some reason, I'm getting this exception while trying to do an image clarification prediction on Linux. This logic work just fine on Windows. 

I looked up the issue and found this old bug from before dotnet 3.0. 
https://github.com/dotnet/runtime/issues/27200

I did however still ran `apt-get install libgdiplus libc6-dev` and make sure the .so was in the /usr/lib dir where it should have been, yet I still get this issue.

Error: Exception throw in GadgetMl perdict.; TypeInitializationException - The type initializer for 'Gdip' threw an exception. -    at System.Drawing.SafeNa>
    at System.Drawing.Image.InitializeFromStream(Stream stream)
    at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
    at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
    at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement)
    at System.Drawing.Image.FromStream(Stream stream)
    at Microsoft.ML.Data.ImageLoadingTransformer.Mapper.<>c__DisplayClass4_0.<MakeGetterImageDataViewType>b__1(Bitmap& dst)
    at Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper.<>c__DisplayClass3_0.<MakeGetter>b__1(Bitmap& dst)
    at Microsoft.ML.Transforms.Image.ImagePixelExtractingTransformer.Mapper.<>c__DisplayClass5_0`1.<GetGetterCore>b__1(VBuffer`1& dst)
    at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.NamedOnnxValueGetterVec`1.GetNamedOnnxValue()
    at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.UpdateCacheIfNeeded(Int64 position, INamedOnnxValueGetter[] srcNamedOnnxValueGetters, List`1 activ>
    at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.<>c__DisplayClass14_0`1.<MakeTensorGetter>b__0(VBuffer`1& dst)
    at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass8_0`1.<CreateDirectVBufferSetter>b__0(TRow row)
    at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
    at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
    at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
    at Microsoft.ML.PredictionEngine`2.Predict(TSrc example, TDst& prediction)

**To Reproduce**

**Expected behavior**

**Screenshots, Code, Sample Projects**
If applicable, add screenshots, code snippets, or sample projects to help explain your problem.

**Additional context**

**Comment by gfoidl** [comment]
Please see [System.Drawing.Common only supported on Windows](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only).

**Comment by QuinnDamerell** [comment]
Thanks for that response! I looked for an answer for about 30 minutes, and somehow I never came by this.

Is there any work planned to move the ML libs away from this dependency? It would be amazing if they would be operational on Linux, where I assume most of these prediction servers would be running. Maybe the system could be updated to use a modern cross-plat dotnet 6 alternative?

**Comment by michaelgsharp** [comment]
@QuinnDamerell so if you look are the [Recommended Actions](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) section, there is a way to enable support for it still. From my understanding the support won't be removed until .NET 7 comes out. So if you enable it, it should still work. Can you try and that let me know because if not we can take a look to see whats going on.

As far as moving away from this dependency that is the plan. We are going to use a new library to deal with images before .NET 7/ML.NET 2.0 drops in November, though the exact mechanism we are going to use is still up for debate (new dependency on another library, some type of abstraction, etc).
