### ISSUE TITLE
[ML.net cli] Resume a cli training after a crash 

### ISSUE THREAD

**Issue by wil70** [dotnet/machinelearning#6286]
Hello, is there a way to resume an ML.net cli training to where it was before a crash?
I have a lot of data in the folder C:\Users\wwww\AppData\Local\Temp\AutoML-NNI\Experiment-9K67B4 but I do not know how to make mlnet start from there.

Detail:
I used the cli, ie "mlnet classicfiaction...."
I trained for a few days, but I made a mistake which used a lot of memory on my computer, which stopped the mlnet process. I would like to start mlnet to where it left so it can continue from there

Thanks
w

2022-08-10 15:03:24.3091 DEBUG System.InvalidOperationException: Event we were waiting on was subject to an exception
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Array.Resize[T](T[]& array, Int32 newSize)
   at Microsoft.ML.Internal.Utilities.ArrayUtils.EnsureSize[T](T[]& array, Int32 min, Int32 max, Boolean keepOld, Boolean& resized)
   at Microsoft.ML.Data.CacheDataView.ColumnCache.ImplOne`1.CacheCurrent()
   at Microsoft.ML.Data.CacheDataView.Filler(DataViewRowCursor cursor, ColumnCache[] caches, OrderedWaiter waiter)

**Comment by dakersnar** [comment]
I don't believe this functionality is currently supported.

cc @luisquintanilla for confirmation. Is this something that we are tracking support for in the future?
