### ISSUE TITLE
Model Builder Error

### ISSUE THREAD

**Issue by kitosd** [dotnet/machinelearning#6295]
Model Builder Version : 16.1.0.20.27905
Visual Studio Version : 16.11.18

Bug description
With freshly-updated [as of today, 2022-08-19] VS2019 and model builder, I tried to use the new ML builder wizard "Value prediction". It failed with an exception: Method not found: 'System.Collections.Generic.IEnumerable1<System.ValueTuple2<Microsoft.ML.AutoML.RunDetail`1<!!0>,Int32>> Microsoft.ML.AutoML.BestResultUtil.GetTopNRunResults

Steps to Reproduce

Installed latest VS 2019 and updated Model Builder to latest version
Create new project. Right click on project -> Add -> "Machine Learning"
Choose image classification, "Local ML", Next.
As input, choose an appropriate folder, observe "data preview" looks like I expected, with images being shown under various classifications
Train, Start Training.
Expected Experience
Pretty much what I'd expect from the tutorial, and of a wizard.

Actual Experience
Shortly after click "start training", I get this:
"GPU Service not found. Falling back to CPU AutoML Service."

Moments later, this exception:
Method not found: 'System.Collections.Generic.IEnumerable1<System.ValueTuple2<Microsoft.ML.AutoML.RunDetail1<!!0>,Int32>> Microsoft.ML.AutoML.BestResultUtil.GetTopNRunResults(System.Collections.Generic.IEnumerable1<Microsoft.ML.AutoML.RunDetail1<!!0>>, Microsoft.ML.AutoML.IMetricsAgent1<!!0>, Int32, Boolean)'.
at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment3.d__21.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment3.ExecuteAsync(IDataView trainData, IDataView validateData, ColumnInformation columnInformation, Nullable1 userCancellationToken, Nullable`1 timeout)
at Microsoft.ML.ModelBuilder.AutoMLEngine.d__30.MoveNext() in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 147

**Comment by luisquintanilla** [comment]
Hi @kitosd 

Sorry to hear you ran into issues. Would it be possible for you to use Model Builder in VS 2022 instead of VS 2019

**Comment by kitosd** [comment]
> Hi @kitosd 
> 
> 
> 
> Sorry to hear you ran into issues. Would it be possible for you to use Model Builder in VS 2022 instead of VS 2019

I tried that but I have same error
