### ISSUE TITLE
Image Prediction : OOM when allocating tensor with shape

### ISSUE THREAD

**Issue by PerfectEngineer** [dotnet/machinelearning#6308]
### System information

- **OS version/distro**: Win 10
- **.NET Version (eg., dotnet --info)**:  6.0
- **ML.NET Version**: ML.NET v1.7.1
- **SciSharp.TensorFlow.Redis: 2.3.1**

**Issue OOM when allocating tensor**

 
### Code
BitmapImage imageAsBitmap = new BitmapImage(new Uri("D:/ImageToGetPrediction.jpeg"));
var encoder = new JpegBitmapEncoder();
encoder.Frames.Add(BitmapFrame.Create(imageAsBitmap));
var input = new Input();

using (MemoryStream ms = new MemoryStream())
{
encoder.Save(ms);
input.Image = ms.ToArray();
}
var prediction = _predictor.Predict(input);

### Exception 
OOM when allocating tensor with shape[1,75,75,256] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[{{node resnet_v2_101/block1/unit_1/bottleneck_v2/conv3/BiasAdd}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
INNERMESSAGE 
STACKTRACE:    at Microsoft.ML.TensorFlow.TensorFlowUtils.Runner.Run()
   at Microsoft.ML.Vision.ImageClassificationModelParameters.Classifier.Score(VBuffer`1& image, Span`1 classProbabilities)
   at Microsoft.ML.Vision.ImageClassificationModelParameters.<>c__DisplayClass22_0`2.<Microsoft.ML.Data.IValueMapper.GetMapper>b__0(VBuffer`1& src, VBuffer`1& dst)
   at Microsoft.ML.Data.SchemaBindablePredictorWrapperBase.<>c__DisplayClass19_0`2.<GetValueGetter>b__0(TDst& dst)
   at Microsoft.ML.Data.PredictedLabelScorerBase.EnsureCachedPosition[TScore](Int64& cachedPosition, TScore& score, DataViewRow boundRow, ValueGetter`1 scoreGetter)
   at Microsoft.ML.Data.MulticlassClassificationScorer.<>c__DisplayClass16_0.<GetPredictedLabelGetter>b__1(VBuffer`1& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass8_0`1.<CreateDirectVBufferSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
   at Microsoft.ML.PredictionEngine`2.Predict(TSrc example, TDst& prediction)
   at Microsoft.ML.PredictionEngineBase`2.Predict(TSrc example)

**Comment by michaelgsharp** [comment]
@tarekgh is this something you think that the new image changes will help address?

**Comment by tarekgh** [comment]
We need a complete working sample to try it. @PerfectEngineer can you provide that?
