### ISSUE TITLE
ExtractPixels transform not able to split in multi dimentional array.

### ISSUE THREAD

**Issue by JeremyMahieu** [dotnet/machinelearning#6602]
**System Information (please complete the following information):**
 - OS & Version: Windows 10
 - ML.NET Version: 2.0.1
 - .NET Version: .NET 7.0

**Describe the bug**
Getting the following error. I cannot get the ExtractPixels transformer to split the pixels up into a multi dimentional array. (8 images (can get this down to 1 with batch size), 3 channel, 1280pixel, 1280pixel.

System.InvalidOperationException: 'Input shape mismatch: Input 'images' has shape 8,3,1280,1280, but input data is of length 4915200.'
```
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper..ctor(OnnxTransformer parent, DataViewSchema inputSchema)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.MakeRowMapper(DataViewSchema inputSchema)
   at Microsoft.ML.Data.RowToRowTransformerBase.GetOutputSchema(DataViewSchema inputSchema)
   at Microsoft.ML.Data.TrivialEstimator`1.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
```

**To Reproduce**
1. Create an onnx model with ultralytics yolov8
2. Try to use it in .net

**Expected behavior**
Have the pixel extractor split the image into a float[1, 3, 1280, 1280] form.

**Screenshots, Code, Sample Projects**
Pipeline looks like this
```csharp
            var inputColumns = new string[] { "images" };
            var outputColumns = new string[] { "output0" };
            var pipeline = mlContext.Transforms.LoadImages(outputColumnName: "images", imageFolder: "", inputColumnName: "images")
                .Append(mlContext.Transforms.ResizeImages(outputColumnName: "images", imageWidth: 1280, imageHeight: 1280, inputColumnName: "images"))
                .Append(mlContext.Transforms.ExtractPixels(outputColumnName: "images"))
                .Append(mlContext.Transforms.ApplyOnnxModel(modelFile: ONNX_MODEL_PATH, outputColumnNames: outputColumns, inputColumnNames: inputColumns));
            var emptyDv = mlContext.Data.LoadFromEnumerable(new OnnxInput[] { });

            return pipeline.Fit(emptyDv); (ERROR HERE)
```

The model looks like this:
![image](https://user-images.githubusercontent.com/23409814/226076837-16a03f9b-35bc-4855-beb5-5feaaaaec1d4.png)

**Additional context**
I switched from a working project with ml.net model and wanted to use an onnx model.

**Comment by JeremyMahieu** [comment]
setting batch to 1 helped. Apparently there's not beffierent between [1,3,1280,1280] and [4915200]
