### ISSUE TITLE
Unable to load shared library 'SymSgdNative' or one of its dependencies

### ISSUE THREAD

**Issue by hieu-n** [dotnet/machinelearning#6603]
**System Information (please complete the following information):**
 - OS & Version: Ubuntu 22.04.2 LTS
 - ML.NET Version: 2.0.1
 - .NET Version: 7.0.101

**Describe the bug**
Unable to use `mlContext.BinaryClassification.Trainers.SymbolicSgdLogisticRegression`. It looks like the native libraries are missing for linux build.

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'SymSgdNative' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/myhome/SampleProject/bin/Debug/net7.0/runtimes/linux-x64/native/SymSgdNative.so: cannot open shared object file: No such file or directory
/home/myhome/dotnet/shared/Microsoft.NETCore.App/7.0.1/SymSgdNative.so: cannot open shared object file: No such file or directory
/home/myhome/SampleProject/bin/Debug/net7.0/SymSgdNative.so: cannot open shared object file: No such file or directory
libomp.so: cannot open shared object file: No such file or directory
/home/myhome/dotnet/shared/Microsoft.NETCore.App/7.0.1/libSymSgdNative.so: cannot open shared object file: No such file or directory
/home/myhome/SampleProject/bin/Debug/net7.0/libSymSgdNative.so: cannot open shared object file: No such file or directory
/home/myhome/SampleProject/bin/Debug/net7.0/runtimes/linux-x64/native/SymSgdNative: cannot open shared object file: No such file or directory
/home/myhome/dotnet/shared/Microsoft.NETCore.App/7.0.1/SymSgdNative: cannot open shared object file: No such file or directory
/home/myhome/SampleProject/bin/Debug/net7.0/SymSgdNative: cannot open shared object file: No such file or directory
/home/myhome/SampleProject/bin/Debug/net7.0/runtimes/linux-x64/native/libSymSgdNative: cannot open shared object file: No such file or directory
/home/myhome/dotnet/shared/Microsoft.NETCore.App/7.0.1/libSymSgdNative: cannot open shared object file: No such file or directory
/home/myhome/SampleProject/bin/Debug/net7.0/libSymSgdNative: cannot open shared object file: No such file or directory

   at Microsoft.ML.Trainers.SymbolicSgdLogisticRegressionBinaryTrainer.Native.LearnAll(Int32 totalNumInstances, Int32* instSizes, Int32** instIndices, Single** instValues, Single* labels, Boolean tuneLR, Single& lr, Single l2Const, Single piw, Single* weightVector, Single& bias, Int32 numFeatres, Int32 numPasses, Int32 numThreads, Boolean tuneNumLocIter, Int32& numLocIter, Single tolerance, Boolean needShuffle, Boolean shouldInitialize, State* state, ChannelCallBack info)
   at Microsoft.ML.Trainers.SymbolicSgdLogisticRegressionBinaryTrainer.Native.LearnAll(InputDataManager inputDataManager, Boolean tuneLR, Single& lr, Single l2Const, Single piw, Span`1 weightVector, Single& bias, Int32 numFeatres, Int32 numPasses, Int32 numThreads, Boolean tuneNumLocIter, Int32& numLocIter, Single tolerance, Boolean needShuffle, Boolean shouldInitialize, GCHandle stateGCHandle, ChannelCallBack info)
   at Microsoft.ML.Trainers.SymbolicSgdLogisticRegressionBinaryTrainer.TrainCore(IChannel ch, RoleMappedData data, LinearModelParameters predictor, Int32 weightSetCount)
   at Microsoft.ML.Trainers.SymbolicSgdLogisticRegressionBinaryTrainer.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at SampleProject.Program.Main(String[] args) in /home/myhome/SampleProject/Program.cs:line 53
```

**To Reproduce**
1. Create a new console application with the command `dotnet new console -o SampleProject`.
2. Adding ML.Net packages.
3. Create a simple code to train a binary classification model using `SymbolicSgdLogisticRegression`.
4. Run and encounter the exception.

**Expected behavior**
The program should run without exceptions and the model is successfully trained.

**Screenshots, Code, Sample Projects**
SampleProject.csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="2.0.1" />
    <PackageReference Include="Microsoft.ML.AutoML" Version="0.20.1" />
    <PackageReference Include="Microsoft.ML.LightGbm" Version="2.0.1" />
    <PackageReference Include="Microsoft.ML.Probabilistic.Compiler" Version="0.4.2301.301" />
    <PackageReference Include="MKL.NET.linux-x64" Version="2022.0.1.117" />
  </ItemGroup>

</Project>
```

Program.cs

```
using Microsoft.ML;
using Microsoft.ML.Data;

namespace SampleProject;

public class HousingData
{
    public float Size { get; set; }

    [VectorType(3)]
    public float[] HistoricalPrices { get; set; }

    public float CurrentPrice { get; set; }
    public bool Label { get; set; }
}

public class Program
{
    public static void Main(string[] args)
    {
        HousingData[] inMemoryCollection = new HousingData[]
        {
            new HousingData
            {
                Size = 700f,
                HistoricalPrices = new float[]
                {
                    100000f, 3000000f, 250000f
                },
                CurrentPrice = 500000f,
                Label = true
            },
            new HousingData
            {
                Size = 1000f,
                HistoricalPrices = new float[]
                {
                    600000f, 400000f, 650000f
                },
                CurrentPrice = 700000f,
                Label = false
            }
        };
        // Create MLContext
        MLContext mlContext = new MLContext();

        //Load Data
        IDataView data = mlContext.Data.LoadFromEnumerable(inMemoryCollection);
        var pipeline = mlContext.Transforms.Concatenate("Features", "Size", "HistoricalPrices", "CurrentPrice")
            .Append(mlContext.BinaryClassification.Trainers.SymbolicSgdLogisticRegression());
        var model = pipeline.Fit(data);
        
    }
}
```

**Comment by michaelgsharp** [comment]
If this is still an issue for you, make sure you have `Microsoft.ML.Mkl.Components` installed as this will bring in the `libSymSgdNative`.

Then, I noticed that `libSymSgdNative` depends on both `libomp.so` and `libiomp5.so`. It shouldn't depend on `libomp.so`, just the `libiomp5.so`, so you will have to use `patchelf` to remove `libomp.so`. I'll figure out why its doing that.

**Comment by michaelgsharp** [comment]
Tracking this here #6972 6972
