### ISSUE TITLE
System.TypeLoadException: Could not load type 'Microsoft.ML.Runtime.ITrainer`2'

### ISSUE THREAD

**Issue by rauhs** [dotnet/machinelearning#663]
### System information

- **OS version/distro**: 10.0.14
- **.NET Version (eg., dotnet --info)**: 2.1.202

### Issue

- **What did you do?**
Upgraded my pipeline to v0.4. It used SDCA multi classification.

On the *first* `Train` call it always throws a

```
System.TypeLoadException: Could not load type 'Microsoft.ML.Runtime.ITrainer`2' from assembly 'Microsoft.ML.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at Microsoft.ML.Runtime.ComponentCatalog.CacheLoadedAssemblies()
   at Microsoft.ML.Runtime.ComponentCatalog.FindLoadableClasses[TSig]()
   at Microsoft.ML.Runtime.EntryPoints.ModuleCatalog..ctor(IExceptionContext ectx)
   at Microsoft.ML.Runtime.EntryPoints.ModuleCatalog.CreateInstance(IExceptionContext ectx)
   at Microsoft.ML.Runtime.Experiment..ctor(IHostEnvironment env)
   at Microsoft.ML.LearningPipeline.Train[TInput,TOutput]()
```

It works fine on subsequent training calls to similar pipelines. It worked fine under 0.3

**Comment by Ivanidzo4ka** [comment]
What kind of project are you use? Any chance this is Asp.net?
Our current DI system is a bit old and obsolete and was written with assumption of .net framework and expect all dlls present in binary folder. 
Also why it's 
> Microsoft.ML.Core, Version=1.0.0.0 

version =1.0, I've check our Microsoft.ML nuget and we have version 0.4.26807.2
Any chance you know how this dll get into your binary folder?

**Comment by rauhs** [comment]
It's a normal Console project, nothing fancy. I did copy all the dlls into the binary project folder.

Not sure why I get a `1.0.0.0` version in the exception. I've since tried LightGBM again and had to do the workaround (which i didn't have to do for 0.3) from Stackoverflow. Now, the exception I originally posted seems to be gone.

**Comment by Ivanidzo4ka** [comment]
DRI RESPONSE: At this point I don't think it's possible to give answer unless you can provide us project, since it's quite old (0.4), about legacy pipeline, and in generally it works on my machine with default project.

**Comment by rauhs** [comment]
Closing. Will re-open in case if happens again.

**Comment by trumhemcut** [comment]
Downgrade to Microsoft.ML 1.5.5 works fine to me
