### ISSUE TITLE
Cannot converted to ONNX model by trained model

### ISSUE THREAD

**Issue by HoaNguyen55** [dotnet/machinelearning#6693]
**System Information (please complete the following information):**
 - OS & Version: Google Colab
 - ML.NET Version: Here is some package version
```
<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.14.1" />
<PackageReference Include="Microsoft.ML.OnnxConverter" Version="0.20.1" />
<PackageReference Include="Google.Protobuf" Version="3.20.3" />
<PackageReference Include="Microsoft.ML.OnnxTransformer" Version="2.0.1" />
<PackageReference Include="Microsoft.ML" Version="2.0.1" />
```

**Describe the bug**
I try to load model MLModel.zip which is generated from AutoML, then I load this trained model to convert to *.ONNX model.
I face this error status:
```
Unhandled exception. System.InvalidOperationException: The targeted pipeline can not be fully converted into a well-defined ONNX model. Please check if all steps in that pipeline are convertible to ONNX and all necessary variables are not dropped (via command line arguments).
   at Microsoft.ML.Model.OnnxConverter.SaveOnnxCommand.ConvertTransformListToOnnxModel(OnnxContextImpl ctx, IChannel ch, IDataView inputData, IDataView outputData, LinkedList`1 transforms, HashSet`1 inputColumnNamesToDrop, HashSet`1 outputColumnNamesToDrop)
   at Microsoft.ML.OnnxExportExtensions.ConvertToOnnxProtobufCore(IHostEnvironment env, OnnxContextImpl ctx, ITransformer transform, IDataView inputData, String[] outputColumnNamesToKeep)
   at Microsoft.ML.OnnxExportExtensions.ConvertToOnnxProtobuf(ModelOperationsCatalog catalog, ITransformer transform, IDataView inputData, String[] outputColumns)
   at Microsoft.ML.OnnxExportExtensions.ConvertToOnnx(ModelOperationsCatalog catalog, ITransformer transform, IDataView inputData, Stream stream)
   at consumeModelApp.Program.Main(String[] args) in /content/drive/MyDrive/hinhhoc/consumeModelApp_Onnx/Program.cs:line 56

```
Line:56 in Program.cs:
```
mlContext.Model.ConvertToOnnx(mlModel, transformedData, onnx);
```
The format of my dataset in TSV file is:
```
Label	ImageSource
one_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_hash_marks/one_hash_marks_2.png
one_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_hash_marks/one_hash_marks_3.png
one_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_hash_marks/one_hash_marks_6.png
one_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_hash_marks/one_hash_marks_4.png
two_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/two_hash_marks/two_hash_marks_858.png
two_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/two_hash_marks/two_hash_marks_528.png
two_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/two_hash_marks/two_hash_marks_868.png
two_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/two_hash_marks/two_hash_marks_590.png
two_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/two_hash_marks/two_hash_marks_513.png
two_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/two_hash_marks/two_hash_marks_429.png
two_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/two_hash_marks/two_hash_marks_714.png
two_hash_marks	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/two_hash_marks/two_hash_marks_546.png
one_degree	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_degree/one_degree_251.png
one_degree	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_degree/one_degree_35.png
one_degree	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_degree/one_degree_265.png
one_degree	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_degree/one_degree_201.png
one_degree	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_degree/one_degree_157.png
one_degree	/content/drive/MyDrive/hinhhoc/train_kyhieu_1/one_degree/one_degree_289.png
```

**To Reproduce**
1. Run Google Colab and install all related library
2. Convert to ONNX model by snipping code in attachments
[program.txt](https://github.com/dotnet/machinelearning/files/11496163/program.txt)

3. See error

**Expected behavior**
Generate ONNX file and be able to load this file by using Python in Google Colab environment.

**Screenshots, Code, Sample Projects**
N/A
**Additional context**
N/A

**Comment by luisquintanilla** [comment]
Hi @HoaNguyen55 

Sorry to hear you ran into issues.

The issue appears to be because not all the transforms / trainers in your pipeline are exportable to ONNX. Building ONNX exportable pipelines is not currently a scenario we support today. There are a few workarounds.

1. Run the ML.NET model as is without converting to ONNX
2. Manually edit the pipeline generated by AutoML to use ONNX exportable transforms where possible. Here's a list of transforms and trainers listing their ONNX support. 

  - https://learn.microsoft.com/dotnet/machine-learning/resources/transforms
  - https://learn.microsoft.com/dotnet/machine-learning/how-to-choose-an-ml-net-algorithm

May I ask what the scenario here is that you're exporting to ONNX instead of using the model as is?

**Comment by michaelgsharp** [comment]
Closing due to stale issue.
