### ISSUE TITLE
Failure to load lib_lightgbm in  Microsoft.ML.Fairlearn.Tests.GridSearchTest.TestGridSearchTrialRunner2

### ISSUE THREAD

**Issue by ericstj** [dotnet/machinelearning#6841]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=419700
Build error leg or test failing: Microsoft.ML.Fairlearn.Tests.GridSearchTest.TestGridSearchTrialRunner2
Pull request: https://github.com/dotnet/machinelearning/pull/6837

## Error Message

```
Exception Message
System.AggregateException : One or more errors occurred. (Unable to load shared library 'lib_lightgbm' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblib_lightgbm, 0x0001): tried: 'liblib_lightgbm' (no such file), '/usr/local/lib/liblib_lightgbm' (no such file), '/usr/lib/liblib_lightgbm' (no such file), '/private/tmp/helix/working/C4560A62/w/B640096B/e/liblib_lightgbm' (no such file))
---- System.DllNotFoundException : Unable to load shared library 'lib_lightgbm' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblib_lightgbm, 0x0001): tried: 'liblib_lightgbm' (no such file), '/usr/local/lib/liblib_lightgbm' (no such file), '/usr/lib/liblib_lightgbm' (no such file), '/private/tmp/helix/working/C4560A62/w/B640096B/e/liblib_lightgbm' (no such file)
CallStack
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.ML.AutoML.AutoMLExperiment.Run() in /Users/runner/work/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/AutoMLExperiment.cs:line 204
   at Microsoft.ML.Fairlearn.Tests.GridSearchTest.TestGridSearchTrialRunner2() in /Users/runner/work/1/s/test/Microsoft.ML.Fairlearn.Tests/GridSearchTest.cs:line 104
----- Inner Stack Trace -----
   at Microsoft.ML.Trainers.LightGbm.WrappedLightGbmInterface.DatasetCreateFromSampledColumn(IntPtr sampleValuePerColumn, IntPtr sampleIndicesPerColumn, Int32 numCol, Int32[] sampleNonZeroCntPerColumn, Int32 numSampleRow, Int32 numTotalRow, String parameters, SafeDataSetHandle& ret)
   at Microsoft.ML.Trainers.LightGbm.Dataset..ctor(Double[][] sampleValuePerColumn, Int32[][] sampleIndicesPerColumn, Int32 numCol, Int32[] sampleNonZeroCntPerColumn, Int32 numSampleRow, Int32 numTotalRow, String param, Single[] labels, Single[] weights, Int32[] groups) in /Users/runner/work/1/s/src/Microsoft.ML.LightGbm/WrappedLightGbmDataset.cs:line 66
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.CreateDatasetFromSamplingData(IChannel ch, Factory factory, Int32 numRow, String param, Single[] labels, Single[] weights, Int32[] groups, CategoricalMetaData catMetaData, Dataset& dataset) in /Users/runner/work/1/s/src/Microsoft.ML.LightGbm/LightGbmTrainerBase.cs:line 995
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.LoadTrainingData(IChannel ch, RoleMappedData trainData, CategoricalMetaData& catMetaData) in /Users/runner/work/1/s/src/Microsoft.ML.LightGbm/LightGbmTrainerBase.cs:line 663
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.TrainModelCore(TrainContext context) in /Users/runner/work/1/s/src/Microsoft.ML.LightGbm/LightGbmTrainerBase.cs:line 440
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor) in /Users/runner/work/1/s/src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs:line 157
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input) in /Users/runner/work/1/s/src/Microsoft.ML.Data/Training/TrainerEstimatorBase.cs:line 77
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input) in /Users/runner/work/1/s/src/Microsoft.ML.Data/DataLoadSave/EstimatorChain.cs:line 68
   at Microsoft.ML.Fairlearn.GridSearchTrailRunner.RunAsync(TrialSettings settings, CancellationToken ct) in /Users/runner/work/1/s/src/Microsoft.ML.Fairlearn/Reductions/GridSearchTrialRunner.cs:line 79
   at Microsoft.ML.AutoML.AutoMLExperiment.RunAsync(CancellationToken ct) in /Users/runner/work/1/s/src/Microsoft.ML.AutoML/AutoMLExperiment/AutoMLExperiment.cs:line 273
```

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unable to load shared library 'lib_lightgbm' or one of its dependencies.",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=419700
**Error message validated:** `Unable to load shared library 'lib_lightgbm' or one of its dependencies.`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 9/27/2023 6:14:12 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by michaelgsharp** [comment]
@LittleLittleCloud is this one of the issues that we fixed? Correctly loading lightgbm for grid search tests?
