### ISSUE TITLE
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'TF_StringEncodedSize' in shared library 'tensorflow'.

### ISSUE THREAD

**Issue by fuszenecker** [dotnet/machinelearning#6893]
**System Information (please complete the following information):**
 - OS & Version: Ubuntu Linux 22.04 LTS
 - ML.NET Version: 3.0.0
 - .NET Version: .NET 8.0

**Describe the bug**
When I try to train a model for image classification, I receive the exception below:

```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'TF_StringEncodedSize' in shared library 'tensorflow'.
   at Tensorflow.c_api.TF_StringEncodedSize(UInt64 len)
   at Microsoft.ML.Vision.ImageClassificationTrainer.EncodeByteAsString(VBuffer`1 buffer)
   at Microsoft.ML.Vision.ImageClassificationTrainer.ImageProcessor.ProcessImage(VBuffer`1& imageBuffer)
   at Microsoft.ML.Vision.ImageClassificationTrainer.CacheFeaturizedImagesToDisk(IDataView input, String labelColumnName, String imageColumnName, ImageProcessor imageProcessor, String inputTensorName, String outputTensorName, String cacheFilePath, Dataset dataset, Action`1 metricsCallback, Nullable`1 validationFraction)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Program.<Main>$(String[] args) in /home/fuszenecker/dev/zp/Program.cs:line 25
```

**To Reproduce**
1. Update the `SciSharp.TensorFlow.Redist` package from `2.3.1` to `2.16.0`.
2. See error

**Expected behavior**
No exception received, the classification works as expected.

**Screenshots, Code, Sample Projects**

```
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.Mkl.Redist" Version="3.0.0" />
    <PackageReference Include="Microsoft.ML.ImageAnalytics" Version="3.0.0" />
    <PackageReference Include="Microsoft.ML.Vision" Version="3.0.0" />
    <PackageReference Include="SciSharp.TensorFlow.Redist" Version="2.16.0" />
  </ItemGroup>
```

**Additional context**

**Comment by ericstj** [comment]
Here's the breaking change notice from TF:
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#breaking-changes-14

> * C-API functions `TF_StringDecode`, `TF_StringEncode`, and `TF_StringEncodedSize` are no longer relevant and have been removed; see `core/platform/ctstring.h` for  string access/modification in C.

So we'd need to update TF and remove our usage of this API.  

If I check 
https://github.com/tensorflow/tensorflow/blob/bbef4c482abe0fb81f98d12eed73efd641fc7e93/tensorflow/core/platform/ctstring.h#L19

It redirects to 
https://github.com/tensorflow/tensorflow/blob/bbef4c482abe0fb81f98d12eed73efd641fc7e93/third_party/xla/third_party/tsl/tsl/platform/ctstring.h#L50-L55

```
// Returns the size of the string.
inline size_t TF_TString_GetSize(const TF_TString *str);
// Returns the capacity of the string buffer.  It should not be considered safe
// to write in the region between size and capacity---call Resize or
// ResizeUninitialized before doing so.
inline size_t TF_TString_GetCapacity(const TF_TString *str);
```

So maybe what we need is to use one of these instead.

**Comment by luisquintanilla** [comment]
Hi @fuszenecker 

For TensorFlow, we currently support up to version 2.3.1. Changing the version to 2.3.1 should address this issue.
