### ISSUE TITLE
Unable to update OnnxRuntime

### ISSUE THREAD

**Issue by ericstj** [dotnet/machinelearning#6916]
**System Information (please complete the following information):**
 - OS & Version: Windows 11 22H2 x64
 - ML.NET Version: https://github.com/dotnet/machinelearning/pull/6703
 - .NET Version: Net 8

**Describe the bug**
When updating OnnxRuntime to 1.15.0 or later 4 tests fail with 
```
  Error Message:
   System.InvalidOperationException : Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:Fail] OnnxValueType must either be a tensor or sparse tensor
   at Microsoft.ML.OnnxRuntime.NodeMetadata.CheckTensor()
   at Microsoft.ML.OnnxRuntime.NodeMetadata.get_Dimensions()
   at Microsoft.ML.Transforms.Onnx.OnnxModel.GetOnnxVariablesFromMetadata(IReadOnlyDictionary`2 nodeMetadata, IDictionary`2 shapeDictionary, Dictionary`2 typePool, Dictionary`2 casterPool) in C:\src\dotnet\machinelearning\src\Microsoft.ML.OnnxTransformer\OnnxUtils.cs:line 302
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads) in C:\src\dotnet\machinelearning\src\Microsoft.ML.OnnxTransformer\OnnxUtils.cs:line 257
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes) in C:\src\dotnet\machinelearning\src\Microsoft.ML.OnnxTransformer\OnnxTransform.cs:line 260
```
Failing tests are:
Microsoft.ML.Tests.OnnxTransformTests.TestOnnxModelNotDisposal
Microsoft.ML.Tests.OnnxTransformTests.TestOnnxModelDisposal
Microsoft.ML.Tests.OnnxTransformTests.TestOnnxZipMapWithStringKeys
Microsoft.ML.Tests.OnnxTransformTests.TestOnnxZipMapWithInt64Keys

**To Reproduce**
1. Update MicrosoftMLOnnxRuntimeVersion to 1.16.1.
2. build and run test on Microsoft.ML.OnnxTransformerTest

**Expected behavior**
All tests pass

**Screenshots, Code, Sample Projects**
4 tests above fail

**Comment by abagh0703** [comment]
Maybe this issue is better suited for the Onnxruntime repo https://github.com/microsoft/onnxruntime

**Comment by matouskozak** [comment]
Resolved in https://github.com/dotnet/machinelearning/pull/6975
