### ISSUE TITLE
HttpClient.Timeout in Microsoft.ML.Tokenizers.Tests

### ISSUE THREAD

**Issue by ericstj** [dotnet/machinelearning#7065]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=601020
Build error leg or test failing: Microsoft.ML.Tokenizers.Tests.EnglishRobertaTests.TokenizationTest
Pull request: https://github.com/dotnet/machinelearning/pull/7063

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": ["The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.", "at Microsoft.ML.Tokenizers.Tests.EnglishRobertaTests.TokenizationTest"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": true
}
```

Failure log:
```
[m[31;1m    Microsoft.ML.Tokenizers.Tests.EnglishRobertaTests.TokenizationTest [FAIL]
[m[37m      System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
[m[37m      ---- System.TimeoutException : A task was canceled.
[m[37m      -------- System.Threading.Tasks.TaskCanceledException : A task was canceled.
[m[30;1m      Stack Trace:
[m[37m           at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
[m[37m           at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[m[37m        /Users/runner/work/1/s/test/Microsoft.ML.Tokenizers.Tests/Utils.cs(19,0): at Microsoft.ML.Tokenizers.Tests.Utils.DownloadFile(String url, String fileName)
[m[37m        /Users/runner/work/1/s/test/Microsoft.ML.Tokenizers.Tests/EnglishRobertaTests.cs(93,0): at Microsoft.ML.Tokenizers.Tests.EnglishRobertaTests.TokenizationTest()
[m[37m           at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[m[37m        ----- Inner Stack Trace -----
[m[37m        
[m[37m        ----- Inner Stack Trace -----
[m[37m           at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[m[37m           at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[m[37m           at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[m[37m           at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[m[37m           at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=601020
**Error message validated:** `[The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. at Microsoft.ML.Tokenizers.Tests.EnglishRobertaTests.TokenizationTest`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 3/13/2024 5:34:21 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by tarekgh** [comment]
Should be addressed by https://github.com/dotnet/machinelearning/pull/7098
