### ISSUE TITLE
DataFrameColumn.And System.NotSupportedException: Specified method is not supported.

### ISSUE THREAD

**Issue by RaphaelPliessnig** [dotnet/machinelearning#7091]
- OS & Version: Windows 10
 - ML.NET Version: Data.Analysis 21.1
 - .NET Version: .NET 8.0

Since i upgraded to Data.Analysis 21.1 from 20.0 the ".And" method does not work anymore. 
I also cant "downgrade to 20.0 anymore since i get this error: Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension

```
#r "nuget: Microsoft.Data.Analysis, 0.21.1"

using System;

using Microsoft.Data.Analysis;

var col1 = new BooleanDataFrameColumn("col1", new Boolean[]{true, false, true});
var col2 = new BooleanDataFrameColumn("col2", new Boolean[]{false, true, true});
var dfTest = new DataFrame(col1,col2);
dfTest["and"] = dfTest["col1"].And(dfTest["col2"])
```
before the update to 21.1 everything worked as expected but i am now getting this error: 
Error: System.NotSupportedException: Specified method is not supported.
at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.HandleOperationImplementation[U](BinaryOperation operation, PrimitiveDataFrameColumn`1 column, Boolean inPlace)
at Microsoft.Data.Analysis.PrimitiveDataFrameColumn`1.And(DataFrameColumn column, Boolean inPlace)
at Submission#3.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

am i missing some dependencies or is this method just no longer supported? 

Thank you in advance

**Comment by asmirnov82** [comment]
Hello @RaphaelPliessnig 
Thanks for reporting the defect. Fix is ready https://github.com/dotnet/machinelearning/pull/7093

@JakeRadMSFT can we release 0.21.2 version with the latest fixes?

While fix is not released you may change you code to this:

```cs
var col1 = new BooleanDataFrameColumn("col1", new Boolean[]{true, false, true});
var col2 = new BooleanDataFrameColumn("col2", new Boolean[]{false, true, true});
var dfTest = new DataFrame(col1,col2);
dfTest["and"] = col1.And(col2)
```

this should help.

**Comment by RaphaelPliessnig** [comment]
Thank you very much. 
The workaround helps!
