### ISSUE TITLE
mlnet finds duplicate columns where they don't exist

### ISSUE THREAD

**Issue by thomasd3** [dotnet/machinelearning#7269]
I use this command:

```
mlnet classification --dataset training.csv  --validation-dataset validating.csv --train-time 100 --label-col 0 --ignore-cols 1 2 3 -has-header true --name test
```

and I get this error:
```
Start Training
[Source=TextLoader; Binding, Kind=Info] Duplicate name(s) specified - later columns will hide earlier ones
System.ArgumentException: An item with the same key has already been added. Key: 22742.3                                                                                                                                                                         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)                                                                                                                                                      at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
```

But there are absolutely no duplicate names in the columns.

This is the (very long) header:
```
label_score_long_1005,label_score_short_1005,timestamp,interval,high0,high0_h1,high0_p03,high0_p05,high0_p10,high_raw0,high_raw0_h1,high_raw0_p03,high_raw0_p05,high_raw0_p10,low0,low0_h1,low0_p03,low0_p05,low0_p10,low_raw0,low_raw0_h1,low_raw0_p03,low_raw0_p05,low_raw0_p10,close0,close0_h1,close0_p03,close0_p05,close0_p10,close_raw0,close_raw0_h1,close_raw0_p03,close_raw0_p05,close_raw0_p10,volume0,volume0_h1,volume0_p03,volume0_p05,volume0_p10,volume_raw0,volume_raw0_h1,volume_raw0_p03,volume_raw0_p05,volume_raw0_p10,volume_ema0,volume_ema0_h1,volume_ema0_p03,volume_ema0_p05,volume_ema0_p10,adx0,adx0_h1,adx0_p03,adx0_p05,adx0_p10,adx_r0,adx_r0_h1,adx_r0_p03,adx_r0_p05,adx_r0_p10,adx_mdi0,adx_mdi0_h1,adx_mdi0_p03,adx_mdi0_p05,adx_mdi0_p10,adx_pdi0,adx_pdi0_h1,adx_pdi0_p03,adx_pdi0_p05,adx_pdi0_p10,adl_money_flow_multiplier0,adl_money_flow_multiplier0_h1,adl_money_flow_multiplier0_p03,adl_money_flow_multiplier0_p05,adl_money_flow_multiplier0_p10,ao0,ao0_h1,ao0_p03,ao0_p05,ao0_p10,aroon_down0,aroon_down0_h1,aroon_down0_p03,aroon_down0_p05,aroon_down0_p10,aroon_up0,aroon_up0_h1,aroon_up0_p03,aroon_up0_p05,aroon_up0_p10,aroon_oscillator0,aroon_oscillator0_h1,aroon_oscillator0_p03,aroon_oscillator0_p05,aroon_oscillator0_p10,atrp0,atrp0_h1,atrp0_p03,atrp0_p05,atrp0_p10,atr_buystop0,atr_buystop0_h1,atr_buystop0_p03,atr_buystop0_p05,atr_buystop0_p10,atr_sellstop0,atr_sellstop0_h1,atr_sellstop0_p03,atr_sellstop0_p05,atr_sellstop0_p10,bop0,bop0_h1,bop0_p03,bop0_p05,bop0_p10,cci0,cci0_h1,cci0_p03,cci0_p05,cci0_p10,chaikinmoney_flow_multiplier0,chaikinmoney_flow_multiplier0_h1,chaikinmoney_flow_multiplier0_p03,chaikinmoney_flow_multiplier0_p05,chaikinmoney_flow_multiplier0_p10,chand_exit0,chand_exit0_h1,chand_exit0_p03,chand_exit0_p05,chand_exit0_p10,choppiness0,choppiness0_h1,choppiness0_p03,choppiness0_p05,choppiness0_p10,cmf0,cmf0_h1,cmf0_p03,cmf0_p05,cmf0_p10,cmf_money_flow_multiplier0,cmf_money_flow_multiplier0_h1,cmf_money_flow_multiplier0_p03,cmf_money_flow_multiplier0_p05,cmf_money_flow_multiplier0_p10,cmo0,cmo0_h1,cmo0_p03,cmo0_p05,cmo0_p10,connor_rank0,connor_rank0_h1,connor_rank0_p03,connor_rank0_p05,connor_rank0_p10,connor_rsi0,connor_rsi0_h1,connor_rsi0_p03,connor_rsi0_p05,connor_rsi0_p10,connor_rsi_streak0,connor_rsi_streak0_h1,connor_rsi_streak0_p03,connor_rsi_streak0_p05,connor_rsi_streak0_p10,elderray_bearpower0,elderray_bearpower0_h1,elderray_bearpower0_p03,elderray_bearpower0_p05,elderray_bearpower0_p10,elderray_bullpower0,elderray_bullpower0_h1,elderray_bullpower0_p03,elderray_bullpower0_p05,elderray_bullpower0_p10,gator_lower0,gator_lower0_h1,gator_lower0_p03,gator_lower0_p05,gator_lower0_p10,gator_lower_is_expanding0,gator_lower_is_expanding0_h1,gator_lower_is_expanding0_p03,gator_lower_is_expanding0_p05,gator_lower_is_expanding0_p10,gator_upper0,gator_upper0_h1,gator_upper0_p03,gator_upper0_p05,gator_upper0_p10,gator_upper_is_expanding0,gator_upper_is_expanding0_h1,gator_upper_is_expanding0_p03,gator_upper_is_expanding0_p05,gator_upper_is_expanding0_p10,hurst_exponent0,hurst_exponent0_h1,hurst_exponent0_p03,hurst_exponent0_p05,hurst_exponent0_p10,hvz_score0,hvz_score0_h1,hvz_score0_p03,hvz_score0_p05,hvz_score0_p10,ichimoku_kijunsen0,ichimoku_kijunsen0_h1,ichimoku_kijunsen0_p03,ichimoku_kijunsen0_p05,ichimoku_kijunsen0_p10,ichimoku_senkou_span_a0,ichimoku_senkou_span_a0_h1,ichimoku_senkou_span_a0_p03,ichimoku_senkou_span_a0_p05,ichimoku_senkou_span_a0_p10,ichimoku_senkou_span_b0,ichimoku_senkou_span_b0_h1,ichimoku_senkou_span_b0_p03,ichimoku_senkou_span_b0_p05,ichimoku_senkou_span_b0_p10,ichimoku_tenkansen0,ichimoku_tenkansen0_h1,ichimoku_tenkansen0_p03,ichimoku_tenkansen0_p05,ichimoku_tenkansen0_p10,macd0,macd0_h1,macd0_p03,macd0_p05,macd0_p10,marubozu_match0,marubozu_match0_h1,marubozu_match0_p03,marubozu_match0_p05,marubozu_match0_p10,mfi0,mfi0_h1,mfi0_p03,mfi0_p05,mfi0_p10,parabolic_sar0,parabolic_sar0_h1,parabolic_sar0_p03,parabolic_sar0_p05,parabolic_sar0_p10,pivots_high_line0,pivots_high_line0_h1,pivots_high_line0_p03,pivots_high_line0_p05,pivots_high_line0_p10,pivots_high_trend0,pivots_high_trend0_h1,pivots_high_trend0_p03,pivots_high_trend0_p05,pivots_high_trend0_p10,pivots_low_line0,pivots_low_line0_h1,pivots_low_line0_p03,pivots_low_line0_p05,pivots_low_line0_p10,pivots_low_trend0,pivots_low_trend0_h1,pivots_low_trend0_p03,pivots_low_trend0_p05,pivots_low_trend0_p10,pmo0,pmo0_h1,pmo0_p03,pmo0_p05,pmo0_p10,pmo_signal0,pmo_signal0_h1,pmo_signal0_p03,pmo_signal0_p05,pmo_signal0_p10,pvo0,pvo0_h1,pvo0_p03,pvo0_p05,pvo0_p10,roc0,roc0_h1,roc0_p03,roc0_p05,roc0_p10,rsi0,rsi0_h1,rsi0_p03,rsi0_p05,rsi0_p10,schaff_stc0,schaff_stc0_h1,schaff_stc0_p03,schaff_stc0_p05,schaff_stc0_p10,smi0,smi0_h1,smi0_p03,smi0_p05,smi0_p10,srsi_signal0,srsi_signal0_h1,srsi_signal0_p03,srsi_signal0_p05,srsi_signal0_p10,srsi_stoch_rsi0,srsi_stoch_rsi0_h1,srsi_stoch_rsi0_p03,srsi_stoch_rsi0_p05,srsi_stoch_rsi0_p10,stoch_a0,stoch_a0_h1,stoch_a0_p03,stoch_a0_p05,stoch_a0_p10,stoch_a_zone0,stoch_a_zone0_h1,stoch_a_zone0_p03,stoch_a_zone0_p05,stoch_a_zone0_p10,stoch_a_cross_top0,stoch_a_cross_top0_h1,stoch_a_cross_top0_p03,stoch_a_cross_top0_p05,stoch_a_cross_top0_p10,stoch_a_cross_bottom0,stoch_a_cross_bottom0_h1,stoch_a_cross_bottom0_p03,stoch_a_cross_bottom0_p05,stoch_a_cross_bottom0_p10,stoch_b0,stoch_b0_h1,stoch_b0_p03,stoch_b0_p05,stoch_b0_p10,stoch_b_zone0,stoch_b_zone0_h1,stoch_b_zone0_p03,stoch_b_zone0_p05,stoch_b_zone0_p10,stoch_b_cross_top0,stoch_b_cross_top0_h1,stoch_b_cross_top0_p03,stoch_b_cross_top0_p05,stoch_b_cross_top0_p10,stoch_b_cross_bottom0,stoch_b_cross_bottom0_h1,stoch_b_cross_bottom0_p03,stoch_b_cross_bottom0_p05,stoch_b_cross_bottom0_p10,stoch_c0,stoch_c0_h1,stoch_c0_p03,stoch_c0_p05,stoch_c0_p10,stoch_c_zone0,stoch_c_zone0_h1,stoch_c_zone0_p03,stoch_c_zone0_p05,stoch_c_zone0_p10,stoch_c_cross_top0,stoch_c_cross_top0_h1,stoch_c_cross_top0_p03,stoch_c_cross_top0_p05,stoch_c_cross_top0_p10,stoch_c_cross_bottom0,stoch_c_cross_bottom0_h1,stoch_c_cross_bottom0_p03,stoch_c_cross_bottom0_p05,stoch_c_cross_bottom0_p10,stoch_d0,stoch_d0_h1,stoch_d0_p03,stoch_d0_p05,stoch_d0_p10,stoch_d_zone0,stoch_d_zone0_h1,stoch_d_zone0_p03,stoch_d_zone0_p05,stoch_d_zone0_p10,stoch_d_cross_top0,stoch_d_cross_top0_h1,stoch_d_cross_top0_p03,stoch_d_cross_top0_p05,stoch_d_cross_top0_p10,stoch_d_cross_bottom0,stoch_d_cross_bottom0_h1,stoch_d_cross_bottom0_p03,stoch_d_cross_bottom0_p05,stoch_d_cross_bottom0_p10,supertrend_lower0,supertrend_lower0_h1,supertrend_lower0_p03,supertrend_lower0_p05,supertrend_lower0_p10,supertrend_upper0,supertrend_upper0_h1,supertrend_upper0_p03,supertrend_upper0_p05,supertrend_upper0_p10,tsi_signal0,tsi_signal0_h1,tsi_signal0_p03,tsi_signal0_p05,tsi_signal0_p10,tsi0,tsi0_h1,tsi0_p03,tsi0_p05,tsi0_p10,ulcer_index0,ulcer_index0_h1,ulcer_index0_p03,ulcer_index0_p05,ulcer_index0_p10,uo_ultimate0,uo_ultimate0_h1,uo_ultimate0_p03,uo_ultimate0_p05,uo_ultimate0_p10,volstop_lower0,volstop_lower0_h1,volstop_lower0_p03,volstop_lower0_p05,volstop_lower0_p10,volstop_upper0,volstop_upper0_h1,volstop_upper0_p03,volstop_upper0_p05,volstop_upper0_p10,vortex_nvi0,vortex_nvi0_h1,vortex_nvi0_p03,vortex_nvi0_p05,vortex_nvi0_p10,vortex_pvi0,vortex_pvi0_h1,vortex_pvi0_p03,vortex_pvi0_p05,vortex_pvi0_p10,willfract_bear0,willfract_bear0_h1,willfract_bear0_p03,willfract_bear0_p05,willfract_bear0_p10,willfract_bull0,willfract_bull0_h1,willfract_bull0_p03,willfract_bull0_p05,willfract_bull0_p10,tgn_tunnel_high0,tgn_tunnel_high0_h1,tgn_tunnel_high0_p03,tgn_tunnel_high0_p05,tgn_tunnel_high0_p10,tgn_tunnel_low0,tgn_tunnel_low0_h1,tgn_tunnel_low0_p03,tgn_tunnel_low0_p05,tgn_tunnel_low0_p10,tgn_tunnel_high_price0,tgn_tunnel_high_price0_h1,tgn_tunnel_high_price0_p03,tgn_tunnel_high_price0_p05,tgn_tunnel_high_price0_p10,tgn_tunnel_low_price0,tgn_tunnel_low_price0_h1,tgn_tunnel_low_price0_p03,tgn_tunnel_low_price0_p05,tgn_tunnel_low_price0_p10,tgn_tunnel_high_price_change0,tgn_tunnel_high_price_change0_h1,tgn_tunnel_high_price_change0_p03,tgn_tunnel_high_price_change0_p05,tgn_tunnel_high_price_change0_p10,tgn_tunnel_low_price_change0,tgn_tunnel_low_price_change0_h1,tgn_tunnel_low_price_change0_p03,tgn_tunnel_low_price_change0_p05,tgn_tunnel_low_price_change0_p10,tgn_node_last_type0,tgn_node_last_type0_h1,tgn_node_last_type0_p03,tgn_node_last_type0_p05,tgn_node_last_type0_p10,tgn_node_price_hh0,tgn_node_price_hh0_h1,tgn_node_price_hh0_p03,tgn_node_price_hh0_p05,tgn_node_price_hh0_p10,tgn_node_price_lh0,tgn_node_price_lh0_h1,tgn_node_price_lh0_p03,tgn_node_price_lh0_p05,tgn_node_price_lh0_p10,tgn_node_price_hl0,tgn_node_price_hl0_h1,tgn_node_price_hl0_p03,tgn_node_price_hl0_p05,tgn_node_price_hl0_p10,tgn_node_price_ll0,tgn_node_price_ll0_h1,tgn_node_price_ll0_p03,tgn_node_price_ll0_p05,tgn_node_price_ll0_p10,tgn_gap_countAbove0,tgn_gap_countAbove0_h1,tgn_gap_countAbove0_p03,tgn_gap_countAbove0_p05,tgn_gap_countAbove0_p10,tgn_gap_countBelow0,tgn_gap_countBelow0_h1,tgn_gap_countBelow0_p03,tgn_gap_countBelow0_p05,tgn_gap_countBelow0_p10,tgn_gap_distanceClosestAbove0,tgn_gap_distanceClosestAbove0_h1,tgn_gap_distanceClosestAbove0_p03,tgn_gap_distanceClosestAbove0_p05,tgn_gap_distanceClosestAbove0_p10,tgn_gap_distanceClosestBelow0,tgn_gap_distanceClosestBelow0_h1,tgn_gap_distanceClosestBelow0_p03,tgn_gap_distanceClosestBelow0_p05,tgn_gap_distanceClosestBelow0_p10,tgn_gap_sizeClosestAbove0,tgn_gap_sizeClosestAbove0_h1,tgn_gap_sizeClosestAbove0_p03,tgn_gap_sizeClosestAbove0_p05,tgn_gap_sizeClosestAbove0_p10,tgn_gap_sizeClosestBelow0,tgn_gap_sizeClosestBelow0_h1,tgn_gap_sizeClosestBelow0_p03,tgn_gap_sizeClosestBelow0_p05,tgn_gap_sizeClosestBelow0_p10,tgn_gap_directionClosestAbove0,tgn_gap_directionClosestAbove0_h1,tgn_gap_directionClosestAbove0_p03,tgn_gap_directionClosestAbove0_p05,tgn_gap_directionClosestAbove0_p10,tgn_gap_directionClosestBelow0,tgn_gap_directionClosestBelow0_h1,tgn_gap_directionClosestBelow0_p03,tgn_gap_directionClosestBelow0_p05,tgn_gap_directionClosestBelow0_p10,tgn_gap_avgDistanceAbove0,tgn_gap_avgDistanceAbove0_h1,tgn_gap_avgDistanceAbove0_p03,tgn_gap_avgDistanceAbove0_p05,tgn_gap_avgDistanceAbove0_p10,tgn_gap_avgDistanceBelow0,tgn_gap_avgDistanceBelow0_h1,tgn_gap_avgDistanceBelow0_p03,tgn_gap_avgDistanceBelow0_p05,tgn_gap_avgDistanceBelow0_p10,tgn_LL_countAbove0,tgn_LL_countAbove0_h1,tgn_LL_countAbove0_p03,tgn_LL_countAbove0_p05,tgn_LL_countAbove0_p10,tgn_LL_countBelow0,tgn_LL_countBelow0_h1,tgn_LL_countBelow0_p03,tgn_LL_countBelow0_p05,tgn_LL_countBelow0_p10,tgn_ll_distanceClosestAbove0,tgn_ll_distanceClosestAbove0_h1,tgn_ll_distanceClosestAbove0_p03,tgn_ll_distanceClosestAbove0_p05,tgn_ll_distanceClosestAbove0_p10,tgn_ll_distanceClosestBelow0,tgn_ll_distanceClosestBelow0_h1,tgn_ll_distanceClosestBelow0_p03,tgn_ll_distanceClosestBelow0_p05,tgn_ll_distanceClosestBelow0_p10,tgn_ll_directionClosestAbove0,tgn_ll_directionClosestAbove0_h1,tgn_ll_directionClosestAbove0_p03,tgn_ll_directionClosestAbove0_p05,tgn_ll_directionClosestAbove0_p10,tgn_ll_directionClosestBelow0,tgn_ll_directionClosestBelow0_h1,tgn_ll_directionClosestBelow0_p03,tgn_ll_directionClosestBelow0_p05,tgn_ll_directionClosestBelow0_p10,tgn_ll_avgDistanceAbove0,tgn_ll_avgDistanceAbove0_h1,tgn_ll_avgDistanceAbove0_p03,tgn_ll_avgDistanceAbove0_p05,tgn_ll_avgDistanceAbove0_p10,tgn_ll_avgDistanceBelow0,tgn_ll_avgDistanceBelow0_h1,tgn_ll_avgDistanceBelow0_p03,tgn_ll_avgDistanceBelow0_p05,tgn_ll_avgDistanceBelow0_p10,tgn_coc_last_distance0,tgn_coc_last_distance0_h1,tgn_coc_last_distance0_p03,tgn_coc_last_distance0_p05,tgn_coc_last_distance0_p10,tgn_coc_last_direction0,tgn_coc_last_direction0_h1,tgn_coc_last_direction0_p03,tgn_coc_last_direction0_p05,tgn_coc_last_direction0_p10,tgn_coc_count_last_5_hours0,tgn_coc_count_last_5_hours0_h1,tgn_coc_count_last_5_hours0_p03,tgn_coc_count_last_5_hours0_p05,tgn_coc_count_last_5_hours0_p10,tgn_coc_count_last_10_hours0,tgn_coc_count_last_10_hours0_h1,tgn_coc_count_last_10_hours0_p03,tgn_coc_count_last_10_hours0_p05,tgn_coc_count_last_10_hours0_p10,tgn_coc_time_since_last_event0,tgn_coc_time_since_last_event0_h1,tgn_coc_time_since_last_event0_p03,tgn_coc_time_since_last_event0_p05,tgn_coc_time_since_last_event0_p10,tgn_coc_avg_interval_dist_between0,tgn_coc_avg_interval_dist_between0_h1,tgn_coc_avg_interval_dist_between0_p03,tgn_coc_avg_interval_dist_between0_p05,tgn_coc_avg_interval_dist_between0_p10,tgn_coc_avg_price_dist_between0,tgn_coc_avg_price_dist_between0_h1,tgn_coc_avg_price_dist_between0_p03,tgn_coc_avg_price_dist_between0_p05,tgn_coc_avg_price_dist_between0_p10,tgn_coc_long_count0,tgn_coc_long_count0_h1,tgn_coc_long_count0_p03,tgn_coc_long_count0_p05,tgn_coc_long_count0_p10,tgn_coc_short_count0,tgn_coc_short_count0_h1,tgn_coc_short_count0_p03,tgn_coc_short_count0_p05,tgn_coc_short_count0_p10,tgn_mss_last_distance0,tgn_mss_last_distance0_h1,tgn_mss_last_distance0_p03,tgn_mss_last_distance0_p05,tgn_mss_last_distance0_p10,tgn_mss_last_direction0,tgn_mss_last_direction0_h1,tgn_mss_last_direction0_p03,tgn_mss_last_direction0_p05,tgn_mss_last_direction0_p10,tgn_mss_count_last_5_hours0,tgn_mss_count_last_5_hours0_h1,tgn_mss_count_last_5_hours0_p03,tgn_mss_count_last_5_hours0_p05,tgn_mss_count_last_5_hours0_p10,tgn_mss_count_last_10_hours0,tgn_mss_count_last_10_hours0_h1,tgn_mss_count_last_10_hours0_p03,tgn_mss_count_last_10_hours0_p05,tgn_mss_count_last_10_hours0_p10,tgn_mss_time_since_last_event0,tgn_mss_time_since_last_event0_h1,tgn_mss_time_since_last_event0_p03,tgn_mss_time_since_last_event0_p05,tgn_mss_time_since_last_event0_p10,tgn_mss_avg_interval_dist_between0,tgn_mss_avg_interval_dist_between0_h1,tgn_mss_avg_interval_dist_between0_p03,tgn_mss_avg_interval_dist_between0_p05,tgn_mss_avg_interval_dist_between0_p10,tgn_mss_avg_price_dist_between0,tgn_mss_avg_price_dist_between0_h1,tgn_mss_avg_price_dist_between0_p03,tgn_mss_avg_price_dist_between0_p05,tgn_mss_avg_price_dist_between0_p10,tgn_mss_long_count0,tgn_mss_long_count0_h1,tgn_mss_long_count0_p03,tgn_mss_long_count0_p05,tgn_mss_long_count0_p10,tgn_mss_short_count0,tgn_mss_short_count0_h1,tgn_mss_short_count0_p03,tgn_mss_short_count0_p05,tgn_mss_short_count0_p10,tgn_fair_price0,tgn_fair_price0_h1,tgn_fair_price0_p03,tgn_fair_price0_p05,tgn_fair_price0_p10,tgn_tunnel_breakout0,tgn_tunnel_breakout0_h1,tgn_tunnel_breakout0_p03,tgn_tunnel_breakout0_p05,tgn_tunnel_breakout0_p10,tgn_tunnel_break_from_price0,tgn_tunnel_break_from_price0_h1,tgn_tunnel_break_from_price0_p03,tgn_tunnel_break_from_price0_p05,tgn_tunnel_break_from_price0_p10,tgn_compression_zone_breakout0,tgn_compression_zone_breakout0_h1,tgn_compression_zone_breakout0_p03,tgn_compression_zone_breakout0_p05,tgn_compression_zone_breakout0_p10,tgn_compression_zone_break_from_price0,tgn_compression_zone_break_from_price0_h1,tgn_compression_zone_break_from_price0_p03,tgn_compression_zone_break_from_price0_p05,tgn_compression_zone_break_from_price0_p10,tgn_in_zone0,tgn_in_zone0_h1,tgn_in_zone0_p03,tgn_in_zone0_p05,tgn_in_zone0_p10
```

when I don't specify that the file has a header, I get this error instead:

```
Start Training
System.Exception: Train dataset and validate dataset schema is not compatible. Column(s) col0, col4, col5, col6, col7, col8, col9, col10, col11, col12, col13, col14, col15, col16, col17, col18, col19, col20, col21, col22, col23, col24, col25, col26, col27, col28, col29, col30, col31, col32, col33, col34, col35, col36, col37, col38, col39, col40, col41, col42, col43, col44, col45, col46, col47, col48, col49, col50, col51, col52, col53, col54, col55, col56, col57, col58, col59, col60, col61, col62, col63, col64, col65, col66, col67, col68, col69, col70, col71, col72, col73, col74, col75, col76, col77, col78, col79, col80, col81, col82, col83, col84, col85, col86, col87, col88, col89, col90, col91, col92, col93, col94, col95, col96, col97, col98, col99, col100, col101, col102, col103, col104, col105, col106, col107, col108, col109, col110, col111, col112, col113, col114, col115, col116, col117, col118, col119, col120, col121, col122, col123, col124, col125, col126, col127, col128, col129, col130, col131, col132, col133, col134, col135, col136, col137, col138, col139, col140, col141, col142, col143, col144, col145, col146, col147, col148, col149, col150, col151, col152, col153, col154, col155, col156, col157, col158, col159, col160, col161, col162, col163, col164, col165, col166, col167, col168, col169, col170, col171, col172, col173, col174, col175, col176, col177, col178, col179, col180, col181, col182, col183, col184, col185, col186, col187, col188, col189, col190, col191, col192, col193, col194, col195, col196, col197, col198, col199, col200, col201, col202, col203, col204, col205, col206, col207, col208, col209, col210, col211, col212, col213, col214, col215, col216, col217, col218, col219, col220, col221, col222, col223, col224, col225, col226, col227, col228, col229, col230, col231, col232, col233, col234, col235, col236, col237, col238, col239, col240, col241, col242, col243, col244, col245, col246, col247, col248, col249, col250, col251, col252, col253, col254, col255, col256, col257, col258, col259, col260, col261, col262, col263, col264, col265, col266, col267, col268, col269, col270, col271, col272, col273, col274, col275, col276, col277, col278, col279, col280, col281, col282, col283, col284, col285, col286, col287, col288, col289, col290, col291, col292, col293, col294, col295, col296, col297, col298, col299, col300, col301, col302, col303, col304, col305, col306, col307, col308, col309, col310, col311, col312, col313, col314, col315, col316, col317, col318, col319, col320, col321, col322, col323, col324, col325, col326, col327, col328, col329, col330, col331, col332, col333, col334, col335, col336, col337, col338, col339, col340, col341, col342, col343, col344, col345, col346, col347, col348, col349, col350, col351, col352, col353, col354, col355, col356, col357, col358, col359, col360, col361, col362, col363, col364, col365, col366, col367, col368, col369, col370, col371, col372, col373, col374, col375, col376, col377, col378, col379, col380, col381, col382, col383, col384, col385, col386, col387, col388, col389, col390, col391, col392, col393, col394, col395, col396, col397, col398, col399, col400, col401, col402, col403, col404, col405, col406, col407, col408, col409, col410, col411, col412, col413, col414, col415, col416, col417, col418, col419, col420, col421, col422, col423, col424, col425, col426, col427, col428, col429, col430, col431, col432, col433, col434, col435, col436, col437, col438, col439, col440, col441, col442, col443, col444, col445, col446, col447, col448, col449, col450, col451, col452, col453, col454, col455, col456, col457, col458, col459, col460, col461, col462, col463, col464, col465, col466, col467, col468, col469, col470, col471, col472, col473, col474, col475, col476, col477, col478, col479, col480, col481, col482, col483, col484, col485, col486, col487, col488, col489, col490, col491, col492, col493, col494, col495, col496, col497, col498, col499, col500, col501, col502, col503, col504, col505, col506, col507, col508, col509, col510, col511, col512, col513, col514, col515, col516, col517, col518, col519, col520, col521, col522, col523, col524, col525, col526, col527, col528, col529, col530, col531, col532, col533, col534, col535, col536, col537, col538, col539, col540, col541, col542, col543, col544, col545, col546, col547, col548, col549, col550, col551, col552, col553, col554, col555, col556, col557, col558, col559, col560, col561, col562, col563, col564, col565, col566, col567, col568, col569, col570, col571, col572, col573, col574, col575, col576, col577, col578, col579, col580, col581, col582, col583, col584, col585, col586, col587, col588, col589, col590, col591, col592, col593, col594, col595, col596, col597, col598, col599, col600, col601, col602, col603, col604, col605, col606, col607, col608, col609, col610, col611, col612, col613, col614, col615, col616, col617, col618, col619, col620, col621, col622, col623, col624, col625, col626, col627, col628, col629, col630, col631, col632, col633, col634, col635, col636, col637, col638, col639, col640, col641, col642, col643, col644, col645, col646, col647, col648, col649, col650, col651, col652, col653, col654, col655, col656, col657, col658, col659, col660, col661, col662, col663, col664, col665, col666, col667, col668, col669, col670, col671, col672, col673, col674, col675, col676, col677, col678, col679, col680, col681, col682, col683, col684, col685, col686, col687, col688, col689, col690, col691, col692, col693, col694, col695, col696, col697, col698, col699, col700, col701, col702, col703, col704, col705, col706, col707, col708, col709, col710, col711, col712, col713 are not found in validate dataset.
   at Microsoft.ML.ModelBuilder.AutoMLEngine.GetValidateDatasetLoaderOption(ITrainingConfiguration config, IEnumerable`1 validateColumnInfo, Char decimalSeparator, String delimiter, Boolean hasHeader) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 307
   at Microsoft.ML.ModelBuilder.AutoMLEngine.GetValidateDatasetTextLoaderOptionAsync(ITrainingConfiguration config) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 398
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 106

```

**Comment by smp73** [comment]
![Image](https://github.com/user-attachments/assets/97db7429-cdad-4224-8464-4e78bbdb7957)
