### ISSUE TITLE
Flaky assert failure in SDCA test 

### ISSUE THREAD

**Issue by Zruty0** [dotnet/machinelearning#918]
```
2018-09-13T23:25:02.4332634Z Failed   Microsoft.ML.Scenarios.ScenariosTests.TrainAndPredictIrisModelWithStringLabelTest
2018-09-13T23:25:02.4332936Z Error Message:
2018-09-13T23:25:02.4333077Z  Assert failed: longIdx=37, invariants.Length=37
2018-09-13T23:25:02.4333210Z Expected: True
2018-09-13T23:25:02.4333341Z Actual:   False
2018-09-13T23:25:02.4333453Z Stack Trace:
2018-09-13T23:25:02.4333653Z    at Microsoft.ML.Runtime.Internal.Internallearn.Test.GlobalBase.AssertHandler(String msg, IExceptionContext ectx) in D:\a\1\s\test\Microsoft.ML.TestFramework\GlobalBase.cs:line 47
2018-09-13T23:25:02.4333951Z    at Microsoft.ML.Runtime.Contracts.DbgFailCore(String msg, IExceptionContext ctx) in D:\a\1\s\src\Microsoft.ML.Core\Utilities\Contracts.cs:line 770
2018-09-13T23:25:02.4334183Z    at Microsoft.ML.Runtime.Contracts.DbgFail(String msg) in D:\a\1\s\src\Microsoft.ML.Core\Utilities\Contracts.cs:line 783
2018-09-13T23:25:02.4334404Z    at Microsoft.ML.Runtime.Contracts.Assert(Boolean f, String msg) in D:\a\1\s\src\Microsoft.ML.Core\Utilities\Contracts.cs:line 841
2018-09-13T23:25:02.4334962Z    at Microsoft.ML.Runtime.Learners.SdcaTrainerBase`2.TrainCore(IChannel ch, RoleMappedData data, LinearPredictor predictor, Int32 weightSetCount) in D:\a\1\s\src\Microsoft.ML.StandardLearners\Standard\LinearClassificationTrainer.cs:line 514
2018-09-13T23:25:02.4335278Z    at Microsoft.ML.Runtime.Learners.StochasticTrainerBase`2.TrainModelCore(TrainContext context) in D:\a\1\s\src\Microsoft.ML.StandardLearners\Standard\StochasticTrainerBase.cs:line 42
2018-09-13T23:25:02.4335567Z    at Microsoft.ML.Runtime.Training.TrainerEstimatorBase`2.Train(TrainContext context) in D:\a\1\s\src\Microsoft.ML.Data\Training\TrainerEstimatorBase.cs:line 88
2018-09-13T23:25:02.4336480Z    at Microsoft.ML.Runtime.Training.TrainerEstimatorBase`2.Microsoft.ML.Runtime.ITrainer.Train(TrainContext context) in D:\a\1\s\src\Microsoft.ML.Data\Training\TrainerEstimatorBase.cs:line 154
2018-09-13T23:25:02.4336826Z    at Microsoft.ML.Runtime.Data.TrainUtils.TrainCore(IHostEnvironment env, IChannel ch, RoleMappedData data, ITrainer trainer, RoleMappedData validData, ICalibratorTrainer calibrator, Int32 maxCalibrationExamples, Nullable`1 cacheData, IPredictor inputPredictor) in D:\a\1\s\src\Microsoft.ML.Data\Commands\TrainCommand.cs:line 260
2018-09-13T23:25:02.4337494Z    at Microsoft.ML.Runtime.Data.TrainUtils.Train(IHostEnvironment env, IChannel ch, RoleMappedData data, ITrainer trainer, ICalibratorTrainerFactory calibrator, Int32 maxCalibrationExamples) in D:\a\1\s\src\Microsoft.ML.Data\Commands\TrainCommand.cs:line 228
2018-09-13T23:25:02.4337856Z    at Microsoft.ML.Runtime.EntryPoints.LearnerEntryPointsUtils.Train[TArg,TOut](IHost host, TArg input, Func`1 createTrainer, Func`1 getLabel, Func`1 getWeight, Func`1 getGroup, Func`1 getName, Func`1 getCustom, ICalibratorTrainerFactory calibrator, Int32 maxCalibrationExamples) in D:\a\1\s\src\Microsoft.ML.Data\EntryPoints\InputBase.cs:line 189
2018-09-13T23:25:02.4338176Z    at Microsoft.ML.Runtime.Learners.Sdca.TrainMultiClass(IHostEnvironment env, Arguments input) in D:\a\1\s\src\Microsoft.ML.StandardLearners\Standard\SdcaMultiClass.cs:line 437
```

The data  pipeline has a `TextLoader`, a `Dictionarizer` and `ColumnConcatenator`, then it trains SDCA classifier.

@TomFinley suggests that it could be related to the difference in ID generation between iterations. 
The fact that the test is not failing every time suggests that either there is a race condition somewhere (in the `TextLoader`?), or somehow the data is sometimes modified mid-run.

**Comment by codemzs** [comment]
don't think this applies with the stable API. Our SDCA test quite reliably these days.
